var annotated_dup =
[
    [ "os", "namespaceos.html", "namespaceos" ],
    [ "exception_stack_frame_s", "structexception__stack__frame__s.html", "structexception__stack__frame__s" ],
    [ "os_clock_node_s", "structos__clock__node__s.html", "structos__clock__node__s" ],
    [ "os_condvar_attr_s", "structos__condvar__attr__s.html", "structos__condvar__attr__s" ],
    [ "os_condvar_s", "structos__condvar__s.html", "structos__condvar__s" ],
    [ "os_double_list_links_s", "structos__double__list__links__s.html", "structos__double__list__links__s" ],
    [ "os_evflags_attr_s", "structos__evflags__attr__s.html", "structos__evflags__attr__s" ],
    [ "os_evflags_s", "structos__evflags__s.html", "structos__evflags__s" ],
    [ "os_mail_queue_s", "structos__mail__queue__s.html", "structos__mail__queue__s" ],
    [ "os_mailQ_def", "structos__mail_q__def.html", "structos__mail_q__def" ],
    [ "os_mempool_attr_s", "structos__mempool__attr__s.html", "structos__mempool__attr__s" ],
    [ "os_mempool_s", "structos__mempool__s.html", "structos__mempool__s" ],
    [ "os_messageQ_def", "structos__message_q__def.html", "structos__message_q__def" ],
    [ "os_mqueue_attr_s", "structos__mqueue__attr__s.html", "structos__mqueue__attr__s" ],
    [ "os_mqueue_s", "structos__mqueue__s.html", "structos__mqueue__s" ],
    [ "os_mutex_attr_s", "structos__mutex__attr__s.html", "structos__mutex__attr__s" ],
    [ "os_mutex_def", "structos__mutex__def.html", "structos__mutex__def" ],
    [ "os_mutex_s", "structos__mutex__s.html", "structos__mutex__s" ],
    [ "os_pool_def", "structos__pool__def.html", "structos__pool__def" ],
    [ "os_semaphore_attr_s", "structos__semaphore__attr__s.html", "structos__semaphore__attr__s" ],
    [ "os_semaphore_def", "structos__semaphore__def.html", "structos__semaphore__def" ],
    [ "os_semaphore_s", "structos__semaphore__s.html", "structos__semaphore__s" ],
    [ "os_systick_clock_current_s", "structos__systick__clock__current__s.html", "structos__systick__clock__current__s" ],
    [ "os_thread_attr_s", "structos__thread__attr__s.html", "structos__thread__attr__s" ],
    [ "os_thread_children_list_s", "structos__thread__children__list__s.html", "structos__thread__children__list__s" ],
    [ "os_thread_context_s", "structos__thread__context__s.html", "structos__thread__context__s" ],
    [ "os_thread_def", "structos__thread__def.html", "structos__thread__def" ],
    [ "os_thread_s", "structos__thread__s.html", "structos__thread__s" ],
    [ "os_thread_user_storage_t", "structos__thread__user__storage__t.html", "structos__thread__user__storage__t" ],
    [ "os_timer_attr_s", "structos__timer__attr__s.html", "structos__timer__attr__s" ],
    [ "os_timer_def", "structos__timer__def.html", "structos__timer__def" ],
    [ "os_timer_s", "structos__timer__s.html", "structos__timer__s" ],
    [ "os_waiting_thread_node_s", "structos__waiting__thread__node__s.html", "structos__waiting__thread__node__s" ],
    [ "osEvent", "structos_event.html", "structos_event" ]
];