CMSIS++ Reference: os::rtos::Semaphore Class Reference
os::rtos::Semaphore Class Reference
POSIX semaphore.
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Semaphore ()
Create a default semaphore.
Semaphore (const semaphore::Attributes &attr)
Create custom semaphore.
Semaphore (const Semaphore &)=delete
Semaphore (Semaphore &&)=delete
Semaphore & operator= (const Semaphore &)=delete
Semaphore & operator= (Semaphore &&)=delete
~Semaphore ()
Destroy the semaphore.
bool operator== (const Semaphore &rhs) const
Compare semaphores.
result_t post (void)
Post (unlock) the semaphore.
result_t wait ()
Lock the semaphore, possibly waiting.
result_t try_wait ()
Try to lock the semaphore.
result_t timed_wait (systicks_t ticks)
Timed wait to lock the semaphore.
semaphore::count_t value (void) const
Get the semaphore value.
result_t reset (void)
Reset the semaphore.
semaphore::count_t initial_value (void) const
semaphore::count_t max_value (void) const
const char * name (void) const
Protected Attributes
port::Tasks_list list_
const semaphore::count_t initial_count_
volatile semaphore::count_t count_
const semaphore::count_t max_count_
const char *const name_
Detailed Description
POSIX semaphore.
Supports both counting and binary semaphores.
Semaphores should generally be used to synchronise with events occuring on interrupts.
For inter-thread synchronisation, to avoid cases of priority inversion, more suitable are mutexes.
Compatible with POSIX semaphores. http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/semaphore.h.html
Definition at line 1611 of file os.h.
Constructor & Destructor Documentation
os::rtos::Semaphore::Semaphore ()
Create a default semaphore.
Create and initialise a semaphore with default attributes. Initialise the semaphore with count=0 and no limit for count.
Compatible with POSIX sem_init(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_init.html#
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 61 of file os-semaphore.cpp.
References os::rtos::semaphore::counting_initializer.
                           :
         Semaphore
           { semaphore::counting_initializer }
     {
       ;
     }
os::rtos::Semaphore::Semaphore (const semaphore::Attributes & attr)
Create custom semaphore.
Create and initialise a semaphore with custom attributes.
Compatible with POSIX sem_init(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_init.html#
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 77 of file os-semaphore.cpp.
References attr, count_, os::rtos::scheduler::in_handler_mode(), initial_count_, max_count_, os::rtos::Named_object::name(), os_assert_throw, and os::trace::printf().
                                                          :
         Named_object
           { attr.name () }, //
         initial_count_ (attr.sm_initial_count), //
         max_count_ (attr.sm_max_count)
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       // The CMSIS validator requires the max_count to be equal to
       // the initial count, which can be 0, but we patch it on the way.
       assert(max_count_ > 0);
       assert(attr.sm_initial_count <= max_count_);
       count_ = attr.sm_initial_count;
       // TODO check if initial count can be negative, to validate.
       trace::printf ("%s() @%p %s %d %d\n", __func__, this, name (), count_,
                      max_count_);
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       port::Semaphore::create (this);
 #else
       // TODO
 #endif
     }
os::rtos::Semaphore::Semaphore (const Semaphore &) delete
os::rtos::Semaphore::Semaphore (Semaphore &&) delete
os::rtos::Semaphore::~Semaphore ()
Destroy the semaphore.
It is safe to destroy an initialised semaphore upon which no threads are currently blocked. The effect of destroying a semaphore upon which other threads are currently blocked is undefined.
Compatible with POSIX sem_destroy(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_destroy.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 120 of file os-semaphore.cpp.
References os::rtos::Named_object::name(), and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       port::Semaphore::destroy (this);
 #else
       // TODO
 #endif
     }
Member Function Documentation
semaphore::count_t os::rtos::Semaphore::initial_value (void) const inline
Definition at line 2857 of file os.h.
     {
       return initial_count_;
     }
semaphore::count_t os::rtos::Semaphore::max_value (void) const inline
Definition at line 2863 of file os.h.
     {
       return max_count_;
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), try_wait(), wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and ~Semaphore().
     {
       return name_;
     }
Semaphore& os::rtos::Semaphore::operator= (const Semaphore &) delete
Semaphore& os::rtos::Semaphore::operator= (Semaphore &&) delete
bool os::rtos::Semaphore::operator== (const Semaphore & rhs) const inline
Compare semaphores.
Return values
true The given semaphore is the same as this semaphore.
false The semaphores are different.
Identical semaphores should have the same memory address.
Definition at line 2840 of file os.h.
     {
       return this == &rhs;
     }
result_t os::rtos::Semaphore::post (void)
Post (unlock) the semaphore.
Return values
result::ok The semaphore was posted.
EOVERFLOW The max count was exceeded.
ENOTRECOVERABLE The semaphore could not be posted (extension to POSIX).
Performe a post operation on the semaphore, informing the waiting consumers that one more resource is available. The semaphore count is incremented, up to max_count.
If the semaphore count resulting from this operation is positive, then no threads were blocked waiting for the semaphore to become unlocked.
If the count of the semaphore resulting from this operation is zero, then one of the threads blocked waiting for the semaphore shall be allowed to return successfully from its call to Semaphore::wait().
If the Process Scheduling option is supported, the thread to be unblocked shall be chosen in a manner appropriate to the scheduling policies and parameters in effect for the blocked threads. In the case of the schedulers SCHED_FIFO and SCHED_RR, the highest priority waiting thread shall be unblocked, and if there is more than one highest priority thread blocked waiting for the semaphore, then the highest priority thread that has been waiting the longest shall be unblocked. If the Process Scheduling option is not defined, the choice of a thread to unblock is unspecified. If the scheduling policy is SCHED_SPORADIC, the semantics are as per SCHED_FIFO.
Compatible with POSIX sem_post() http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_post.html
Note
Can be invoked from Interrupt Service Routines.
Warning
Applications using these functions may be subject to priority inversion.
Definition at line 171 of file os-semaphore.cpp.
References count_, list_, max_count_, os::rtos::Named_object::name(), os::rtos::result::ok, and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Semaphore::post (this);
 #else
       interrupts::Critical_section cs; // ----- Critical section -----
       if (count_ >= this->max_count_)
         {
           return EOVERFLOW;
         }
       ++count_;
       if (count_ == 0)
         {
           // Wakeup one thread
           if (list_.get_length () > 0)
             {
               list_.get_top ()->wakeup ();
             }
         }
       return result::ok;
 #endif
     }
result_t os::rtos::Semaphore::reset (void)
Reset the semaphore.
Return values
result::ok The semaphore was reset.
EPERM Cannot be invoked from an Interrupt Service Routine.
Set the counter to the initial value.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 377 of file os-semaphore.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), initial_count_, os::rtos::result::ok, os_assert_err, and os::driver::usb::device::reset.
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Semaphore::reset (this);
 #else
       interrupts::Critical_section cs; // ----- Critical section -----
       if (count_ < 0)
         {
           // There are waiting tasks
           return EAGAIN;
         }
       count_ = initial_count_;
       return result::ok;
 #endif
     }
result_t os::rtos::Semaphore::timed_wait (systicks_t ticks)
Timed wait to lock the semaphore.
Parameters
[in] ticks Number of ticks to wait.
Return values
result::ok The calling process successfully performed the semaphore lock operation.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINVAL Invalid timeout (POSIX limits the timeout to 1000 million ns)
ETIMEDOUT The semaphore could not be locked before the specified timeout expired.
ENOTRECOVERABLE Semaphore wait failed (extension to POSIX).
EDEADLK A deadlock condition was detected.
EINTR The operation was interrupted.
Try to perform a lock operation; if the semaphore cannot be locked without waiting for another process or thread to unlock the semaphore by performing a Semaphore::post() function, this wait shall be terminated when the specified timeout expires.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Under no circumstance shall the function fail with a timeout if the semaphore can be locked immediately. The validity of the timeout need not be checked if the semaphore can be locked immediately.
Compatible with POSIX sem_timedwait(), except the time point is replaced with a duration. http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_timedwait.html
Warning
Cannot be invoked from Interrupt Service Routines.
Applications using these functions may be subject to priority inversion.
Definition at line 333 of file os-semaphore.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), list_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), os::rtos::this_thread::thread(), and os::rtos::Systick_clock::wait().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d_ticks) @%p %s\n", __func__, ticks, this, name ());
       if (ticks == 0)
         {
           ticks = 1;
         }
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Semaphore::timed_wait (this, ticks);
 #else
         {
           interrupts::Critical_section cs; // ----- Critical section -----
           --count_;
           if (count_ >= 0)
             {
               return result::ok;
             }
           // Add current thread to the semaphore waiting list.
           list_.add (&this_thread::thread ());
         }
       Systick_clock::wait (ticks);
       // TODO: return EINTR
       return ETIMEDOUT;
 #endif
     }
result_t os::rtos::Semaphore::try_wait ()
Try to lock the semaphore.
Return values
result::ok The calling process successfully performed the semaphore lock operation.
EPERM Cannot be invoked from an Interrupt Service Routine.
EAGAIN The semaphore was already locked.
ENOTRECOVERABLE Semaphore wait failed (extension to POSIX).
EDEADLK A deadlock condition was detected.
EINTR The operation was interrupted.
Tries to perform a lock operation only if the semaphore is currently not locked; that is, if the semaphore value is currently positive it decrements it and returns success. Otherwise, it shall not lock the semaphore.
Upon successful return, the state of the semaphore shall be locked and shall remain locked until the post() function is executed and returns successfully.
Compatible with POSIX sem_trywait(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_wait.html
Note
Can be invoked from Interrupt Service Routines.
Warning
Applications using these functions may be subject to priority inversion.
Definition at line 280 of file os-semaphore.cpp.
References count_, os::rtos::Named_object::name(), os::rtos::result::ok, and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Semaphore::try_wait (this);
 #else
         {
           interrupts::Critical_section cs; // ----- Critical section -----
           if (count_ > 0)
             {
               --count_;
               return result::ok;
             }
           // Count may be 0 or negative
           return EAGAIN;
         }
 #endif
     }
semaphore::count_t os::rtos::Semaphore::value (void) const inline
Get the semaphore value.
Returns
The semaphore value.
If positive, the semaphore value reflects the number of available resources. If negative, it counts the waiting tasks.
Definition at line 2851 of file os.h.
     {
       return count_;
     }
result_t os::rtos::Semaphore::wait ()
Lock the semaphore, possibly waiting.
Return values
result::ok The calling process successfully performed the semaphore lock operation.
EPERM Cannot be invoked from an Interrupt Service Routine.
ENOTRECOVERABLE Semaphore wait failed (extension to POSIX).
EDEADLK A deadlock condition was detected.
EINTR The operation was interrupted.
Perform a lock operation on the semaphore.
If the current value is positive, it is decremented, and the call returns immediately
If the semaphore value is currently zero, then the calling thread shall not return from the call to wait() until it either locks the semaphore or the call is interrupted by a signal.
Upon successful return, the state of the semaphore shall be locked and shall remain locked until the post() function is executed and returns successfully.
The function is interruptible by the delivery of an external event (signal, thread cancel, etc).
Compatible with POSIX sem_wait(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_wait.html
Warning
Cannot be invoked from Interrupt Service Routines.
Applications using these functions may be subject to priority inversion.
Definition at line 229 of file os-semaphore.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), list_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), os::rtos::this_thread::thread(), and os::rtos::this_thread::yield().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Semaphore::wait (this);
 #else
         {
           interrupts::Critical_section cs; // ----- Critical section ------
           --count_;
           if (count_ >= 0)
             {
               return result::ok;
             }
           // Add current thread to the semaphore waiting  list
           list_.add (&this_thread::thread ());
           // `count_` is negative.
         }
       this_thread::yield ();
       // Return EINTR?
       return result::ok;
 #endif
     }
Member Data Documentation
volatile semaphore::count_t os::rtos::Semaphore::count_ protected
Definition at line 1732 of file os.h.
Referenced by post(), reset(), Semaphore(), timed_wait(), try_wait(), and wait().
const semaphore::count_t os::rtos::Semaphore::initial_count_ protected
Definition at line 1729 of file os.h.
Referenced by reset(), and Semaphore().
port::Tasks_list os::rtos::Semaphore::list_ protected
Definition at line 1721 of file os.h.
Referenced by post(), timed_wait(), and wait().
const semaphore::count_t os::rtos::Semaphore::max_count_ protected
Definition at line 1735 of file os.h.
Referenced by post(), and Semaphore().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-semaphore.cpp