CMSIS++ Reference: os::rtos::Realtime_clock Class Reference
os::rtos::Realtime_clock Class Reference
#include <os.h>
Public Types
using rep = uint64_t
using sleep_rep = duration_t
Static Public Member Functions
static rep now (void)
Tell the absolute time now.
static result_t sleep_for (sleep_rep secs)
Sleep a number of seconds.
static result_t initialize (void)
Static Public Attributes
static constexpr uint32_t frequency_hz = 1
Detailed Description
Definition at line 951 of file os.h.
Member Typedef Documentation
using os::rtos::Realtime_clock::rep = uint64_t
Definition at line 956 of file os.h.
using os::rtos::Realtime_clock::sleep_rep = duration_t
Definition at line 957 of file os.h.
Member Function Documentation
result_t os::rtos::Realtime_clock::initialize (void) static
Must be called only once, during inits.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 283 of file os-clocks.cpp.
References os::rtos::__rtc_now, os::rtos::scheduler::in_handler_mode(), now(), os::rtos::result::ok, and os_assert_err.
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       // TODO: Use the RTC driver to initialise the seconds to epoch.
       return result::ok;
     }
Realtime_clock::rep os::rtos::Realtime_clock::now (void) static noexcept
Tell the absolute time now.
Returns
The number of seconds since 1 January 1970 00:00:00.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 56 of file chrono.cpp.
References os::rtos::Systick_clock::now().
Referenced by initialize(), and os_realtime_clock_now().
       {
         const auto secs = rtos::Realtime_clock::now ();
         return time_point
           { duration
             { secs } };
       }
result_t os::rtos::Realtime_clock::sleep_for (Realtime_clock::sleep_rep secs) static
Sleep a number of seconds.
Parameters
[in] secs the number of seconds to sleep.
Return values
ETIMEDOUT The sleep lasted the entire duration.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINTR The sleep was interrupted.
Put the current thread to sleep, until the next n-th RTC second occurs. Depending when the call is issued, the first second counted may be very short.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 312 of file os-clocks.cpp.
References os::rtos::__rtc_now, os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
Referenced by os_realtime_clock_sleep_for().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("Realtime_clock::sleep_for(%ds)\n", secs);
       // TODO
       __rtc_now += secs;
       return result::ok;
     }
Member Data Documentation
constexpr uint32_t os::rtos::Realtime_clock::frequency_hz = 1 static
Definition at line 955 of file os.h.
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/libcpp/chrono.cpp
src/cmsis-plus/rtos/os-clocks.cpp