CMSIS++ Reference: os::rtos::Message_queue Class Reference
os::rtos::Message_queue Class Reference
POSIX message queue.
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Message_queue (mqueue::size_t msgs, mqueue::size_t msg_size_bytes)
Create a message queue.
Message_queue (const mqueue::Attributes &attr, mqueue::size_t msgs, mqueue::size_t msg_size_bytes)
Message_queue (const Message_queue &)=delete
Message_queue (Message_queue &&)=delete
Message_queue & operator= (const Message_queue &)=delete
Message_queue & operator= (Message_queue &&)=delete
~Message_queue ()
Delete the message queue.
bool operator== (const Message_queue &rhs) const
Compare memory queues.
result_t send (const char *msg, std::size_t nbytes, mqueue::priority_t mprio)
Send message to the queue.
result_t try_send (const char *msg, std::size_t nbytes, mqueue::priority_t mprio)
Try to send message to the queue.
result_t timed_send (const char *msg, std::size_t nbytes, mqueue::priority_t mprio, systicks_t ticks)
Send message to the queue with timeout.
result_t receive (char *msg, std::size_t nbytes, mqueue::priority_t *mprio)
Receive message from the queue.
result_t try_receive (char *msg, std::size_t nbytes, mqueue::priority_t *mprio)
Try to receive message from the queue.
result_t timed_receive (char *msg, std::size_t nbytes, mqueue::priority_t *mprio, systicks_t ticks)
Receive message from the queue with timeout.
std::size_t capacity (void) const
Get queue capacity.
std::size_t length (void) const
Get queue length.
std::size_t msg_size (void) const
Get message size.
bool empty (void) const
Check if the queue is empty.
bool full (void) const
Check if the queue is full.
result_t reset (void)
Reset the message queue.
const char * name (void) const
Protected Attributes
port::Tasks_list send_list_
port::Tasks_list receive_list_
void * queue_addr_
std::size_t queue_size_bytes_
const mqueue::size_t msgs_
const mqueue::size_t msg_size_bytes_
mqueue::size_t count_
const char *const name_
Detailed Description
POSIX message queue.
Priority based, fixed size FIFO.
Compatible with POSIX message queues. http://pubs.opengroup.org/onlinepubs/9699919799/
Definition at line 2007 of file os.h.
Constructor & Destructor Documentation
os::rtos::Message_queue::Message_queue (mqueue::size_t msgs, mqueue::size_t msg_size_bytes)
Create a message queue.
Parameters
[in] msgs The number of messages.
[in] msg_size_bytes The message size, in bytes.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 52 of file os-mqueue.cpp.
                                                                :
         Message_queue (mqueue::initializer, msgs, msg_size_bytes)
     {
       ;
     }
os::rtos::Message_queue::Message_queue (const mqueue::Attributes & attr, mqueue::size_t msgs, mqueue::size_t msg_size_bytes)
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 63 of file os-mqueue.cpp.
References attr, count_, os::rtos::scheduler::in_handler_mode(), msg_size_bytes_, msgs_, os::rtos::Named_object::name(), os_assert_throw, os::trace::printf(), queue_addr_, and queue_size_bytes_.
                                                                :
         Named_object
           { attr.name () }, //
         msgs_ (msgs), //
         msg_size_bytes_ (msg_size_bytes)
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       queue_addr_ = attr.queue_address;
       queue_size_bytes_ = attr.queue_size_bytes;
       if (queue_addr_ != nullptr)
         {
           os_assert_throw(queue_size_bytes_ > 0, EINVAL);
           os_assert_throw(
               queue_size_bytes_ >= (std::size_t )(msgs * msg_size_bytes),
               EINVAL);
         }
       count_ = 0;
       trace::printf ("%s() @%p %s %d %d\n", __func__, this, name (), msgs_,
                      msg_size_bytes_);
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       port::Message_queue::create (this);
 #else
       if (queue_addr_ == nullptr)
         {
           // TODO: dynamically alloc queue (msgs * msg_size_bytes).
         }
       // TODO
 #endif
     }
os::rtos::Message_queue::Message_queue (const Message_queue &) delete
os::rtos::Message_queue::Message_queue (Message_queue &&) delete
os::rtos::Message_queue::~Message_queue ()
Delete the message queue.
Definition at line 106 of file os-mqueue.cpp.
References os::rtos::Named_object::name(), and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       port::Message_queue::destroy (this);
 #else
       // TODO: Free dynamically allocated structures.
 #endif
     }
Member Function Documentation
std::size_t os::rtos::Message_queue::capacity (void) const inline
Get queue capacity.
Returns
The max number of messages that can be queued.
Definition at line 2962 of file os.h.
     {
       return msgs_;
     }
bool os::rtos::Message_queue::empty (void) const inline
Check if the queue is empty.
Return values
true The queue has no messages.
false The queue has some messages.
Definition at line 2974 of file os.h.
     {
       return (length () == 0);
     }
bool os::rtos::Message_queue::full (void) const inline
Check if the queue is full.
Return values
true The queue is full.
false The queue is not full.
Definition at line 2980 of file os.h.
     {
       return (length () == capacity ());
     }
std::size_t os::rtos::Message_queue::length (void) const inline
Get queue length.
Returns
The number of messages in the queue.
Definition at line 2956 of file os.h.
     {
       return count_;
     }
std::size_t os::rtos::Message_queue::msg_size (void) const inline
Get message size.
Returns
The message size, in bytes.
Definition at line 2968 of file os.h.
     {
       return msg_size_bytes_;
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), receive(), os::rtos::Memory_pool::reset(), reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), timed_receive(), timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), try_receive(), try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), ~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Message_queue& os::rtos::Message_queue::operator= (const Message_queue &) delete
Message_queue& os::rtos::Message_queue::operator= (Message_queue &&) delete
bool os::rtos::Message_queue::operator== (const Message_queue & rhs) const inline
Compare memory queues.
Return values
true The given memory queue is the same as this memory queue.
false The memory queues are different.
Identical message queues should have the same memory address.
Definition at line 2950 of file os.h.
     {
       return this == &rhs;
     }
result_t os::rtos::Message_queue::receive (char * msg, std::size_t nbytes, mqueue::priority_t * mprio)
Receive message from the queue.
Parameters
[out] msg The address where to store the dequeued message.
[in] nbytes The size of the destination buffer. Must be lower than the value used when creating the queue.
[out] mprio The address where to store the message priority. May be nullptr.
Return values
result::ok The message was received.
EINVAL A parameter is invalid or outside of a permitted range.
EMSGSIZE The specified message length, nbytes, is greater than the message size attribute of the message queue.
EPERM Cannot be invoked from an Interrupt Service Routine.
ENOTRECOVERABLE The message could not be dequeued (extension to POSIX).
EBADMSG The implementation has detected a data corruption problem with the message.
EINTR The operation was interrupted.
The receive() function shall receive the oldest of the highest priority message(s) from the message queue. If the size of the buffer in bytes, specified by the nbytes argument, is less than the msg_size_bytes attribute of the message queue, the function shall fail and return an error. Otherwise, the selected message shall be removed from the queue and copied to the buffer pointed to by the msg argument.
If the value of nbytes is greater than {SSIZE_MAX}, the result is implementation-defined.
If the argument mprio is not NULL, the priority of the selected message shall be stored in the location referenced by mprio.
If the message queue is empty, receive() shall block until a message is enqueued on the message queue or until receive() is cancelled/interrupted. If more than one thread is waiting to receive a message when a message arrives at an empty queue and the Priority Scheduling option is supported, then the thread of highest priority that has been waiting the longest shall be selected to receive the message. Otherwise, it is unspecified which waiting thread receives the message.
Compatible with POSIX mq_receive() with O_NONBLOCK not set. http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_receive.html#
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 327 of file os-mqueue.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), msg_size_bytes_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       os_assert_err(msg != nullptr, EINVAL);
       os_assert_err(nbytes >= msg_size_bytes_, EMSGSIZE);
       trace::printf ("%s(%p,%d) @%p %s\n", __func__, msg, nbytes, this,
                      name ());
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::receive (this, msg, nbytes, mprio);
 #else
       // TODO
       --count_;
       return result::ok;
 #endif
     }
result_t os::rtos::Message_queue::reset (void)
Reset the message queue.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Clear both send and receive counter and return the queue to the initial state.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 484 of file os-mqueue.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), and os::driver::usb::device::reset.
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::reset (this);
 #else
       // TODO
       count_ = 0;
       return result::ok;
 #endif
     }
result_t os::rtos::Message_queue::send (const char * msg, std::size_t nbytes, mqueue::priority_t mprio)
Send message to the queue.
Parameters
[in] msg The address of the message to enqueue.
[in] nbytes The length of the message. Must be not higher than the value used when creating the queue.
[in] mprio The message priority.
Return values
result::ok The message was enqueued.
EINVAL A parameter is invalid or outside of a permitted range.
EMSGSIZE The specified message length, nbytes, exceeds the message size attribute of the message queue.
EPERM Cannot be invoked from an Interrupt Service Routine.
ENOTRECOVERABLE The message could not be enqueue (extension to POSIX).
EINTR The operation was interrupted.
The send() function shall add the message pointed to by the argument msg to the message queue. The nbytes argument specifies the length of the message, in bytes, pointed to by msg. The value of nbytes shall be less than or equal to the msg_size_bytes parameter of the message queue object, or send() shall fail.
If the specified message queue is not full, send() shall behave as if the message is inserted into the message queue at the position indicated by the mprio argument. A message with a larger numeric value of mprio shall be inserted before messages with lower values of mprio. A message shall be inserted after other messages in the queue, if any, with equal mprio. The value of mprio shall be less than {MQ_PRIO_MAX}.
If the specified message queue is full, send() shall block until space becomes available to enqueue the message, or until send() is cancelled/interrupted. If more than one thread is waiting to send when space becomes available in the message queue and the Priority Scheduling option is supported, then the thread of the highest priority that has been waiting the longest shall be unblocked to send its message. Otherwise, it is unspecified which waiting thread is unblocked.
Compatible with POSIX mq_send() with O_NONBLOCK not set. http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_timedsend.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 156 of file os-mqueue.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), msg_size_bytes_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       os_assert_err(msg != nullptr, EINVAL);
       os_assert_err(nbytes >= msg_size_bytes_, EINVAL);
       trace::printf ("%s(%p,%d,%d) @%p %s\n", __func__, msg, nbytes, mprio,
                      this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::send (this, msg, nbytes, mprio);
 #else
       // TODO
       ++count_;
       return result::ok;
 #endif
     }
result_t os::rtos::Message_queue::timed_receive (char * msg, std::size_t nbytes, mqueue::priority_t * mprio, systicks_t ticks)
Receive message from the queue with timeout.
Return values
result::ok The message was received.
EINVAL A parameter is invalid or outside of a permitted range.
EMSGSIZE The specified message length, nbytes, is greater than the message size attribute of the message queue.
EPERM Cannot be invoked from an Interrupt Service Routine.
ENOTRECOVERABLE The message could not be dequeued (extension to POSIX).
EBADMSG The implementation has detected a data corruption problem with the message.
EINTR The operation was interrupted.
ETIMEDOUT No message arrived on the queue before the specified timeout expired.
The receive() function shall receive the oldest of the highest priority message(s) from the message queue. If the size of the buffer in bytes, specified by the nbytes argument, is less than the msg_size_bytes attribute of the message queue, the function shall fail and return an error. Otherwise, the selected message shall be removed from the queue and copied to the buffer pointed to by the msg argument.
If the value of nbytes is greater than {SSIZE_MAX}, the result is implementation-defined.
If the argument mprio is not NULL, the priority of the selected message shall be stored in the location referenced by mprio.
If the message queue is empty, receive() shall block until a message is enqueued on the message queue or until receive() is cancelled/interrupted. If more than one thread is waiting to receive a message when a message arrives at an empty queue and the Priority Scheduling option is supported, then the thread of highest priority that has been waiting the longest shall be selected to receive the message. Otherwise, it is unspecified which waiting thread receives the message.
The timed_receive() function shall receive the oldest of the highest priority messages from the message queue as described for the receive() function. However, if no message exists on the queue to satisfy the receive, the wait for such a message shall be terminated when the specified timeout expires.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Under no circumstance shall the operation fail with a timeout if a message can be removed from the message queue immediately. The validity of the abstime parameter need not be checked if a message can be removed from the message queue immediately.
Compatible with POSIX mq_receive() with O_NONBLOCK set. http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_receive.html#
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 445 of file os-mqueue.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), msg_size_bytes_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       os_assert_err(msg != nullptr, EINVAL);
       os_assert_err(nbytes >= msg_size_bytes_, EMSGSIZE);
       trace::printf ("%s(%p,%d,%d_ticks) @%p %s\n", __func__, msg, nbytes,
                      ticks, this, name ());
       if (ticks == 0)
         {
           ticks = 1;
         }
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::timed_receive (this, msg, nbytes, mprio,
                                                  ticks);
 #else
       // TODO
       --count_;
       return result::ok;
 #endif
     }
result_t os::rtos::Message_queue::timed_send (const char * msg, std::size_t nbytes, mqueue::priority_t mprio, systicks_t ticks)
Send message to the queue with timeout.
Parameters
[in] msg The address of the message to enqueue.
[in] nbytes The length of the message. Must be not higher than the value used when creating the queue.
[in] mprio The message priority.
[in] ticks The timeout duration, in SysTick ticks.
Return values
result::ok The message was enqueued.
EINVAL A parameter is invalid or outside of a permitted range.
EMSGSIZE The specified message length, nbytes, exceeds the message size attribute of the message queue.
EPERM Cannot be invoked from an Interrupt Service Routine.
ETIMEDOUT The timeout expired before the message could be added to the queue.
ENOTRECOVERABLE The message could not be enqueue (extension to POSIX).
EINTR The operation was interrupted.
The send() function shall add the message pointed to by the argument msg to the message queue. The nbytes argument specifies the length of the message, in bytes, pointed to by msg. The value of nbytes shall be less than or equal to the msg_size_bytes attribute of the message queue object, or send() shall fail.
If the message queue is not full, send() shall behave as if the message is inserted into the message queue at the position indicated by the mprio argument. A message with a larger numeric value of mprio shall be inserted before messages with lower values of mprio. A message shall be inserted after other messages in the queue, if any, with equal mprio. The value of mprio shall be less than {MQ_PRIO_MAX}.
If the message queue is full, the wait for sufficient room in the queue shall be terminated when the specified timeout expires.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Under no circumstance shall the operation fail with a timeout if there is sufficient room in the queue to add the message immediately.
Compatible with POSIX mq_timedsend(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_timedsend.html
Differences from the standard:
the timeout is not expressed as an absolute time point, but as a relative number of system ticks.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 267 of file os-mqueue.cpp.
References count_, os::rtos::scheduler::in_handler_mode(), msg_size_bytes_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       os_assert_err(msg != nullptr, EINVAL);
       os_assert_err(nbytes >= msg_size_bytes_, EINVAL);
       trace::printf ("%s(%p,%d,%d,%d_ticks) @%p %s\n", __func__, msg, nbytes,
                      mprio, ticks, this, name ());
       if (ticks == 0)
         {
           ticks = 1;
         }
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::timed_send (this, msg, nbytes, mprio, ticks);
 #else
       // TODO
       ++count_;
       return result::ok;
 #endif
     }
result_t os::rtos::Message_queue::try_receive (char * msg, std::size_t nbytes, mqueue::priority_t * mprio)
Try to receive message from the queue.
Parameters
[out] msg The address where to store the dequeued message.
[in] nbytes The size of the destination buffer. Must be lower than the value used when creating the queue.
[out] mprio The address where to store the message priority. May be nullptr.
Return values
result::ok The message was received.
EINVAL A parameter is invalid or outside of a permitted range.
EMSGSIZE The specified message length, nbytes, is greater than the message size attribute of the message queue.
ENOTRECOVERABLE The message could not be dequeued (extension to POSIX).
EBADMSG The implementation has detected a data corruption problem with the message.
EAGAIN The specified message queue is empty.
The receive() function shall receive the oldest of the highest priority message(s) from the message queue. If the size of the buffer in bytes, specified by the nbytes argument, is less than the msg_size_bytes attribute of the message queue, the function shall fail and return an error. Otherwise, the selected message shall be removed from the queue and copied to the buffer pointed to by the msg argument.
If the value of nbytes is greater than {SSIZE_MAX}, the result is implementation-defined.
If the argument mprio is not NULL, the priority of the selected message shall be stored in the location referenced by mprio.
If the message queue is empty, no message shall be removed from the queue, and receive() shall return an error.
Compatible with POSIX mq_receive() with O_NONBLOCK set. http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_receive.html#
Note
Can be invoked from Interrupt Service Routines.
Definition at line 376 of file os-mqueue.cpp.
References count_, msg_size_bytes_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(msg != nullptr, EINVAL);
       os_assert_err(nbytes >= msg_size_bytes_, EMSGSIZE);
       trace::printf ("%s(%p,%d) @%p %s\n", __func__, msg, nbytes, this,
                      name ());
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::try_receive (this, msg, nbytes, mprio);
 #else
       // TODO
       --count_;
       return result::ok;
 #endif
     }
result_t os::rtos::Message_queue::try_send (const char * msg, std::size_t nbytes, mqueue::priority_t mprio)
Try to send message to the queue.
Parameters
[in] msg The address of the message to enqueue.
[in] nbytes The length of the message. Must be not higher than the value used when creating the queue.
[in] mprio The message priority.
Return values
result::ok The message was enqueued.
EAGAIN The specified message queue is full.
EINVAL A parameter is invalid or outside of a permitted range.
EMSGSIZE The specified message length, nbytes, exceeds the message size attribute of the message queue.
ENOTRECOVERABLE The message could not be enqueue (extension to POSIX).
The send() function shall add the message pointed to by the argument msg to the message queue. The nbytes argument specifies the length of the message, in bytes, pointed to by msg. The value of nbytes shall be less than or equal to the msg_size_bytes parameter of the message queue object, or send() shall fail.
If the message queue is not full, send() shall behave as if the message is inserted into the message queue at the position indicated by the mprio argument. A message with a larger numeric value of mprio shall be inserted before messages with lower values of mprio. A message shall be inserted after other messages in the queue, if any, with equal mprio. The value of mprio shall be less than {MQ_PRIO_MAX}.
If the message queue is full, the message shall not be queued and try_send() shall return an error.
Compatible with POSIX mq_send() with O_NONBLOCK set. http://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_timedsend.html
Note
Can be invoked from Interrupt Service Routines.
Definition at line 205 of file os-mqueue.cpp.
References count_, msg_size_bytes_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(msg != nullptr, EINVAL);
       os_assert_err(nbytes >= msg_size_bytes_, EINVAL);
       trace::printf ("%s(%p,%d,%d) @%p %s\n", __func__, msg, nbytes, mprio,
                      this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_MESSAGE_QUEUE)
       return port::Message_queue::try_send (this, msg, nbytes, mprio);
 #else
       // TODO
       ++count_;
       return result::ok;
 #endif
     }
Member Data Documentation
mqueue::size_t os::rtos::Message_queue::count_ protected
Definition at line 2223 of file os.h.
Referenced by Message_queue(), receive(), reset(), send(), timed_receive(), timed_send(), try_receive(), and try_send().
const mqueue::size_t os::rtos::Message_queue::msg_size_bytes_ protected
Definition at line 2221 of file os.h.
Referenced by Message_queue(), receive(), send(), timed_receive(), timed_send(), try_receive(), and try_send().
const mqueue::size_t os::rtos::Message_queue::msgs_ protected
Definition at line 2220 of file os.h.
Referenced by Message_queue().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
void* os::rtos::Message_queue::queue_addr_ protected
Definition at line 2211 of file os.h.
Referenced by Message_queue().
std::size_t os::rtos::Message_queue::queue_size_bytes_ protected
Definition at line 2218 of file os.h.
Referenced by Message_queue().
port::Tasks_list os::rtos::Message_queue::receive_list_ protected
Definition at line 2207 of file os.h.
port::Tasks_list os::rtos::Message_queue::send_list_ protected
Definition at line 2206 of file os.h.
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-mqueue.cpp