CMSIS++ Reference: os::rtos::mutex::Attributes Class Reference
os::rtos::mutex::Attributes Class Reference
Mutex attributes.
#include <os.h>
Inherits os::rtos::Named_object.
Inherited by os::rtos::mutex::Recursive_attributes.
Public Member Functions
Attributes (const char *name)
Attributes (const Attributes &)=default
Attributes (Attributes &&)=default
Attributes & operator= (const Attributes &)=default
Attributes & operator= (Attributes &&)=default
~Attributes ()=default
Delete a mutex attributes.
const char * name (void) const
Public Attributes
thread::priority_t mx_priority_ceiling
mutex::protocol_t mx_protocol
mutex::robustness_t mx_robustness
mutex::type_t mx_type
Protected Attributes
const char *const name_
Detailed Description
Mutex attributes.
Definition at line 1168 of file os.h.
Constructor & Destructor Documentation
os::rtos::mutex::Attributes::Attributes (const char * name) inline
Definition at line 2749 of file os.h.
References os::rtos::thread::priority::highest, mx_priority_ceiling, mx_protocol, mx_robustness, mx_type, os::rtos::thread::priority::none, and os::rtos::thread::priority::normal.
                                               :
           Named_object (name)
       {
         mx_priority_ceiling = thread::priority::highest;
         mx_protocol = protocol::none;
         mx_robustness = robustness::stalled;
         mx_type = type::normal;
       }
os::rtos::mutex::Attributes::Attributes (const Attributes &) default
os::rtos::mutex::Attributes::Attributes (Attributes &&) default
os::rtos::mutex::Attributes::~Attributes () default
Delete a mutex attributes.
Member Function Documentation
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Attributes& os::rtos::mutex::Attributes::operator= (const Attributes &) default
Attributes& os::rtos::mutex::Attributes::operator= (Attributes &&) default
Member Data Documentation
thread::priority_t os::rtos::mutex::Attributes::mx_priority_ceiling
Definition at line 1190 of file os.h.
Referenced by Attributes().
mutex::protocol_t os::rtos::mutex::Attributes::mx_protocol
Definition at line 1191 of file os.h.
Referenced by Attributes().
mutex::robustness_t os::rtos::mutex::Attributes::mx_robustness
Definition at line 1192 of file os.h.
Referenced by Attributes().
mutex::type_t os::rtos::mutex::Attributes::mx_type
Definition at line 1193 of file os.h.
Referenced by Attributes(), and os::rtos::mutex::Recursive_attributes::Recursive_attributes().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
The documentation for this class was generated from the following file:
include/cmsis-plus/rtos/os.h