CMSIS++ Reference: os::rtos::Event_flags Class Reference
os::rtos::Event_flags Class Reference
Event flags.
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Event_flags (void)
Event_flags (const evflags::Attributes &attr)
Event_flags (const Event_flags &)=delete
Event_flags (Event_flags &&)=delete
Event_flags & operator= (const Event_flags &)=delete
Event_flags & operator= (Event_flags &&)=delete
~Event_flags ()
Delete the event flags.
bool operator== (const Event_flags &rhs) const
Compare event flags.
result_t wait (flags::mask_t mask, flags::mask_t *oflags, flags::mode_t mode)
Wait for event flags.
result_t try_wait (flags::mask_t mask, flags::mask_t *oflags, flags::mode_t mode)
Try to wait for event flags.
result_t timed_wait (flags::mask_t mask, flags::mask_t *oflags, flags::mode_t mode, systicks_t ticks)
Timed wait for signal flags.
result_t raise (flags::mask_t mask, flags::mask_t *oflags)
Raise event flags.
result_t clear (flags::mask_t mask, flags::mask_t *oflags)
Clear event flags.
flags::mask_t get (flags::mask_t mask, flags::mode_t mode)
Get/clear event flags.
bool waiting (void)
Check if some thread is waiting.
const char * name (void) const
Protected Member Functions
result_t _try_wait (flags::mask_t mask, flags::mask_t *oflags, flags::mode_t mode)
Protected Attributes
port::Tasks_list list_
flags::mask_t flags_
const char *const name_
Detailed Description
Event flags.
Synchronised set of flags that can be used to notify events between threads or between ISRs and threads.
No POSIX similar functionality identified.
Definition at line 2278 of file os.h.
Constructor & Destructor Documentation
os::rtos::Event_flags::Event_flags (void)
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 56 of file os-evflags.cpp.
References os::rtos::evflags::initializer.
                               :
         Event_flags
           { evflags::initializer }
     {
       ;
     }
os::rtos::Event_flags::Event_flags (const evflags::Attributes & attr)
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 68 of file os-evflags.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_throw, and os::trace::printf().
                                                            :
         Named_object
           { attr.name () }
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       port::Event_flags::create (this);
 #else
       ;
 #endif
     }
os::rtos::Event_flags::Event_flags (const Event_flags &) delete
os::rtos::Event_flags::Event_flags (Event_flags &&) delete
os::rtos::Event_flags::~Event_flags ()
Delete the event flags.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 93 of file os-evflags.cpp.
References os::trace::printf().
     {
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       port::Event_flags::destroy (this);
 #else
       ;
 #endif
     }
Member Function Documentation
result_t os::rtos::Event_flags::_try_wait (flags::mask_t mask, flags::mask_t * oflags, flags::mode_t mode) protected
Definition at line 109 of file os-evflags.cpp.
References os::rtos::flags::mode::all, os::rtos::flags::mode::any, flags_, and os::rtos::result::ok.
Referenced by timed_wait(), try_wait(), and wait().
     {
       if ((mask != 0) && ((mode & flags::mode::all) != 0))
         {
           // Only if all desires signals are raised we're done.
           if ((flags_ & mask) == mask)
             {
               if (oflags != nullptr)
                 {
                   *oflags = flags_;
                 }
               // Clear desired signals.
               flags_ &= ~mask;
               return result::ok;
             }
         }
       else if ((mask == 0) || ((mode & flags::mode::any) != 0))
         {
           // Any flag will do it.
           if (flags_ != 0)
             {
               // Possibly return.
               if (oflags != nullptr)
                 {
                   *oflags = flags_;
                 }
               // Since we returned them all, also clear them all.
               flags_ = 0;
               return result::ok;
             }
         }
       return EAGAIN;
     }
result_t os::rtos::Event_flags::clear (flags::mask_t mask, flags::mask_t * oflags)
Clear event flags.
Parameters
[in] mask The OR-ed flags to clear.
[out] oflags Optional pointer where to store the previous value of the flags; may be nullptr.
Return values
result::ok The flags were cleared.
EINVAL The mask is zero.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 355 of file os-evflags.cpp.
References os::rtos::flags::mode::clear, flags_, os::rtos::result::ok, and os_assert_err.
     {
       os_assert_err(mask != 0, EINVAL);
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::clear (this, mask, oflags);
 #else
       interrupts::Critical_section cs; // ----- Critical section -----
       if (oflags != nullptr)
         {
           *oflags = flags_;
         }
       // Clear the selected bits; leave the rest untouched.
       flags_ &= ~mask;
       return result::ok;
 #endif
     }
flags::mask_t os::rtos::Event_flags::get (flags::mask_t mask, flags::mode_t mode)
Get/clear event flags.
Parameters
[in] mask The OR-ed flags to get/clear; may be zero.
[in] mode Mode bits to select if the flags should be cleared (the other bits are ignored).
Return values
flags The selected bits from the flags mask.
Select the requested bits from the event flags and return them. If requested, clear the selected bits in the event flags.
If the mask is zero, return the status of all event flags, without any masking or subsequent clearing.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 392 of file os-evflags.cpp.
References os::rtos::flags::mode::clear, flags_, and os::trace::ret.
     {
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::get (this, mask, mode);
 #else
       interrupts::Critical_section cs; // ----- Critical section -----
       if (mask == 0)
         {
           // Return the entire mask.
           return flags_;
         }
       flags::mask_t ret = flags_ & mask;
       if ((mode & flags::mode::clear) != 0)
         {
           // Clear the selected bits; leave the rest untouched.
           flags_ &= ~mask;
         }
       // Return the selected bits.
       return ret;
 #endif
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Event_flags& os::rtos::Event_flags::operator= (const Event_flags &) delete
Event_flags& os::rtos::Event_flags::operator= (Event_flags &&) delete
bool os::rtos::Event_flags::operator== (const Event_flags & rhs) const
Compare event flags.
Return values
true The given event flags object is the same as this event flags.
false The event flags are different.
result_t os::rtos::Event_flags::raise (flags::mask_t mask, flags::mask_t * oflags)
Raise event flags.
Parameters
[in] mask The OR-ed flags to raise.
[out] oflags Optional pointer where to store the new value of the flags; may be nullptr.
Return values
result::ok The flags were raised.
EINVAL The mask is zero.
ENOTRECOVERABLE Raise failed.
Set more bits in the thread current signal mask. Use OR at bit-mask level. Wake-up all waiting threads, if any.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 319 of file os-evflags.cpp.
References flags_, list_, os::rtos::result::ok, and os_assert_err.
     {
       os_assert_err(mask != 0, EINVAL);
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::raise (this, mask, oflags);
 #else
       interrupts::Critical_section cs; // ----- Critical section -----
       flags_ |= mask;
       if (oflags != nullptr)
         {
           *oflags = flags_;
         }
       if (!list_.empty ())
         {
           // Wake-up all threads, if any.
           list_.wakeup_all ();
         }
       return result::ok;
 #endif
     }
result_t os::rtos::Event_flags::timed_wait (flags::mask_t mask, flags::mask_t * oflags, flags::mode_t mode, systicks_t ticks)
Timed wait for signal flags.
Parameters
[in] mask The expected flags (OR-ed bit-mask); may be zero.
[out] oflags Pointer where to store the current flags; may be nullptr.
[in] mode Mode bits to select if either all or any flags are expected, and if the flags should be cleared.
[in] ticks Ticks to wait.
Return values
result::ok All expected flags are raised.
EPERM Cannot be invoked from an Interrupt Service Routine.
ETIMEDOUT The expected condition did not occur during the entire timeout duration.
EINVAL The mask is outside of the permitted range.
EINTR The operation was interrupted.
ENOTRECOVERABLE Wait failed.
If the mode::all bit is set, the function expects all given flags to be raised; otherwise, if the mode::any bit is set, the function expects any single flag to be raised.
If the expected event flags are raised, the function returns instantly.
Otherwise suspend the execution of the current thread until all/any specified event flags are raised.
When the parameter mask is 0, the current thread is suspended until any event flag is raised. In this case, if any event flags are already raised, the function returns instantly.
The wait shall be terminated when the specified timeout expires.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Under no circumstance shall the operation fail with a timeout if the event flags are already raised.
If the mode::clear bit is set, the event flags that are returned are automatically cleared.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 262 of file os-evflags.cpp.
References _try_wait(), os::rtos::scheduler::in_handler_mode(), os::rtos::Systick_clock::now(), os::rtos::result::ok, os_assert_throw, os::rtos::scheduler::start(), os::rtos::this_thread::thread(), and os::rtos::Systick_clock::wait().
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       if (ticks == 0)
         {
           ticks = 1;
         }
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::timed_wait (this, mask, oflags, mode, ticks);
 #else
       Systick_clock::rep start = Systick_clock::now ();
       for (;;)
         {
           Systick_clock::sleep_rep slept_ticks;
             {
               interrupts::Critical_section cs; // ----- Critical section -----
               if (_try_wait (mask, oflags, mode) == result::ok)
                 {
                   return result::ok;
                 }
             }
           Systick_clock::rep now = Systick_clock::now ();
           slept_ticks = (Systick_clock::sleep_rep) (now - start);
           if (slept_ticks >= ticks)
             {
               return ETIMEDOUT;
             }
           Systick_clock::wait (ticks - slept_ticks);
           if (this_thread::thread ().interrupted ())
             {
               return EINTR;
             }
         }
       return ENOTRECOVERABLE;
 #endif
     }
result_t os::rtos::Event_flags::try_wait (flags::mask_t mask, flags::mask_t * oflags, flags::mode_t mode)
Try to wait for event flags.
Parameters
[in] mask The expected flags (OR-ed bit-mask); may be zero.
[out] oflags Pointer where to store the current flags; may be nullptr.
[in] mode Mode bits to select if either all or any flags are expected, and if the flags should be cleared.
Return values
result::ok All expected flags are raised.
EINVAL The mask is outside of the permitted range.
EAGAIN The expected condition did not occur.
ENOTRECOVERABLE Wait failed.
If the mode::all bit is set, the function expects all given flags to be raised; otherwise, if the mode::any bit is set, the function expects any single flag to be raised.
The function does not blocks, if the expected event flags are not raised, but returns EGAIN.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 213 of file os-evflags.cpp.
References _try_wait().
     {
       interrupts::Critical_section cs; // ----- Critical section -----
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::try_wait (this, mask, oflags, mode);
 #else
       return _try_wait (mask, oflags, mode);
 #endif
     }
result_t os::rtos::Event_flags::wait (flags::mask_t mask, flags::mask_t * oflags, flags::mode_t mode)
Wait for event flags.
Parameters
[in] mask The expected flags (OR-ed bit-mask); may be zero.
[out] oflags Pointer where to store the current flags; may be nullptr.
[in] mode Mode bits to select if either all or any flags are expected, and if the flags should be cleared.
Return values
result::ok All expected flags are raised.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINVAL The mask is outside of the permitted range.
EINTR The operation was interrupted.
ENOTRECOVERABLE Wait failed.
If the mode::all bit is set, the function expects all given flags to be raised; otherwise, if the mode::any bit is set, the function expects any single flag to be raised.
If the expected event flags are raised, the function returns instantly.
Otherwise suspend the execution of the current thread until all/any specified event flags are raised.
When the parameter mask is 0, the current thread is suspended until any event flag is raised. In this case, if any event flags are already raised, the function returns instantly.
If the mode::clear bit is set, the event flags that are returned are automatically cleared.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 167 of file os-evflags.cpp.
References _try_wait(), os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_throw, os::rtos::this_thread::suspend(), and os::rtos::this_thread::thread().
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::wait (this, mask, oflags, mode);
 #else
       for (;;)
         {
             {
               interrupts::Critical_section cs; // ----- Critical section -----
               if (_try_wait (mask, oflags, mode) == result::ok)
                 {
                   return result::ok;
                 }
             }
           this_thread::suspend ();
           if (this_thread::thread ().interrupted ())
             {
               return EINTR;
             }
         }
       return ENOTRECOVERABLE;
 #endif
     }
bool os::rtos::Event_flags::waiting (void)
Check if some thread is waiting.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 427 of file os-evflags.cpp.
References list_.
     {
 #if defined(OS_INCLUDE_PORT_RTOS_EVENT_FLAGS)
       return port::Event_flags::waiting (this);
 #else
       return !list_.empty ();
 #endif
     }
Member Data Documentation
flags::mask_t os::rtos::Event_flags::flags_ protected
Definition at line 2418 of file os.h.
Referenced by _try_wait(), clear(), get(), and raise().
port::Tasks_list os::rtos::Event_flags::list_ protected
Definition at line 2410 of file os.h.
Referenced by raise(), and waiting().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-evflags.cpp