CMSIS++ Reference: os::rtos::Memory_pool Class Reference
os::rtos::Memory_pool Class Reference
Synchronised memory pool.
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Memory_pool (mempool::size_t blocks, mempool::size_t block_size_bytes)
Create a memory pool with default attributes.
Memory_pool (const mempool::Attributes &attr, mempool::size_t blocks, mempool::size_t block_size_bytes)
Create a memory pool with custom attributes.
Memory_pool (const Memory_pool &)=delete
Memory_pool (Memory_pool &&)=delete
Memory_pool & operator= (const Memory_pool &)=delete
Memory_pool & operator= (Memory_pool &&)=delete
~Memory_pool ()
Delete the memory pool.
bool operator== (const Memory_pool &rhs) const
Compare memory pools.
void * alloc (void)
Allocate a memory block.
void * try_alloc (void)
Allocate a memory block.
void * timed_alloc (systicks_t ticks)
Allocate a memory block.
result_t free (void *block)
Free the memory block.
std::size_t capacity (void) const
Get memory pool capacity.
std::size_t count (void) const
Get blocks count.
std::size_t block_size (void) const
Get block size.
bool empty (void) const
Check if the memory pool is empty.
bool full (void) const
Check if the memory pool is full.
result_t reset (void)
Reset the memory pool.
void * pool (void)
const char * name (void) const
Protected Types
enum : uint8_t { flags_allocated = 1 }
Protected Member Functions
void * _try_first (void)
Protected Attributes
port::Tasks_list list_
char * pool_addr_
const mempool::size_t blocks_
const mempool::size_t block_size_bytes_
volatile mempool::size_t count_
void *volatile first_
uint8_t flags_
const char *const name_
Detailed Description
Synchronised memory pool.
Manage a pool of same size blocks. Fast and deterministic allocation and dealocation behaviour, suitable for use even in ISRs.
No POSIX similar functionality identified.
Note
There is no equivalent of calloc(); to initialise memory, use: memset (block, 0, pool.block_size ());
Definition at line 1798 of file os.h.
Member Enumeration Documentation
anonymous enum : uint8_t protected
Enumerator
flags_allocated
Definition at line 1943 of file os.h.
         : uint8_t
           {
             flags_allocated = 1
       };
Constructor & Destructor Documentation
os::rtos::Memory_pool::Memory_pool (mempool::size_t blocks, mempool::size_t block_size_bytes)
Create a memory pool with default attributes.
Parameters
[in] blocks The maximum number of items in the pool.
[in] block_size_bytes The size of an item, in bytes.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 54 of file os-mempool.cpp.
References os::rtos::mempool::initializer.
                                                               :
         Memory_pool
           { mempool::initializer, blocks, block_size_bytes }
     {
       ;
     }
os::rtos::Memory_pool::Memory_pool (const mempool::Attributes & attr, mempool::size_t blocks, mempool::size_t block_size_bytes)
Create a memory pool with custom attributes.
Parameters
[in] attr Reference to attributes object.
[in] blocks The maximum number of items in the pool.
[in] block_size_bytes The size of an item, in bytes.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 66 of file os-mempool.cpp.
References attr, block_size_bytes_, blocks_, count_, first_, flags_, flags_allocated, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_throw, pool_addr_, and os::trace::printf().
                                                               :
         Named_object
           { attr.name () }, //
         blocks_ (blocks), //
         block_size_bytes_ (block_size_bytes)
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       pool_addr_ = (char*) attr.mp_pool_address;
       assert(blocks_ > 0);
       // Blocks must be large enough to store the index, used
       // to construct the list of free blocks.
       assert(block_size_bytes_ >= sizeof(std::ptrdiff_t));
       flags_ = 0;
       trace::printf ("%s() @%p %s %d %d\n", __func__, this, name (), blocks_,
                      block_size_bytes_);
       if (pool_addr_ == nullptr)
         {
           pool_addr_ = new (std::nothrow) char[blocks_ * block_size_bytes_];
           flags_ |= flags_allocated;
         }
       os_assert_throw(pool_addr_ != nullptr, ENOMEM);
       // Construct a linked list of blocks. Store the pointer at
       // the beginning of each block. Each block
       // will hold the address of the next free block, or nullptr at the end.
       char* p = pool_addr_;
       for (std::size_t i = 1; i < blocks_; ++i)
         {
           *(void**) p = (p + block_size_bytes_);
           p += block_size_bytes_;
         }
       *(void**) p = nullptr;
       first_ = pool_addr_; // Pointer to first block.
       count_ = 0; // No allocated blocks.
     }
os::rtos::Memory_pool::Memory_pool (const Memory_pool &) delete
os::rtos::Memory_pool::Memory_pool (Memory_pool &&) delete
os::rtos::Memory_pool::~Memory_pool ()
Delete the memory pool.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 116 of file os-mempool.cpp.
References flags_, flags_allocated, os::rtos::Named_object::name(), pool_addr_, and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       if (flags_ | flags_allocated)
         {
           delete[] (pool_addr_);
         }
     }
Member Function Documentation
void * os::rtos::Memory_pool::_try_first (void) protected
Definition at line 131 of file os-mempool.cpp.
References count_, and first_.
Referenced by alloc(), timed_alloc(), and try_alloc().
     {
       if (first_ != nullptr)
         {
           void* p = (void*) first_;
           first_ = *(void**) first_;
           ++count_;
           return p;
         }
       return nullptr;
     }
void * os::rtos::Memory_pool::alloc (void)
Allocate a memory block.
Returns
Pointer to memory block.
Allocate a fixed size memory block from the memory pool.
It uses a critical section to protect simultaneous access from other threads or interrupts.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 153 of file os-mempool.cpp.
References _try_first(), os::rtos::scheduler::in_handler_mode(), list_, os::rtos::Named_object::name(), os_assert_throw, os::trace::printf(), os::rtos::this_thread::suspend(), and os::rtos::this_thread::thread().
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       bool queued = false;
       for (;;)
         {
             {
               interrupts::Critical_section cs; // ----- Critical section -----
               void* p = _try_first ();
               if (p != nullptr)
                 {
                   return p;
                 }
               if (!queued)
                 {
                   // Add this thread to the waiting list.
                   // Will be removed by free().
                   list_.add (&this_thread::thread ());
                   queued = true;
                 }
             }
           this_thread::suspend ();
           if (this_thread::thread ().interrupted ())
             {
               return nullptr;
             }
         }
       /* NOTREACHED */
       return nullptr;
     }
std::size_t os::rtos::Memory_pool::block_size (void) const inline
Get block size.
Returns
The block size, in bytes.
Definition at line 2900 of file os.h.
Referenced by osMutexDelete().
     {
       return block_size_bytes_;
     }
std::size_t os::rtos::Memory_pool::capacity (void) const inline
Get memory pool capacity.
Returns
The max number of blocks in the pool.
Definition at line 2894 of file os.h.
Referenced by osMutexDelete().
     {
       return blocks_;
     }
std::size_t os::rtos::Memory_pool::count (void) const inline
Get blocks count.
Returns
The number of blocks used from the queue.
Definition at line 2906 of file os.h.
     {
       return count_;
     }
bool os::rtos::Memory_pool::empty (void) const inline
Check if the memory pool is empty.
Return values
true The memory pool has no allocated blocks.
false The memory pool has allocated blocks.
Definition at line 2912 of file os.h.
     {
       return (count () == 0);
     }
result_t os::rtos::Memory_pool::free (void * block)
Free the memory block.
Return values
result::ok The memory block was released.
EINVAL The block does not belong to the memory pool.
Return a memory block previously allocated by alloc() or calloc() back to the memory pool.
It uses a critical section to protect simultaneous access from other threads or interrupts.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 287 of file os-mempool.cpp.
References block_size_bytes_, blocks_, count_, first_, list_, os::rtos::Named_object::name(), os::rtos::result::ok, pool_addr_, and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       // Validate pointer.
       if ((block < pool_addr_)
           || (block >= (pool_addr_ + blocks_ * block_size_bytes_)))
         {
           return EINVAL;
         }
       interrupts::Critical_section cs; // ----- Critical section -----
       // Perform a push_front() on the single linked LIFO list,
       // i.e. add the block to the beginning of the list.
       // Link previous list to this block; may be null, but it does
       // not matter.
       *(void**) block = first_;
       // Now this block is the first one.
       first_ = block;
       --count_;
       if (!list_.empty ())
         {
           // Wake-up one thread, if any.
           list_.wakeup_one ();
         }
       return result::ok;
     }
bool os::rtos::Memory_pool::full (void) const inline
Check if the memory pool is full.
Return values
true All memory blocks are allocated.
false There are still memory blocks that can be allocated.
Definition at line 2918 of file os.h.
     {
       return (count () == capacity ());
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), ~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Memory_pool& os::rtos::Memory_pool::operator= (const Memory_pool &) delete
Memory_pool& os::rtos::Memory_pool::operator= (Memory_pool &&) delete
bool os::rtos::Memory_pool::operator== (const Memory_pool & rhs) const inline
Compare memory pools.
Return values
true The given memory pool is the same as this memory pool.
false The memory pools are different.
Identical memory pools should have the same memory address.
Definition at line 2888 of file os.h.
     {
       return this == &rhs;
     }
void * os::rtos::Memory_pool::pool (void) inline
Definition at line 2924 of file os.h.
Referenced by osMutexDelete().
     {
       return pool_addr_;
     }
result_t os::rtos::Memory_pool::reset (void)
Reset the memory pool.
Return values
result::ok The memory pool was reset.
EPERM Cannot be invoked from an Interrupt Service Routine.
Reset the memory pool to initial state, all block are free.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 328 of file os-mempool.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       // TODO
       return result::ok;
     }
void * os::rtos::Memory_pool::timed_alloc (systicks_t ticks)
Allocate a memory block.
Returns
Pointer to memory block, or nullptr if timeout.
Allocate a fixed size memory block from the memory pool.
It uses a critical section to protect simultaneous access from other threads or interrupts.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 218 of file os-mempool.cpp.
References _try_first(), os::rtos::scheduler::in_handler_mode(), list_, os::rtos::Named_object::name(), os::rtos::Systick_clock::now(), os_assert_throw, os::trace::printf(), os::rtos::scheduler::start(), os::rtos::this_thread::thread(), and os::rtos::Systick_clock::wait().
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d) @%p %s\n", __func__, ticks, this, name ());
       bool queued = false;
       if (ticks == 0)
         {
           ticks = 1;
         }
       Systick_clock::rep start = Systick_clock::now ();
       for (;;)
         {
           Systick_clock::sleep_rep slept_ticks;
             {
               interrupts::Critical_section cs; // ----- Critical section -----
               void* p = _try_first ();
               if (p != nullptr)
                 {
                   return p;
                 }
               Systick_clock::rep now = Systick_clock::now ();
               slept_ticks = (Systick_clock::sleep_rep) (now - start);
               if (slept_ticks >= ticks)
                 {
                   if (queued)
                     {
                       list_.remove (&this_thread::thread ());
                     }
                   return nullptr;
                 }
               if (!queued)
                 {
                   // Add this thread to the waiting list.
                   // Will be removed by free() or if timeout occurs.
                   list_.add (&this_thread::thread ());
                   queued = true;
                 }
             }
           Systick_clock::wait (ticks - slept_ticks);
           if (this_thread::thread ().interrupted ())
             {
               return nullptr;
             }
         }
       /* NOTREACHED */
       return nullptr;
     }
void * os::rtos::Memory_pool::try_alloc (void)
Allocate a memory block.
Returns
Pointer to memory block, or nullptr if no memory available.
Allocate a fixed size memory block from the memory pool.
It uses a critical section to protect simultaneous access from other threads or interrupts.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 201 of file os-mempool.cpp.
References _try_first(), os::rtos::Named_object::name(), and os::trace::printf().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       return _try_first ();
     }
Member Data Documentation
const mempool::size_t os::rtos::Memory_pool::block_size_bytes_ protected
Definition at line 1933 of file os.h.
Referenced by free(), and Memory_pool().
const mempool::size_t os::rtos::Memory_pool::blocks_ protected
Definition at line 1932 of file os.h.
Referenced by free(), and Memory_pool().
volatile mempool::size_t os::rtos::Memory_pool::count_ protected
Definition at line 1935 of file os.h.
Referenced by _try_first(), free(), and Memory_pool().
void* volatile os::rtos::Memory_pool::first_ protected
Definition at line 1940 of file os.h.
Referenced by _try_first(), free(), and Memory_pool().
uint8_t os::rtos::Memory_pool::flags_ protected
Definition at line 1942 of file os.h.
Referenced by Memory_pool(), and ~Memory_pool().
port::Tasks_list os::rtos::Memory_pool::list_ protected
Definition at line 1923 of file os.h.
Referenced by alloc(), free(), and timed_alloc().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
char* os::rtos::Memory_pool::pool_addr_ protected
Definition at line 1925 of file os.h.
Referenced by free(), Memory_pool(), and ~Memory_pool().
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-mempool.cpp