CMSIS++ Reference: os::rtos::semaphore::Attributes Class Reference
os::rtos::semaphore::Attributes Class Reference
Semaphore attributes.
#include <os.h>
Inherits os::rtos::Named_object.
Inherited by os::rtos::semaphore::Binary_attributes.
Public Member Functions
Attributes (const char *name)
Attributes (const Attributes &)=default
Attributes (Attributes &&)=default
Attributes & operator= (const Attributes &)=default
Attributes & operator= (Attributes &&)=default
~Attributes ()=default
Delete semaphore attributes.
const char * name (void) const
Public Attributes
count_t sm_initial_count
count_t sm_max_count
Protected Attributes
const char *const name_
Detailed Description
Semaphore attributes.
Definition at line 1536 of file os.h.
Constructor & Destructor Documentation
os::rtos::semaphore::Attributes::Attributes (const char * name) inline
Definition at line 2815 of file os.h.
References os::rtos::semaphore::max_count_value, sm_initial_count, and sm_max_count.
                                               :
           Named_object
             { name }
       {
         sm_initial_count = 0;
         sm_max_count = max_count_value;
       }
os::rtos::semaphore::Attributes::Attributes (const Attributes &) default
os::rtos::semaphore::Attributes::Attributes (Attributes &&) default
os::rtos::semaphore::Attributes::~Attributes () default
Delete semaphore attributes.
Member Function Documentation
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Attributes& os::rtos::semaphore::Attributes::operator= (const Attributes &) default
Attributes& os::rtos::semaphore::Attributes::operator= (Attributes &&) default
Member Data Documentation
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
count_t os::rtos::semaphore::Attributes::sm_initial_count
Definition at line 1558 of file os.h.
Referenced by Attributes(), and os::rtos::semaphore::Binary_attributes::Binary_attributes().
count_t os::rtos::semaphore::Attributes::sm_max_count
Definition at line 1560 of file os.h.
Referenced by Attributes(), and os::rtos::semaphore::Binary_attributes::Binary_attributes().
The documentation for this class was generated from the following file:
include/cmsis-plus/rtos/os.h