CMSIS++ Reference: os::rtos::Timer Class Reference
os::rtos::Timer Class Reference
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Timer (timer::func_t function, timer::func_args_t args)
Timer (const timer::Attributes &attr, timer::func_t function, timer::func_args_t args)
Timer (const Timer &)=delete
Timer (Timer &&)=delete
Timer & operator= (const Timer &)=delete
Timer & operator= (Timer &&)=delete
~Timer ()
bool operator== (const Timer &rhs) const
Compare timers.
result_t start (systicks_t ticks)
Start or restart the timer.
result_t stop (void)
Stop the timer.
const char * name (void) const
Protected Attributes
timer::func_t func_
timer::func_args_t func_args_
timer::type_t type_
const char *const name_
Detailed Description
Definition at line 1070 of file os.h.
Constructor & Destructor Documentation
os::rtos::Timer::Timer (timer::func_t function, timer::func_args_t args)
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 58 of file os-timer.cpp.
References os::rtos::timer::once_initializer.
                                                              :
         Timer
           { timer::once_initializer, function, args }
     {
       ;
     }
os::rtos::Timer::Timer (const timer::Attributes & attr, timer::func_t function, timer::func_args_t args)
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 70 of file os-timer.cpp.
References args, attr, func_, func_args_, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_throw, os::trace::printf(), and type_.
                                          :
         Named_object
           { attr.name () }
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       os_assert_throw(function != nullptr, EINVAL);
       type_ = attr.tm_type;
       func_ = function;
       func_args_ = args;
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_TIMER)
       port::Timer::create (this, function, args);
 #else
       // TODO
 #endif
     }
os::rtos::Timer::Timer (const Timer &) delete
os::rtos::Timer::Timer (Timer &&) delete
os::rtos::Timer::~Timer ()
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 102 of file os-timer.cpp.
References os::trace::printf().
     {
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       port::Timer::destroy (this);
 #else
       // TODO
 #endif
     }
Member Function Documentation
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Timer& os::rtos::Timer::operator= (const Timer &) delete
Timer& os::rtos::Timer::operator= (Timer &&) delete
bool os::rtos::Timer::operator== (const Timer & rhs) const inline
Compare timers.
Return values
true The given timer is the same as this timer.
false The timers are different.
Identical timers should have the same memory address.
Definition at line 2739 of file os.h.
     {
       return this == &rhs;
     }
result_t os::rtos::Timer::start (systicks_t ticks)
Start or restart the timer.
Parameters
[in] ticks The timer period, in ticks.
Return values
result::ok The timer has been started or restarted.
ENOTRECOVERABLE Timer could not be started.
EPERM Cannot be invoked from an Interrupt Service Routine.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 123 of file os-timer.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, os::trace::printf(), and os::rtos::scheduler::start().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d) @%p \n", __func__, ticks, this);
       if (ticks == 0)
         {
           ticks = 1;
         }
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Timer::start (this, ticks);
 #else
       // TODO
       return result::ok;
 #endif
     }
result_t os::rtos::Timer::stop (void)
Stop the timer.
Return values
result::ok The timer has been stopped.
EPERM Cannot be invoked from an Interrupt Service Routine.
EAGAIN The timer is not yet started.
ENOTRECOVERABLE Timer could not be stopped.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 152 of file os-timer.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_SEMAPHORE)
       return port::Timer::stop (this);
 #else
       // TODO
       return result::ok;
 #endif
     }
Member Data Documentation
timer::func_t os::rtos::Timer::func_ protected
Definition at line 1118 of file os.h.
Referenced by Timer().
timer::func_args_t os::rtos::Timer::func_args_ protected
Definition at line 1119 of file os.h.
Referenced by Timer().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
timer::type_t os::rtos::Timer::type_ protected
Definition at line 1126 of file os.h.
Referenced by Timer().
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-timer.cpp