CMSIS++ Reference: os::rtos::thread::Attributes Class Reference
os::rtos::thread::Attributes Class Reference
Thread attributes.
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Attributes (const char *name)
Attributes (const Attributes &)=default
Attributes (Attributes &&)=default
Attributes & operator= (const Attributes &)=default
Attributes & operator= (Attributes &&)=default
~Attributes ()=default
Delete thread attributes.
const char * name (void) const
Public Attributes
void * th_stack_address
std::size_t th_stack_size_bytes
priority_t th_priority
Protected Attributes
const char *const name_
Detailed Description
Thread attributes.
Definition at line 543 of file os.h.
Constructor & Destructor Documentation
os::rtos::thread::Attributes::Attributes (const char * name) inline
Definition at line 2651 of file os.h.
References os::rtos::thread::priority::normal, th_priority, th_stack_address, and th_stack_size_bytes.
                                               :
           Named_object (name)
       {
         th_stack_address = nullptr;
         th_stack_size_bytes = 0;
         th_priority = thread::priority::normal;
       }
os::rtos::thread::Attributes::Attributes (const Attributes &) default
os::rtos::thread::Attributes::Attributes (Attributes &&) default
os::rtos::thread::Attributes::~Attributes () default
Delete thread attributes.
Member Function Documentation
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Attributes& os::rtos::thread::Attributes::operator= (const Attributes &) default
Attributes& os::rtos::thread::Attributes::operator= (Attributes &&) default
Member Data Documentation
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
priority_t os::rtos::thread::Attributes::th_priority
Definition at line 567 of file os.h.
Referenced by Attributes(), and osThreadCreate().
void* os::rtos::thread::Attributes::th_stack_address
Definition at line 565 of file os.h.
Referenced by Attributes(), and osThreadCreate().
std::size_t os::rtos::thread::Attributes::th_stack_size_bytes
Definition at line 566 of file os.h.
Referenced by Attributes(), and osThreadCreate().
The documentation for this class was generated from the following file:
include/cmsis-plus/rtos/os.h