CMSIS++ Reference: os::rtos::timer::Attributes Class Reference
os::rtos::timer::Attributes Class Reference
Timer attributes.
#include <os.h>
Inherits os::rtos::Named_object.
Inherited by os::rtos::timer::Periodic_attributes.
Public Member Functions
Attributes (const char *name)
Attributes (const Attributes &)=default
Attributes (Attributes &&)=default
Attributes & operator= (const Attributes &)=default
Attributes & operator= (Attributes &&)=default
~Attributes ()=default
Delete timer attributes.
const char * name (void) const
Public Attributes
type_t tm_type
Protected Attributes
const char *const name_
Detailed Description
Timer attributes.
Definition at line 1008 of file os.h.
Constructor & Destructor Documentation
os::rtos::timer::Attributes::Attributes (const char * name) inline
Definition at line 2714 of file os.h.
References tm_type.
                                               :
           Named_object
             { name }
       {
         this->tm_type = run::once;
       }
os::rtos::timer::Attributes::Attributes (const Attributes &) default
os::rtos::timer::Attributes::Attributes (Attributes &&) default
os::rtos::timer::Attributes::~Attributes () default
Delete timer attributes.
Member Function Documentation
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Attributes& os::rtos::timer::Attributes::operator= (const Attributes &) default
Attributes& os::rtos::timer::Attributes::operator= (Attributes &&) default
Member Data Documentation
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
type_t os::rtos::timer::Attributes::tm_type
Definition at line 1030 of file os.h.
Referenced by Attributes(), and os::rtos::timer::Periodic_attributes::Periodic_attributes().
The documentation for this class was generated from the following file:
include/cmsis-plus/rtos/os.h