CMSIS++ Reference: os::rtos::interrupts::Critical_section Class Reference
os::rtos::interrupts::Critical_section Class Reference
#include <os.h>
Public Member Functions
Critical_section ()
~Critical_section ()
Critical_section (const Critical_section &)=delete
Critical_section (Critical_section &&)=delete
Critical_section & operator= (const Critical_section &)=delete
Critical_section & operator= (Critical_section &&)=delete
Static Public Member Functions
static status_t enter (void)
Enter interrupts critical section.
static void exit (status_t status)
Exit interrupts critical section.
Protected Attributes
const status_t status_
Detailed Description
Definition at line 250 of file os.h.
Constructor & Destructor Documentation
os::rtos::interrupts::Critical_section::Critical_section () inline
Definition at line 2541 of file os.h.
                                           :
           status_ (enter ())
       {
         ;
       }
os::rtos::interrupts::Critical_section::~Critical_section () inline
Definition at line 2548 of file os.h.
References exit(), and status_.
       {
         exit (status_);
       }
os::rtos::interrupts::Critical_section::Critical_section (const Critical_section &) delete
os::rtos::interrupts::Critical_section::Critical_section (Critical_section &&) delete
Member Function Documentation
status_t os::rtos::interrupts::Critical_section::enter (void) static
Enter interrupts critical section.
Returns
The current interrupts status register.
Definition at line 159 of file os-core.cpp.
Referenced by os::rtos::interrupts::Lock::lock(), os_irq_critical_enter(), and os::rtos::interrupts::Lock::try_lock().
       {
         return port::interrupts::Critical_section::enter ();
       }
void os::rtos::interrupts::Critical_section::exit (status_t status) static
Exit interrupts critical section.
Parameters
status The value to restore the interrupts status register.
Definition at line 166 of file os-core.cpp.
References os::rtos::this_thread::exit().
Referenced by os_irq_critical_exit(), os::rtos::interrupts::Lock::unlock(), and ~Critical_section().
       {
         return port::interrupts::Critical_section::exit (status);
       }
Critical_section& os::rtos::interrupts::Critical_section::operator= (const Critical_section &) delete
Critical_section& os::rtos::interrupts::Critical_section::operator= (Critical_section &&) delete
Member Data Documentation
const status_t os::rtos::interrupts::Critical_section::status_ protected
Definition at line 282 of file os.h.
Referenced by ~Critical_section().
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-core.cpp