CMSIS++ Reference: os::rtos::Mutex Class Reference
os::rtos::Mutex Class Reference
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Mutex ()
Create a mutex with default attributes.
Mutex (const mutex::Attributes &attr)
Create a mutex with custom attributes.
Mutex (const Mutex &)=delete
Mutex (Mutex &&)=delete
Mutex & operator= (const Mutex &)=delete
Mutex & operator= (Mutex &&)=delete
~Mutex ()
Delete a mutex.
bool operator== (const Mutex &rhs) const
Compare mutexes.
result_t lock (void)
Lock the mutex.
result_t try_lock (void)
Try to lock the mutex.
result_t timed_lock (systicks_t ticks)
Timed attempt to lock the mutex.
result_t unlock (void)
Unlock the mutex.
thread::priority_t prio_ceiling (void) const
Get the priority ceiling of a mutex.
result_t prio_ceiling (thread::priority_t prio_ceiling, thread::priority_t *old_prio_ceiling=nullptr)
Change the priority ceiling of a mutex.
result_t consistent (void)
Mark mutex as consistent.
Thread * owner (void)
result_t reset (void)
const char * name (void) const
Protected Attributes
Thread *volatile owner_
volatile mutex::count_t count_
volatile thread::priority_t prio_ceiling_
const mutex::type_t type_
const mutex::protocol_t protocol_
const mutex::robustness_t robustness_
const char *const name_
Detailed Description
Definition at line 1236 of file os.h.
Constructor & Destructor Documentation
os::rtos::Mutex::Mutex ()
Create a mutex with default attributes.
Initialise the mutex with default attributes.
pthread_mutex_init() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 63 of file os-mutex.cpp.
References os::rtos::mutex::normal_initializer.
                   :
         Mutex
           { mutex::normal_initializer }
     {
       ;
     }
os::rtos::Mutex::Mutex (const mutex::Attributes & attr)
Create a mutex with custom attributes.
Initialize the mutex with attributes specified by attr. Upon successful initialization, the state of the mutex becomes initialized and unlocked.
pthread_mutex_init() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 81 of file os-mutex.cpp.
References attr, count_, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_throw, owner_, os::trace::printf(), prio_ceiling_, protocol_, robustness_, and type_.
                                              :
         Named_object
           { attr.name () }, //
         type_ (attr.mx_type), //
         protocol_ (attr.mx_protocol), //
         robustness_ (attr.mx_robustness) //
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       prio_ceiling_ = attr.mx_priority_ceiling;
       owner_ = nullptr;
       count_ = 0;
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       port::Mutex::create (this);
 #else
       // TODO
 #endif
     }
os::rtos::Mutex::Mutex (const Mutex &) delete
os::rtos::Mutex::Mutex (Mutex &&) delete
os::rtos::Mutex::~Mutex ()
Delete a mutex.
Destroy the mutex object. It shall be safe to destroy an initialized mutex that is unlocked. Attempting to destroy a locked mutex or a mutex that is referenced (for example, while being used in a pthread_cond_timedwait() or pthread_cond_wait()) by another thread results in undefined behavior.
pthread_mutex_destroy() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 122 of file os-mutex.cpp.
References os::trace::printf().
     {
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       port::Mutex::destroy (this);
 #else
       // TODO
 #endif
     }
Member Function Documentation
result_t os::rtos::Mutex::consistent (void)
Mark mutex as consistent.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINVAL The mutex object referenced by mutex is not robust or does not protect an inconsistent state.
If the robust mutex is in an inconsistent state, the Mutex::consistent() function can be used to mark the state protected by the mutex referenced by mutex as consistent again.
If an owner of a robust mutex terminates while holding the mutex, the mutex becomes inconsistent and the next thread that acquires the mutex lock shall be notified of the state by the return value [EOWNERDEAD]. In this case, the mutex does not become normally usable again until the state is marked consistent.
If the thread which acquired the mutex lock with the return value [EOWNERDEAD] terminates before calling either Mutex::consistent() or Mutex::unlock(), the next thread that acquires the mutex lock shall be notified about the state of the mutex by the return value [EOWNERDEAD].
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 429 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::consistent (this);
 #else
       // TODO
       return result::ok;
 #endif
     }
result_t os::rtos::Mutex::lock (void)
Lock the mutex.
Return values
result::ok The mutex was locked.
EPERM Cannot be invoked from an Interrupt Service Routine.
ENOTRECOVERABLE The state protected by the mutex is not recoverable..
EAGAIN The mutex could not be acquired because the maximum number of recursive locks for mutex has been exceeded.
EINVAL The mutex was created with the protocol attribute having the value PTHREAD_PRIO_PROTECT and the calling thread's priority is higher than the mutex's current priority ceiling.
EOWNERDEAD The mutex is a robust mutex and the process containing the previous owning thread terminated while holding the mutex lock. The mutex lock shall be acquired by the calling thread and it is up to the new owner to make the state consistent.
EDEADLK The mutex type is PTHREAD_MUTEX_ERRORCHECK and the current thread already owns the mutex.
If the mutex is free, lock it. If the mutex is already locked by another thread, the calling thread shall block until the mutex becomes available. This operation shall return with the mutex object referenced by mutex in the locked state with the calling thread as its owner. If a thread attempts to relock a mutex that it has already locked, Mutex::lock() shall behave as described in the Relock column of the following table. If a thread attempts to unlock a mutex that it has not locked or a mutex which is unlocked, Mutex::unlock() shall behave as described in the Unlock When Not Owner column of the following table.
TODO: add table
Where the table indicates recursive behavior, the mutex shall maintain the concept of a lock count. When a thread successfully acquires a mutex for the first time, the lock count shall be set to one. Every time a thread relocks this mutex, the lock count shall be incremented by one. Each time the thread unlocks the mutex, the lock count shall be decremented by one. When the lock count reaches zero, the mutex shall become available for other threads to acquire.
pthread_mutex_lock() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 170 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::scheduler::lock(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
Referenced by prio_ceiling().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::lock (this);
 #else
       // TODO
       return result::ok;
 #endif
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Mutex& os::rtos::Mutex::operator= (const Mutex &) delete
Mutex& os::rtos::Mutex::operator= (Mutex &&) delete
bool os::rtos::Mutex::operator== (const Mutex & rhs) const inline
Compare mutexes.
Return values
true The given mutex is the same as this mutex.
false The mutexes are different.
Identical mutexes should have the same memory address.
Definition at line 2774 of file os.h.
     {
       return this == &rhs;
     }
Thread * os::rtos::Mutex::owner (void) inline
Definition at line 2780 of file os.h.
     {
       return owner_;
     }
thread::priority_t os::rtos::Mutex::prio_ceiling (void) const
Get the priority ceiling of a mutex.
Returns
The priority ceiling.
Return the current priority ceiling of the mutex.
pthread_mutex_getprioceiling() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_getprioceiling.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 337 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), os::trace::printf(), and prio_ceiling_.
Referenced by prio_ceiling().
     {
       assert(!scheduler::in_handler_mode ());
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::prio_ceiling (this);
 #else
       // TODO
       return prio_ceiling_;
 #endif
     }
result_t os::rtos::Mutex::prio_ceiling (thread::priority_t prio_ceiling, thread::priority_t * old_prio_ceiling = nullptr)
Change the priority ceiling of a mutex.
Parameters
[in] prio_ceiling new priority.
[out] old_prio_ceiling pointer to location where to store the previous priority; may be nullptr.
Return values
result::ok The priority was changed.
EPERM Cannot be invoked from an Interrupt Service Routine.
Attempt to lock the mutex as if by a call to Mutex::lock(), except that the process of locking the mutex need not adhere to the priority protect protocol. On acquiring the mutex it shall change the mutex's priority ceiling and then release the mutex as if by a call to Mutex::unlock(). When the change is successful, the previous value of the priority ceiling shall be returned in old_ceiling.
If Mutex::set_prio_ceiling() function fails, the mutex priority ceiling shall not be changed.
pthread_mutex_setprioceiling() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_getprioceiling.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 374 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), lock(), os::rtos::result::ok, os_assert_err, os::trace::printf(), prio_ceiling(), prio_ceiling_, and unlock().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::prio_ceiling (this, prio_ceiling, old_prio_ceiling);
 #else
       thread::priority_t prio;
         {
           // TODO: lock() must not adhere to the priority protocol.
           lock ();
           prio = prio_ceiling_;
           prio_ceiling_ = prio_ceiling;
           unlock ();
         }
       if (old_prio_ceiling != nullptr)
         {
           *old_prio_ceiling = prio;
         }
       return result::ok;
 #endif
     }
result_t os::rtos::Mutex::reset (void)
Definition at line 448 of file os-mutex.cpp.
References count_, and os::rtos::result::ok.
     {
       // TODO wait list?
       count_ = 0;
       return result::ok;
     }
result_t os::rtos::Mutex::timed_lock (systicks_t ticks)
Timed attempt to lock the mutex.
Parameters
[in] ticks Number of ticks to wait.
Return values
result::ok The mutex was locked.
EPERM Cannot be invoked from an Interrupt Service Routine.
ETIMEDOUT The mutex could not be locked before the specified timeout expired.
ENOTRECOVERABLE The state protected by the mutex is not recoverable.
EAGAIN The mutex could not be acquired because the maximum number of recursive locks for mutex has been exceeded.
EDEADLK The mutex type is PTHREAD_MUTEX_ERRORCHECK and the current thread already owns the mutex.
EINVAL The process or thread would have blocked, and the abstime parameter specified a nanoseconds field value less than zero or greater than or equal to 1000 million.
EOWNERDEAD The mutex is a robust mutex and the process containing the previous owning thread terminated while holding the mutex lock. The mutex lock shall be acquired by the calling thread and it is up to the new owner to make the state consistent.
Try to lock the mutex object referenced by mutex. If the mutex is already locked, the calling thread shall block until the mutex becomes available as in the Mutex::lock() function. If the mutex cannot be locked without waiting for another thread to unlock the mutex, this wait shall be terminated when the specified timeout expires.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Under no circumstance shall the function fail with a timeout if the mutex can be locked immediately.
As a consequence of the priority inheritance rules (for mutexes initialized with the PRIO_INHERIT protocol), if a timed mutex wait is terminated because its timeout expires, the priority of the owner of the mutex shall be adjusted as necessary to reflect the fact that this thread is no longer among the threads waiting for the mutex.
pthread_mutex_timedlock() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_timedlock.html
Differences from the standard:
the timeout is not expressed as an absolute time point, but as a relative number of system ticks.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 272 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d_ticks) @%p \n", __func__, ticks, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::timed_lock (this, ticks);
 #else
       // TODO
       return result::ok;
 #endif
     }
result_t os::rtos::Mutex::try_lock (void)
Try to lock the mutex.
Return values
result::ok The mutex was locked.
EPERM Cannot be invoked from an Interrupt Service Routine.
ENOTRECOVERABLE The state protected by the mutex is not recoverable..
EAGAIN The mutex could not be acquired because the maximum number of recursive locks for mutex has been exceeded.
EINVAL The mutex was created with the protocol attribute having the value PTHREAD_PRIO_PROTECT and the calling thread's priority is higher than the mutex's current priority ceiling.
EOWNERDEAD The mutex is a robust mutex and the process containing the previous owning thread terminated while holding the mutex lock. The mutex lock shall be acquired by the calling thread and it is up to the new owner to make the state consistent.
EDEADLK The mutex type is PTHREAD_MUTEX_ERRORCHECK and the current thread already owns the mutex.
EBUSY The mutex could not be acquired because it was already locked.
Try to lock the mutex as Mutex::lock(), except that if the mutex object referenced by mutex is currently locked (by any thread, including the current thread), the call shall return immediately. If the mutex type is PTHREAD_MUTEX_RECURSIVE and the mutex is currently owned by the calling thread, the mutex lock count shall be incremented by one and the Mutex::trylock() function shall immediately return success.
If mutex is a robust mutex and the process containing the owning thread terminated while holding the mutex lock, a call to Mutex::lock() shall return the error value [EOWNERDEAD]. If mutex is a robust mutex and the owning thread terminated while holding the mutex lock, a call to Mutex::lock() may return the error value [EOWNERDEAD] even if the process in which the owning thread resides has not terminated. In these cases, the mutex is locked by the thread but the state it protects is marked as inconsistent. The application should ensure that the state is made consistent for reuse and when that is complete call Mutex::consistent(). If the application is unable to recover the state, it should unlock the mutex without a prior call to Mutex::consistent(), after which the mutex is marked permanently unusable.
pthread_mutex_trylock() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 220 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::try_lock (this);
 #else
       // TODO
       return result::ok;
 #endif
     }
result_t os::rtos::Mutex::unlock (void)
Unlock the mutex.
Return values
result::ok The mutex was unlocked.
EPERM Cannot be invoked from an Interrupt Service Routine; the mutex type is PTHREAD_MUTEX_ERRORCHECK or PTHREAD_MUTEX_RECURSIVE, or the mutex is a robust mutex, and the current thread does not own the mutex.
ENOTRECOVERABLE The mutex was not unlocked.
Release the mutex object referenced by mutex. The manner in which a mutex is released is dependent upon the mutex's type attribute. If there are threads blocked on the mutex object referenced by mutex when Mutex::unlock() is called, resulting in the mutex becoming available, the scheduling policy shall determine which thread shall acquire the mutex.
(In the case of PTHREAD_MUTEX_RECURSIVE mutexes, the mutex shall become available when the count reaches zero and the calling thread no longer has any locks on this mutex.)
pthread_mutex_unlock() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 309 of file os-mutex.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, os::trace::printf(), and os::rtos::scheduler::unlock().
Referenced by prio_ceiling().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
 #if defined(OS_INCLUDE_PORT_RTOS_MUTEX)
       return port::Mutex::unlock (this);
 #else
       // TODO
       return result::ok;
 #endif
     }
Member Data Documentation
volatile mutex::count_t os::rtos::Mutex::count_ protected
Definition at line 1398 of file os.h.
Referenced by Mutex(), and reset().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
Thread* volatile os::rtos::Mutex::owner_ protected
Definition at line 1390 of file os.h.
Referenced by Mutex().
volatile thread::priority_t os::rtos::Mutex::prio_ceiling_ protected
Definition at line 1401 of file os.h.
Referenced by Mutex(), and prio_ceiling().
const mutex::protocol_t os::rtos::Mutex::protocol_ protected
Definition at line 1405 of file os.h.
Referenced by Mutex().
const mutex::robustness_t os::rtos::Mutex::robustness_ protected
Definition at line 1406 of file os.h.
Referenced by Mutex().
const mutex::type_t os::rtos::Mutex::type_ protected
Definition at line 1404 of file os.h.
Referenced by Mutex().
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-mutex.cpp