CMSIS++ Reference: os::driver::Serial Class Reference
os::driver::Serial Class Reference abstract
#include <serial.h>
Inherits os::driver::Base.
Inherited by os::driver::Usart_wrapper.
Public Member Functions
Serial () noexcept
Serial (const Serial &)=delete
Serial (Serial &&)=delete
Serial & operator= (const Serial &)=delete
Serial & operator= (Serial &&)=delete
virtual ~Serial () noexcept=default
void register_callback (signal_event_t cb_func, const void *cb_object=nullptr) noexcept
Register event callback.
const serial::Capabilities & get_capabilities (void) noexcept
Get driver capabilities.
return_t send (const void *data, std::size_t num) noexcept
Start the serial transmitter.
return_t receive (void *data, std::size_t num) noexcept
Start the serial receiver.
return_t transfer (const void *data_out, void *data_in, std::size_t num) noexcept
Start sending/receiving data to/from the serial transmitter/receiver.
std::size_t get_tx_count (void) noexcept
Get transmitted bytes count.
std::size_t get_rx_count (void) noexcept
Get received bytes count.
return_t configure (serial::config_t cfg, serial::config_arg_t arg) noexcept
Configure the serial interface.
return_t control (serial::control_t ctrl) noexcept
Control the serial interface.
serial::Status & get_status (void) noexcept
Get serial port status.
return_t control_modem_line (serial::Modem_control ctrl) noexcept
Configure serial modem lines.
serial::Modem_status & get_modem_status (void) noexcept
Get serial modem lines state.
void signal_event (event_t event) noexcept
Signal serial events.
void clean (void) noexcept
const Version & get_version (void) noexcept
Get driver version.
return_t power (Power state) noexcept
Power up/down device.
Protected Member Functions
virtual const serial::Capabilities & do_get_capabilities (void) noexcept=0
virtual return_t do_send (const void *data, std::size_t num) noexcept=0
virtual return_t do_receive (void *data, std::size_t num) noexcept=0
virtual return_t do_transfer (const void *data_out, void *data_in, std::size_t num) noexcept=0
virtual std::size_t do_get_tx_count (void) noexcept=0
virtual std::size_t do_get_rx_count (void) noexcept=0
virtual return_t do_configure (serial::config_t cfg, serial::config_arg_t arg) noexcept=0
virtual return_t do_control (serial::control_t ctrl) noexcept=0
virtual serial::Status & do_get_status (void) noexcept=0
virtual return_t do_control_modem_line (serial::Modem_control ctrl) noexcept=0
virtual serial::Modem_status & do_get_modem_status (void) noexcept=0
virtual const Version & do_get_version (void) noexcept=0
virtual return_t do_power (Power state) noexcept=0
Protected Attributes
signal_event_t cb_func_
Pointer to static function that implements the callback.
const void * cb_object_
Pointer to object instance associated with this driver.
serial::Status status_
serial::Modem_status modem_status_
Detailed Description
Definition at line 504 of file serial.h.
Constructor & Destructor Documentation
os::driver::Serial::Serial () noexcept
Definition at line 40 of file serial.cpp.
References cb_func_, cb_object_, and clean().
     {
       cb_func_ = nullptr;
       cb_object_ = nullptr;
       clean ();
     }
os::driver::Serial::Serial (const Serial &) delete
os::driver::Serial::Serial (Serial &&) delete
virtual os::driver::Serial::~Serial () virtual default noexcept
Member Function Documentation
void os::driver::Serial::clean (void) noexcept
Definition at line 51 of file serial.cpp.
References os::driver::serial::Modem_status::cts, os::driver::serial::Modem_status::dcd, os::driver::serial::Modem_status::dsr, modem_status_, os::driver::serial::Modem_status::ri, os::driver::serial::Status::rx_break, os::driver::serial::Status::rx_busy, os::driver::serial::Status::rx_framing_error, os::driver::serial::Status::rx_overflow, os::driver::serial::Status::rx_parity_error, status_, os::driver::serial::Status::tx_busy, and os::driver::serial::Status::tx_underflow.
Referenced by Serial().
     {
       status_.rx_break = false;
       status_.rx_busy = false;
       status_.rx_framing_error = false;
       status_.rx_overflow = false;
       status_.rx_parity_error = false;
       status_.tx_busy = false;
       status_.tx_underflow = false;
       modem_status_.cts = false;
       modem_status_.dsr = false;
       modem_status_.dcd = false;
       modem_status_.ri = false;
     }
return_t os::driver::Serial::configure (serial::config_t cfg, serial::config_arg_t arg) inline noexcept
Configure the serial interface.
Parameters
[in] control Operation
[in] arg Argument of operation (optional)
Returns
common execution_status and driver specific usart_execution_status
Definition at line 790 of file serial.h.
References arg.
     {
       return do_configure (cfg, arg);
     }
return_t os::driver::Serial::control (serial::control_t ctrl) inline noexcept
Control the serial interface.
Parameters
[in] control Operation
[in] arg Argument of operation (optional)
Returns
common execution_status and driver specific usart_execution_status
Definition at line 796 of file serial.h.
     {
       return do_control (ctrl);
     }
return_t os::driver::Serial::control_modem_line (serial::Modem_control ctrl) inline noexcept
Configure serial modem lines.
Parameters
[in] control ARM_USART_MODEM_CONTROL
Returns
execution_status
Definition at line 808 of file serial.h.
     {
       return do_control_modem_line (ctrl);
     }
virtual return_t os::driver::Serial::do_configure (serial::config_t cfg, serial::config_arg_t arg) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual return_t os::driver::Serial::do_control (serial::control_t ctrl) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual return_t os::driver::Serial::do_control_modem_line (serial::Modem_control ctrl) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual const serial::Capabilities& os::driver::Serial::do_get_capabilities (void) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual serial::Modem_status& os::driver::Serial::do_get_modem_status (void) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual std::size_t os::driver::Serial::do_get_rx_count (void) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual serial::Status& os::driver::Serial::do_get_status (void) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual std::size_t os::driver::Serial::do_get_tx_count (void) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
virtual const Version& os::driver::Base::do_get_version (void) protected pure virtual noexcept inherited
Implemented in os::driver::Usbh_wrapper, os::driver::Usbd_wrapper, and os::driver::Usart_wrapper.
virtual return_t os::driver::Base::do_power (Power state) protected pure virtual noexcept inherited
Implemented in os::driver::Usbd_wrapper, os::driver::Usbh_wrapper, and os::driver::Usart_wrapper.
virtual return_t os::driver::Serial::do_receive (void * data, std::size_t num) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
Referenced by receive().
virtual return_t os::driver::Serial::do_send (const void * data, std::size_t num) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
Referenced by send().
virtual return_t os::driver::Serial::do_transfer (const void * data_out, void * data_in, std::size_t num) protected pure virtual noexcept
Implemented in os::driver::Usart_wrapper.
Referenced by transfer().
const serial::Capabilities & os::driver::Serial::get_capabilities (void) inline noexcept
Get driver capabilities.
Returns
ARM_USART_CAPABILITIES
Definition at line 772 of file serial.h.
     {
       return do_get_capabilities ();
     }
serial::Modem_status & os::driver::Serial::get_modem_status (void) inline noexcept
Get serial modem lines state.
Returns
modem status ARM_USART_MODEM_STATUS
Definition at line 814 of file serial.h.
     {
       return do_get_modem_status ();
     }
std::size_t os::driver::Serial::get_rx_count (void) inline noexcept
Get received bytes count.
Returns
number of bytes received
Definition at line 784 of file serial.h.
     {
       return do_get_rx_count ();
     }
serial::Status & os::driver::Serial::get_status (void) inline noexcept
Get serial port status.
Returns
Serial status ARM_USART_STATUS
Definition at line 802 of file serial.h.
     {
       return do_get_status ();
     }
std::size_t os::driver::Serial::get_tx_count (void) inline noexcept
Get transmitted bytes count.
Returns
number of bytes transmitted
Definition at line 778 of file serial.h.
     {
       return do_get_tx_count ();
     }
const Version & os::driver::Base::get_version (void) inline noexcept inherited
Get driver version.
Returns
ARM_DRIVER_VERSION
Definition at line 195 of file common.h.
     {
       return do_get_version ();
     }
Serial& os::driver::Serial::operator= (const Serial &) delete
Serial& os::driver::Serial::operator= (Serial &&) delete
return_t os::driver::Base::power (Power state) inline noexcept inherited
Power up/down device.
Parameters
[in] state Power state
Returns
execution_status
Definition at line 201 of file common.h.
     {
       return do_power (state);
     }
return_t os::driver::Serial::receive (void * data, std::size_t num) noexcept
Start the serial receiver.
Parameters
[out] data Pointer to buffer for data to receive from USART receiver
[in] num Number of data items to receive
Returns
execution_status
Definition at line 88 of file serial.cpp.
References do_receive(), and os::driver::RETURN_OK.
     {
       assert(data != nullptr);
       if (num == 0)
         {
           return RETURN_OK;
         }
       return do_receive (data, num);
     }
void os::driver::Serial::register_callback (signal_event_t cb_func, const void * cb_object = nullptr) noexcept
Register event callback.
Parameters
[in] cb_event Pointer to ARM_USART_SignalEvent
Returns
execution_status
Definition at line 70 of file serial.cpp.
References cb_func_, and cb_object_.
     {
       cb_func_ = cb_func;
       cb_object_ = cb_object;
     }
return_t os::driver::Serial::send (const void * data, std::size_t num) noexcept
Start the serial transmitter.
Parameters
[in] data Pointer to buffer with data to send to USART transmitter
[in] num Number of data items to send
Returns
execution_status
Definition at line 77 of file serial.cpp.
References do_send(), and os::driver::RETURN_OK.
     {
       assert(data != nullptr);
       if (num == 0)
         {
           return RETURN_OK;
         }
       return do_send (data, num);
     }
void os::driver::Serial::signal_event (event_t event) inline noexcept
Signal serial events.
Parameters
[in] event USART_events notification mask
Returns
none
Definition at line 820 of file serial.h.
     {
       if (cb_func_ != nullptr)
         {
           // Forward event to registered callback.
           cb_func_ (cb_object_, event);
         }
     }
return_t os::driver::Serial::transfer (const void * data_out, void * data_in, std::size_t num) noexcept
Start sending/receiving data to/from the serial transmitter/receiver.
Parameters
[in] data_out Pointer to buffer with data to send
[out] data_in Pointer to buffer for data to receive
[in] num Number of bytes to transfer
Returns
execution_status
Definition at line 99 of file serial.cpp.
References do_transfer(), and os::driver::RETURN_OK.
     {
       assert(data_out != nullptr);
       assert(data_in != nullptr);
       if (num == 0)
         {
           return RETURN_OK;
         }
       return do_transfer (data_out, data_in, num);
     }
Member Data Documentation
signal_event_t os::driver::Serial::cb_func_ protected
Pointer to static function that implements the callback.
Definition at line 681 of file serial.h.
Referenced by register_callback(), and Serial().
const void* os::driver::Serial::cb_object_ protected
Pointer to object instance associated with this driver.
Definition at line 684 of file serial.h.
Referenced by register_callback(), and Serial().
serial::Modem_status os::driver::Serial::modem_status_ protected
Definition at line 687 of file serial.h.
Referenced by clean().
serial::Status os::driver::Serial::status_ protected
Definition at line 686 of file serial.h.
Referenced by clean().
The documentation for this class was generated from the following files:
include/cmsis-plus/drivers/serial.h
src/cmsis-plus/drivers/serial.cpp