CMSIS++ Reference: os::rtos::scheduler::Lock Class Reference
os::rtos::scheduler::Lock Class Reference
#include <os.h>
Public Member Functions
constexpr Lock ()
~Lock ()
Lock (const Lock &)=delete
Lock (Lock &&)=delete
Lock & operator= (const Lock &)=delete
Lock & operator= (Lock &&)=delete
void lock (void)
bool try_lock (void)
void unlock (void)
Protected Attributes
status_t status_ = 0
Detailed Description
Definition at line 207 of file os.h.
Constructor & Destructor Documentation
constexpr os::rtos::scheduler::Lock::Lock ()
Definition at line 2472 of file os.h.
                   :
           status_ (0)
       {
         ;
       }
os::rtos::scheduler::Lock::~Lock () inline
Definition at line 2479 of file os.h.
       {
         ;
       }
os::rtos::scheduler::Lock::Lock (const Lock &) delete
os::rtos::scheduler::Lock::Lock (Lock &&) delete
Member Function Documentation
void os::rtos::scheduler::Lock::lock (void) inline
Definition at line 2485 of file os.h.
References os::rtos::scheduler::lock(), and status_.
       {
         status_ = scheduler::lock ();
       }
Lock& os::rtos::scheduler::Lock::operator= (const Lock &) delete
Lock& os::rtos::scheduler::Lock::operator= (Lock &&) delete
bool os::rtos::scheduler::Lock::try_lock (void) inline
Definition at line 2491 of file os.h.
References os::rtos::scheduler::lock(), and status_.
       {
         status_ = scheduler::lock ();
         return true;
       }
void os::rtos::scheduler::Lock::unlock (void) inline
Definition at line 2498 of file os.h.
References status_, and os::rtos::scheduler::unlock().
       {
         scheduler::unlock (status_);
       }
Member Data Documentation
status_t os::rtos::scheduler::Lock::status_ = 0 protected
Definition at line 234 of file os.h.
Referenced by lock(), try_lock(), and unlock().
The documentation for this class was generated from the following file:
include/cmsis-plus/rtos/os.h