CMSIS++ Reference: os::rtos::Systick_clock Class Reference
os::rtos::Systick_clock Class Reference
#include <os.h>
Public Types
using rep = uint64_t
using sleep_rep = duration_t
using current_t = struct current_s{uint64_t ticks
SysTick detailed timestamp.
Public Member Functions
template<typename Rep_T >
constexpr systicks_t ticks_cast (Rep_T microsec)
Static Public Member Functions
static rep now (void)
Tell the current time.
static rep now (current_t *details)
Tell the current time.
template<typename Rep_T >
static constexpr uint32_t ticks_cast (Rep_T microsec)
Convert microseconds to ticks.
static result_t sleep_for (sleep_rep ticks)
Sleep a number of ticks.
static result_t wait (sleep_rep ticks)
Wait for an event.
Public Attributes
uint32_t cycles
uint32_t divisor
uint32_t core_frequency_hz
Static Public Attributes
static constexpr uint32_t frequency_hz = OS_INTEGER_SYSTICK_FREQUENCY_HZ
Static Protected Member Functions
static result_t _wait (sleep_rep ticks)
Detailed Description
The SysTick clock should be a steady clock, i.e. the total count of ticks should be monotone ascending (in other words no adjustments to the past should be performed).
Definition at line 867 of file os.h.
Member Typedef Documentation
using os::rtos::Systick_clock::current_t = struct current_s { uint64_t ticks
SysTick detailed timestamp.
When an accurate timestamp is needed, the current SysTick counter can be sampled to get the count of CPU cycles inside the tick. For a 100 MHz clock, this is a 10 ns resolution.
To simplify further processing of this timestamp, the structure also includes the CPU clock and the SysTick divider.
Definition at line 898 of file os.h.
using os::rtos::Systick_clock::rep = uint64_t
Definition at line 872 of file os.h.
using os::rtos::Systick_clock::sleep_rep = duration_t
Definition at line 873 of file os.h.
Member Function Documentation
result_t os::rtos::Systick_clock::_wait (Systick_clock::sleep_rep ticks) static protected
Definition at line 183 of file os-clocks.cpp.
References os::rtos::result::ok.
     {
       if (ticks == 0)
         {
           ticks = 1;
         }
       result_t res;
 #if defined(OS_INCLUDE_PORT_RTOS_SYSTICK_CLOCK_SLEEP_FOR)
       res = port::Systick_clock::wait (ticks);
 #else
       // TODO
       res = result::ok;
 #endif
       return res;
     }
Systick_clock::rep os::rtos::Systick_clock::now (void) static
Tell the current time.
Returns
The number of SysTick ticks since startup.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 113 of file os-clocks.cpp.
References os::rtos::__systick_now.
Referenced by os::rtos::Realtime_clock::now(), os_systick_clock_now(), os_systick_clock_now_details(), osKernelRunning(), os::rtos::Thread::sig_wait(), sleep_for(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Thread::timed_sig_wait(), and os::rtos::Event_flags::timed_wait().
     {
       interrupts::Critical_section cs; // ----- Critical section -----
       // Prevent inconsistent values using the critical section.
       return __systick_now;
     }
Systick_clock::rep os::rtos::Systick_clock::now (current_t * details) static
Tell the current time.
Returns
Accurate sampling of SysTick.
Return the very accurate current time, using the internal SysTick cycle counter, which, at 100 MHz and 1000 ticks/sec allows a 10 ns resolution.
The function adjust for border conditions, when the SysTick counter is reloaded during the call.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 133 of file os-clocks.cpp.
References os::rtos::__systick_now.
     {
       assert(details != nullptr);
       // The core frequency can be returned right away, since
       // is not expected to change during this call.
       details->core_frequency_hz = SystemCoreClock;
       // The timer reload value, it is the divisor - 1.
       uint32_t load = SysTick->LOAD;
       // Can also be returned right away.
       details->divisor = load + 1;
       // The ticks and cycles must be read atomically, use a critical
       // section and adjust for border condition, when the event
       // came exactly after entering the critical section.
       uint64_t ticks;
       uint32_t val;
         {
           interrupts::Critical_section cs; // ----- Critical section -----
           // Sample ticks counter inside critical section.
           ticks = __systick_now;
           // Initial sample of the decrementing counter.
           // Might happen before the event, will be used as such.
           val = SysTick->VAL;
           // Check overflow. If the exception is pending, it means the
           // ticks counter was not yet updated, but the counter was reloaded.
           if (SysTick->CTRL & SCB_ICSR_PENDSTSET_Msk)
             {
               // Sample the decrementing counter again to validate the
               // initial sample.
               uint32_t val_update = SysTick->VAL;
               if (val_update > val)
                 {
                   // The second sample is more accurate.
                   val = val_update;
                 }
               ticks++; // Adjust to next tick.
             }
         }
       details->cycles = load - val;
       details->ticks = ticks;
       return ticks;
     }
result_t os::rtos::Systick_clock::sleep_for (Systick_clock::sleep_rep ticks) static
Sleep a number of ticks.
Parameters
[in] ticks The number of ticks to sleep.
Return values
ETIMEDOUT The sleep lasted the entire duration.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINTR The sleep was interrupted.
Put the current thread to sleep until the given number of SysTick cycles are counted. The first tick counted does not represent a full SysTick clock period, but only the remaining part in the current period, which might be almost nothing.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 211 of file os-clocks.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Thread::interrupted(), now(), os_assert_err, os::trace::printf(), and os::rtos::this_thread::thread().
Referenced by os_systick_clock_sleep_for(), and osDelay().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d_ticks)\n", __func__, ticks);
       Systick_clock::rep prev = Systick_clock::now ();
       Systick_clock::sleep_rep ticks_to_go = ticks;
       for (;;)
         {
           result_t res;
           res = _wait (ticks_to_go);
           Systick_clock::rep now = Systick_clock::now ();
           Systick_clock::sleep_rep slept_ticks = (Systick_clock::sleep_rep) (now
               - prev);
           if (slept_ticks >= ticks_to_go)
             {
               return ETIMEDOUT;
             }
           if (this_thread::thread ().interrupted ())
             {
               return EINTR;
             }
           if (res != ETIMEDOUT)
             {
               return res;
             }
           prev = now;
           ticks_to_go -= slept_ticks;
         }
       return ENOTRECOVERABLE;
     }
template<typename Rep_T > static constexpr uint32_t os::rtos::Systick_clock::ticks_cast (Rep_T microsec) static
Convert microseconds to ticks.
Template Parameters
Rep_T Type of input, auto deduced (usually uint32_t or uin64_t)
Parameters
[in] microsec The number of microseconds.
Returns
The number of ticks.
Referenced by osDelay(), osMutexDelete(), osMutexWait(), osSignalWait(), and osTimerStart().
template<typename Rep_T > constexpr systicks_t os::rtos::Systick_clock::ticks_cast (Rep_T microsec)
Round up the microseconds value and convert to number of ticks, using the SysTick frequency in Hz.
Definition at line 2512 of file os.h.
References os::rtos::Named_object::Named_object().
       {
         // TODO: add some restrictions to match only numeric types
         return (systicks_t) ((((microsec) * ((Rep_T) frequency_hz))
             + (Rep_T) 999999ul) / (Rep_T) 1000000ul);
       }
result_t os::rtos::Systick_clock::wait (Systick_clock::sleep_rep ticks) static
Wait for an event.
Parameters
[in] ticks The timeout in ticks.
Return values
result::ok An event occurred before the timeout.
ETIMEDOUT The wait lasted the entire duration.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINTR The sleep was interrupted.
Put the current thread to sleep until a resume(). If the resume() does not occur until the next n-th SysTick, the wait() returns with a timeout.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 258 of file os-clocks.cpp.
References os::rtos::scheduler::in_handler_mode(), os_assert_err, os::trace::printf(), and os::rtos::this_thread::thread().
Referenced by os_systick_clock_wait(), osDelay(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), and os::rtos::Event_flags::timed_wait().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d_ticks)\n", __func__, ticks);
       result_t res;
       res = _wait (ticks);
       if (this_thread::thread ().interrupted ())
         {
           return EINTR;
         }
       return res;
     }
Member Data Documentation
uint32_t os::rtos::Systick_clock::core_frequency_hz
Definition at line 901 of file os.h.
uint32_t os::rtos::Systick_clock::cycles
Definition at line 899 of file os.h.
uint32_t os::rtos::Systick_clock::divisor
Definition at line 900 of file os.h.
constexpr uint32_t os::rtos::Systick_clock::frequency_hz = OS_INTEGER_SYSTICK_FREQUENCY_HZ static
Definition at line 871 of file os.h.
Referenced by os_systick_handler().
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-clocks.cpp