CMSIS++ Reference: os::rtos::interrupts::Lock Class Reference
os::rtos::interrupts::Lock Class Reference
#include <os.h>
Public Member Functions
constexpr Lock ()
~Lock ()
Lock (const Lock &)=delete
Lock (Lock &&)=delete
Lock & operator= (const Lock &)=delete
Lock & operator= (Lock &&)=delete
void lock (void)
bool try_lock (void)
void unlock (void)
Protected Attributes
status_t status_
Detailed Description
Definition at line 285 of file os.h.
Constructor & Destructor Documentation
constexpr os::rtos::interrupts::Lock::Lock ()
Definition at line 2554 of file os.h.
                   :
           status_ (0)
       {
         ;
       }
os::rtos::interrupts::Lock::~Lock () inline
Definition at line 2561 of file os.h.
       {
         ;
       }
os::rtos::interrupts::Lock::Lock (const Lock &) delete
os::rtos::interrupts::Lock::Lock (Lock &&) delete
Member Function Documentation
void os::rtos::interrupts::Lock::lock (void) inline
Definition at line 2567 of file os.h.
References os::rtos::interrupts::Critical_section::enter(), and status_.
       {
         status_ = Critical_section::enter ();
       }
Lock& os::rtos::interrupts::Lock::operator= (const Lock &) delete
Lock& os::rtos::interrupts::Lock::operator= (Lock &&) delete
bool os::rtos::interrupts::Lock::try_lock (void) inline
Definition at line 2573 of file os.h.
References os::rtos::interrupts::Critical_section::enter(), and status_.
       {
         status_ = Critical_section::enter ();
         return true;
       }
void os::rtos::interrupts::Lock::unlock (void) inline
Definition at line 2580 of file os.h.
References os::rtos::interrupts::Critical_section::exit(), and status_.
       {
         Critical_section::exit (status_);
       }
Member Data Documentation
status_t os::rtos::interrupts::Lock::status_ protected
Definition at line 312 of file os.h.
Referenced by lock(), try_lock(), and unlock().
The documentation for this class was generated from the following file:
include/cmsis-plus/rtos/os.h