CMSIS++ Reference: os::rtos::Thread Class Reference
os::rtos::Thread Class Reference
POSIX thread.
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Thread (thread::func_t function, thread::func_args_t args)
Create a new thread with default settings.
Thread (const thread::Attributes &attr, thread::func_t function, thread::func_args_t args)
Create a new thread with custom settings.
Thread (const Thread &)=delete
Thread (Thread &&)=delete
Thread & operator= (const Thread &)=delete
Thread & operator= (Thread &&)=delete
~Thread ()
bool operator== (const Thread &rhs) const
Compare threads.
result_t cancel (void)
Cancel thread execution.
result_t join (void **exit_ptr=nullptr)
Wait for thread termination.
result_t detach (void)
Detach a thread.
result_t sched_prio (thread::priority_t prio)
Set dynamic scheduling priority.
thread::priority_t sched_prio (void)
Get the current scheduling priority.
bool interrupted (void)
thread::state_t sched_state (void) const
void wakeup (void)
Wake-up the thread.
void * function_args (void) const
os_thread_user_storage_t * user_storage (void)
Get user storage.
result_t sig_raise (thread::sigset_t mask, thread::sigset_t *oflags)
Raise thread signal flags.
result_t sig_clear (thread::sigset_t mask, thread::sigset_t *oflags)
Clear thread signal flags.
thread::sigset_t sig_get (thread::sigset_t mask, flags::mode_t mode)
Get/clear thread signal flags.
result_t kill (void)
Force thread termination.
const char * name (void) const
Protected Member Functions
void suspend (void)
Suspend the current thread.
void exit (void *exit_ptr=nullptr)
Terminate thread.
result_t sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
result_t try_sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
result_t timed_sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, systicks_t ticks, flags::mode_t mode)
result_t _try_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
void _destroy (void)
Static Protected Member Functions
static void _invoke_with_exit (Thread *thread)
Invoke terminating thread function.
Protected Attributes
void * stack_addr_
thread::func_t func_
thread::func_args_t func_args_
void * func_result_
Thread * joiner_
std::size_t stack_size_bytes_
thread::state_t sched_state_
thread::priority_t prio_
result_t wakeup_reason_
thread::sigset_t sig_mask_
os_thread_user_storage_t user_storage_
const char *const name_
Friends
void this_thread::suspend (void)
void this_thread::exit (void *exit_ptr)
result_t this_thread::sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
result_t this_thread::try_sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
result_t this_thread::timed_sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, systicks_t ticks, flags::mode_t mode)
Detailed Description
POSIX thread.
Supports terminating functions and a simplified version of signal flags.
Compatible with POSIX threads: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/pthread.h.html
Definition at line 598 of file os.h.
Constructor & Destructor Documentation
os::rtos::Thread::Thread (thread::func_t function, thread::func_args_t args)
Create a new thread with default settings.
Create a new thread, with default attributes.
The thread is created executing function with args as its sole argument. If the start_routine returns, the effect shall be as if there was an implicit call to exit() using the return value of function as the exit status. Note that the thread in which main() was originally invoked differs from this. When it returns from main(), the effect shall be as if there was an implicit call to exit() using the return value of main() as the exit status.
Compatible with pthread_create(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 177 of file os-thread.cpp.
References os::rtos::thread::initializer.
                                                                  :
         Thread
           { thread::initializer, function, args }
     {
       ;
     }
os::rtos::Thread::Thread (const thread::Attributes & attr, thread::func_t function, thread::func_args_t args)
Create a new thread with custom settings.
Create a new thread, with attributes specified by attr. If attr is NULL, the default attributes shall be used. If the attributes specified by attr are modified later, the thread's attributes shall not be affected.
The thread is created executing function with args as its sole argument. If the start_routine returns, the effect shall be as if there was an implicit call to exit() using the return value of function as the exit status. Note that the thread in which main() was originally invoked differs from this. When it returns from main(), the effect shall be as if there was an implicit call to exit() using the return value of main() as the exit status.
Compatible with pthread_create(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 206 of file os-thread.cpp.
References args, attr, func_, func_args_, os::rtos::scheduler::in_handler_mode(), joiner_, os::rtos::Named_object::name(), os::rtos::thread::priority::none, os_assert_throw, os::trace::printf(), prio_, sched_state_, sig_mask_, stack_addr_, stack_size_bytes_, and os::rtos::this_thread::yield().
                                             :
         Named_object
           { attr.name () }
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       assert(function != nullptr);
       assert(attr.th_priority != thread::priority::none);
       // Prevent the new thread to execute before all members are set.
       scheduler::Critical_section cs; // ----- Critical section -----
       // Get attributes from user structure.
       prio_ = attr.th_priority;
       stack_size_bytes_ = attr.th_stack_size_bytes;
       stack_addr_ = attr.th_stack_address;
       func_ = function;
       func_args_ = args;
       sig_mask_ = 0;
       joiner_ = nullptr;
       trace::printf ("%s @%p %s %d %d\n", __func__, this, name (), prio_,
                      stack_size_bytes_);
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       port::Thread::create (this);
       sched_state_ = thread::state::ready;
 #else
       // TODO: check min size
       // TODO: align stack
       if (stack_addr_ == nullptr)
         {
           // TODO: alloc default stack size
         }
       state_ = thread::state::inactive;
       scheduler::__register_thread (this);
 #endif
       this_thread::yield ();
     }
os::rtos::Thread::Thread (const Thread &) delete
os::rtos::Thread::Thread (Thread &&) delete
os::rtos::Thread::~Thread ()
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 261 of file os-thread.cpp.
References _destroy().
     {
       _destroy ();
     }
Member Function Documentation
void os::rtos::Thread::_destroy (void) protected
The actual destructor, also called from exit() and kill().
Definition at line 267 of file os-thread.cpp.
References os::rtos::Named_object::name(), os::trace::printf(), and sched_state_.
Referenced by exit(), kill(), and ~Thread().
     {
       if (sched_state_ == thread::state::destroyed)
         {
           return;
         }
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       sched_state_ = thread::state::destroyed;
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       port::Thread::destroy (this);
       // Does not return if the current thread.
 #else
       // TODO
       scheduler::__unregister_thread (this);
 #endif
     }
void os::rtos::Thread::_invoke_with_exit (Thread * thread) static protected
Invoke terminating thread function.
Parameters
[in] thread The static this.
Same as in POSIX, thread functions can return, and the behaviour should be as the thread called the exit() function.
This requires a proxy to run the thread function, get the result, and explicitly invoke exit().
Definition at line 152 of file os-thread.cpp.
References exit(), func_, func_args_, os::rtos::Named_object::name(), and os::trace::printf().
     {
       trace::printf ("%s @%p %s\n", __func__, thread, thread->name ());
       thread->exit (thread->func_ (thread->func_args_));
     }
result_t os::rtos::Thread::_try_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) protected
Internal function used to test if the desired signal flags are raised.
Definition at line 736 of file os-thread.cpp.
References os::rtos::flags::mode::all, os::rtos::flags::mode::any, os::rtos::result::ok, and sig_mask_.
Referenced by sig_wait(), timed_sig_wait(), and try_sig_wait().
     {
       if ((mask != 0) && ((mode & flags::mode::all) != 0))
         {
           // Only if all desires signals are raised we're done.
           if ((sig_mask_ & mask) == mask)
             {
               if (oflags != nullptr)
                 {
                   *oflags = sig_mask_;
                 }
               // Clear desired signals.
               sig_mask_ &= ~mask;
               return result::ok;
             }
         }
       else if ((mask == 0) || ((mode & flags::mode::any) != 0))
         {
           // Any signal will do it.
           if (sig_mask_ != 0)
             {
               // Possibly return .
               if (oflags != nullptr)
                 {
                   *oflags = sig_mask_;
                 }
               // Since we returned them all, also clear them all.
               sig_mask_ = 0;
               return result::ok;
             }
         }
       return EAGAIN;
     }
result_t os::rtos::Thread::cancel (void)
Cancel thread execution.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
pthread_cancel() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cancel.html
The cancel() function shall not return an error code of [EINTR]. If an implementation detects use of a thread ID after the end of its lifetime, it is recommended that the function should fail and report an [ESRCH] error. error number is returned.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 528 of file os-thread.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       // TODO
       return result::ok;
     }
result_t os::rtos::Thread::detach (void)
Detach a thread.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Indicate to the implementation that storage for the thread thread can be reclaimed when that thread terminates. If thread has not terminated, detach() shall not cause it to terminate. The behaviour is undefined if the value specified by the thread argument to detach() does not refer to a joinable thread.
pthread_detach() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_detach.html
The detach() function shall not return an error code of [EINTR].
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 490 of file os-thread.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       result_t res = port::Thread::detach (this);
       if (res != result::ok)
         {
           return res;
         }
 #else
       // TODO
 #endif
       return result::ok;
     }
void os::rtos::Thread::exit (void * value_ptr = nullptr) protected
Terminate thread.
Returns
-
Terminate the calling thread and make the value value_ptr available to any successful join with the terminating thread. Any cancellation cleanup handlers that have been pushed and not yet popped shall be popped in the reverse order that they were pushed and then executed. After all cancellation cleanup handlers have been executed, if the thread has any thread-specific data, appropriate destructor functions shall be called in an unspecified order. Thread termination does not release any application visible process resources, including, but not limited to, mutexes and file descriptors, nor does it perform any process-level cleanup actions, including, but not limited to, calling any atexit() routines that may exist. An implicit call to exit() is made when a thread other than the thread in which main() was first invoked returns from the start routine that was used to create it. The function's return value shall serve as the thread's exit status. The behaviour of exit() is undefined if called from a cancellation cleanup handler or destructor function that was invoked as a result of either an implicit or explicit call to exit(). After a thread has terminated, the result of access to local (auto) variables of the thread is undefined. Thus, references to local variables of the exiting thread should not be used for the exit() value_ptr parameter value.
pthread_exit() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_exit.html
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 580 of file os-thread.cpp.
References _destroy(), func_result_, os::rtos::scheduler::in_handler_mode(), joiner_, os::rtos::Named_object::name(), os::trace::printf(), sched_state_, and wakeup().
Referenced by _invoke_with_exit(), and os::rtos::this_thread::exit().
     {
       assert(!scheduler::in_handler_mode ());
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       if (sched_state_ == thread::state::terminated)
         {
           trace::printf ("%s() @%p %s already terminated\n", __func__, this,
                          name ());
           return; // Already terminated
         }
       func_result_ = value_ptr;
       sched_state_ = thread::state::terminated;
       if (joiner_ != nullptr)
         {
           joiner_->wakeup ();
         }
       _destroy ();
       // Does not return.
     }
void * os::rtos::Thread::function_args (void) const inline
Definition at line 2680 of file os.h.
     {
       return func_args_;
     }
bool os::rtos::Thread::interrupted (void)
Definition at line 539 of file os-thread.cpp.
Referenced by sig_wait(), os::rtos::Systick_clock::sleep_for(), and timed_sig_wait().
     {
       return false;
     }
result_t os::rtos::Thread::join (void ** exit_ptr = nullptr)
Wait for thread termination.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Suspend execution of the calling thread until the target thread terminates, unless the target thread has already terminated. On return from a successful join() call with a non-NULL exit_ptr argument, the value passed to exit() by the terminating thread shall be made available in the location referenced by exit_ptr. When a join() returns successfully, the target thread has been terminated. The results of multiple simultaneous calls to join() specifying the same target thread are undefined. If the thread calling join() is cancelled, then the target thread shall not be detached.
pthread_join() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_join.html
The join() function may fail if: [EDEADLK] A deadlock was detected.
The join() function shall not return an error code of [EINTR].
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 449 of file os-thread.cpp.
References func_result_, os::rtos::scheduler::in_handler_mode(), joiner_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), sched_state_, and suspend().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       // TODO: Must fail if current thread
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       while ((sched_state_ != thread::state::terminated)
           && (sched_state_ != thread::state::destroyed))
         {
           joiner_ = this;
           suspend ();
         }
       if (exit_ptr != nullptr)
         {
           *exit_ptr = func_result_;
         }
       trace::printf ("%s() @%p %s joined\n", __func__, this, name ());
       return result::ok;
     }
result_t os::rtos::Thread::kill (void)
Force thread termination.
Return values
result::ok The tread was terminated.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 611 of file os-thread.cpp.
References _destroy(), func_result_, os::rtos::scheduler::in_handler_mode(), joiner_, os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), sched_state_, and wakeup().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       if ((sched_state_ == thread::state::terminated)
           || (sched_state_ == thread::state::destroyed))
         {
           trace::printf ("%s() @%p %s already terminated\n", __func__, this,
                          name ());
           return result::ok; // Already terminated
         }
       func_result_ = nullptr;
       sched_state_ = thread::state::terminated;
       if (joiner_ != nullptr)
         {
           joiner_->wakeup ();
         }
       _destroy ();
       return result::ok;
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by _destroy(), _invoke_with_exit(), os::rtos::Memory_pool::alloc(), cancel(), os::rtos::Condition_variable::Condition_variable(), detach(), os::rtos::Event_flags::Event_flags(), exit(), os::rtos::Memory_pool::free(), join(), kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), sig_clear(), sig_get(), sig_raise(), sig_wait(), suspend(), Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Thread& os::rtos::Thread::operator= (const Thread &) delete
Thread& os::rtos::Thread::operator= (Thread &&) delete
bool os::rtos::Thread::operator== (const Thread & rhs) const inline
Compare threads.
Return values
true The given thread is the same as this thread.
false The threads are different.
Identical threads should have the same memory address.
Compatible with POSIX pthread_equal(). http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_equal.html
Definition at line 2668 of file os.h.
     {
       return this == &rhs;
     }
result_t os::rtos::Thread::sched_prio (thread::priority_t prio)
Set dynamic scheduling priority.
Return values
result::ok The priority was set.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINVAL The value of prio is invalid for the scheduling policy of the specified thread.
Set the scheduling priority for the thread to the value given by prio.
pthread_setschedprio() http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_setschedprio.html
If an implementation detects use of a thread ID after the end of its lifetime, it is recommended that the function should fail and report an [ESRCH] error.
The pthread_setschedprio() function shall not return an error code of [EINTR].
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 394 of file os-thread.cpp.
References os::rtos::thread::priority::error, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os::rtos::thread::priority::none, os::rtos::result::ok, os_assert_err, os::trace::printf(), prio_, and os::rtos::this_thread::yield().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       os_assert_err(prio < thread::priority::error, EINVAL);
       os_assert_err(prio != thread::priority::none, EINVAL);
       trace::printf ("%s(%d) @%p %s\n", __func__, prio, this, name ());
       result_t res = result::ok;
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       // The port must perform a context switch.
       res = port::Thread::sched_prio (this, prio);
 #else
       // TODO
       prio_ = prio;
       // Mandatory, the priority might have been raised, the
       // task must be scheduled to run.
       this_thread::yield ();
 #endif
       return res;
     }
thread::priority_t os::rtos::Thread::sched_prio (void)
Get the current scheduling priority.
Returns
The thread priority.
No POSIX equivalent.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 357 of file os-thread.cpp.
References os::rtos::thread::priority::error, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_err, os::trace::printf(), and prio_.
     {
       os_assert_err(!scheduler::in_handler_mode (), thread::priority::error);
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       return port::Thread::sched_prio (this);
 #else
       // TODO
       return prio_;
 #endif
     }
thread::state_t os::rtos::Thread::sched_state (void) const inline
Definition at line 2674 of file os.h.
Referenced by osThreadCreate().
     {
       return sched_state_;
     }
result_t os::rtos::Thread::sig_clear (thread::sigset_t mask, thread::sigset_t * oflags)
Clear thread signal flags.
Parameters
[out] oflags Optional pointer where to store the previous flags; may be nullptr.
[in] mask The OR-ed flags to clear.
Return values
result::ok The flags were cleared.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINVAL The mask is zero.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 710 of file os-thread.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), and sig_mask_.
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       os_assert_err(mask != 0, EINVAL);
       trace::printf ("%s(0x%X) @%p %s\n", __func__, mask, this, name ());
       interrupts::Critical_section cs; // ----- Critical section -----
       if (oflags != nullptr)
         {
           *oflags = sig_mask_;
         }
       // Clear the selected bits; leave the rest untouched.
       sig_mask_ &= ~mask;
       return result::ok;
     }
thread::sigset_t os::rtos::Thread::sig_get (thread::sigset_t mask, flags::mode_t mode)
Get/clear thread signal flags.
Parameters
[in] mask The OR-ed flags to get/clear; may be zero.
[in] mode Mode bits to select if the flags should be cleared (the other bits are ignored).
Return values
flags The selected bits from the current thread signal flags mask.
sig::all Cannot be invoked from an Interrupt Service Routine.
Select the requested bits from the thread current signal mask and return them. If requested, clear the selected bits in the thread signal mask.
If the mask is zero, return the full thread signal mask, without any masking or subsequent clearing.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 679 of file os-thread.cpp.
References os::rtos::thread::sig::all, os::rtos::flags::mode::clear, os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_err, os::trace::printf(), os::trace::ret, and sig_mask_.
     {
       os_assert_err(!scheduler::in_handler_mode (), thread::sig::all);
       trace::printf ("%s(0x%X) @%p %s\n", __func__, mask, this, name ());
       interrupts::Critical_section cs; // ----- Critical section -----
       if (mask == 0)
         {
           // Return the entire mask.
           return sig_mask_;
         }
       thread::sigset_t ret = sig_mask_ & mask;
       if ((mode & flags::mode::clear) != 0)
         {
           // Clear the selected bits; leave the rest untouched.
           sig_mask_ &= ~mask;
         }
       // Return the selected bits.
       return ret;
     }
result_t os::rtos::Thread::sig_raise (thread::sigset_t mask, thread::sigset_t * oflags)
Raise thread signal flags.
Parameters
[in] mask The OR-ed flags to raise.
[out] oflags Optional pointer where to store the previous flags; may be nullptr.
Return values
result::ok The flags were raised.
EINVAL The mask is zero.
EPERM Cannot be invoked from an Interrupt Service Routine.
Set more bits in the thread current signal flags mask. Use OR at bit-mask level. Wake-up the thread to evaluate the signal flagss.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 647 of file os-thread.cpp.
References os::rtos::Named_object::name(), os::rtos::result::ok, os_assert_err, os::trace::printf(), sig_mask_, and wakeup().
     {
       os_assert_err(mask != 0, EINVAL);
       trace::printf ("%s(0x%X) @%p %s\n", __func__, mask, this, name ());
       interrupts::Critical_section cs; // ----- Critical section -----
       if (oflags != nullptr)
         {
           *oflags = sig_mask_;
         }
       sig_mask_ |= mask;
       wakeup ();
       return result::ok;
     }
result_t os::rtos::Thread::sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) protected
If the mode::all bit is set, the function expects all given flags to be raised; otherwise, if the mode::any bit is set, the function expects any single flag to be raised.
If the expected signal flags are raised, the function returns instantly.
Otherwise suspend the execution of the current thread until all/any specified signal flags are raised.
When the parameter mask is 0, the thread is suspended until any signal flag is raised. In this case, if any signal flags are already raised, the function returns instantly.
If the mode::clear bit is set, the signal flags that are returned are automatically cleared.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 794 of file os-thread.cpp.
References _try_wait(), os::rtos::scheduler::in_handler_mode(), interrupted(), os::rtos::Named_object::name(), os::rtos::Systick_clock::now(), os::rtos::result::ok, os_assert_err, os::trace::printf(), and suspend().
Referenced by os::rtos::this_thread::sig_wait().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(0x%X, %d) @%p %s\n", __func__, mask, mode, this,
                      name ());
       Systick_clock::rep prev = Systick_clock::now ();
       Systick_clock::sleep_rep slept_ticks = 0;
       for (;;)
         {
             {
               interrupts::Critical_section cs; // ----- Critical section -----
               if (_try_wait (mask, oflags, mode) == result::ok)
                 {
                   slept_ticks =
                       (Systick_clock::sleep_rep) (Systick_clock::now () - prev);
                   trace::printf ("%s(0x%X, %d)=%d @%p %s\n", __func__, mask,
                                  mode, slept_ticks, this, name ());
                   return result::ok;
                 }
             }
           suspend ();
           if (interrupted ())
             {
               return EINTR;
             }
         }
       return ENOTRECOVERABLE;
     }
void os::rtos::Thread::suspend (void) protected
Suspend the current thread.
Definition at line 292 of file os-thread.cpp.
References os::rtos::Named_object::name(), os::trace::printf(), and os::driver::usb::device::suspend.
Referenced by join(), sig_wait(), and os::rtos::this_thread::suspend().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       port::Thread::suspend (this);
 #else
       // TODO
 #endif
     }
result_t os::rtos::Thread::timed_sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, systicks_t ticks, flags::mode_t mode) protected
If the mode::all bit is set, the function expects all given flags to be raised; otherwise, if the mode::any bit is set, the function expects any single flag to be raised.
If the expected signal flags are raised, the function returns instantly.
Otherwise suspend the execution of the thread until all/any specified signal flags are raised.
When the parameter mask is 0, the thread is suspended until any event flag is raised. In this case, if any signal flags are already raised, the function returns instantly.
The wait shall be terminated when the specified timeout expires.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Under no circumstance shall the operation fail with a timeout if the signal flags are already raised.
If the mode::clear bit is set, the signal flags that are returned are automatically cleared.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 887 of file os-thread.cpp.
References _try_wait(), os::rtos::scheduler::in_handler_mode(), interrupted(), os::rtos::Named_object::name(), os::rtos::Systick_clock::now(), os::rtos::result::ok, os_assert_err, os::trace::printf(), and os::rtos::Systick_clock::wait().
Referenced by os::rtos::this_thread::timed_sig_wait().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(0x%X, %d, %d) @%p %s\n", __func__, mask, mode, ticks,
                      this, name ());
       if (ticks == 0)
         {
           ticks = 1;
         }
         {
           interrupts::Critical_section cs; // ----- Critical section -----
           if (_try_wait (mask, oflags, mode) == result::ok)
             {
               return result::ok;
             }
         }
       Systick_clock::rep prev = Systick_clock::now ();
       Systick_clock::sleep_rep slept_ticks = 0;
       result_t res = ENOTRECOVERABLE;
       for (;;)
         {
           Systick_clock::wait (ticks - slept_ticks);
           Systick_clock::rep now = Systick_clock::now ();
           slept_ticks += (Systick_clock::sleep_rep) (now - prev);
             {
               interrupts::Critical_section cs; // ----- Critical section -----
               if (_try_wait (mask, oflags, mode) == result::ok)
                 {
                   res = result::ok;
                   break;
                 }
             }
           if (slept_ticks >= ticks)
             {
               res = ETIMEDOUT;
               break;
             }
           if (interrupted ())
             {
               res = EINTR;
               break;
             }
           prev = now;
         }
 #if 1
       trace::printf ("%s(0x%X, %d, %d)=%d @%p %s\n", __func__, mask, mode,
                      ticks, slept_ticks, this, name ());
 #endif
       return res;
     }
result_t os::rtos::Thread::try_sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) protected
If the mode::all bit is set, the function expects all given flags to be raised; otherwise, if the mode::any bit is set, the function expects any single flag to be raised.
The function does not blocks, if the expected signal flags are not raised, but returns EGAIN.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 841 of file os-thread.cpp.
References _try_wait(), os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_err, and os::trace::printf().
Referenced by os::rtos::this_thread::try_sig_wait().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(0x%X, %d) @%p %s\n", __func__, mask, mode, this,
                      name ());
       interrupts::Critical_section cs; // ----- Critical section -----
       return _try_wait (mask, oflags, mode);
     }
os_thread_user_storage_t * os::rtos::Thread::user_storage (void) inline
Get user storage.
Returns
The address of the thread user storage.
The user storage is a custom structure defined in os-app-config.h, which is added to each and every thread storage. Applications can store here any data.
Inspired by (actually a generalisation of) µC-OS III task user registers and FreeRTOS thread local storage, which proved useful when implementing CMSIS+ over FreeRTOS.
Definition at line 2704 of file os.h.
     {
       return &user_storage_;
     }
void os::rtos::Thread::wakeup (void)
Wake-up the thread.
Note
Can be invoked from Interrupt Service Routines.
Internal, no POSIX equivalent.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 314 of file os-thread.cpp.
References os::rtos::Named_object::name(), os::rtos::result::ok, os::trace::printf(), and wakeup_reason_.
Referenced by exit(), kill(), and sig_raise().
     {
       trace::printf ("%s() @%p %s\n", __func__, this, name ());
       wakeup_reason_ = result::ok;
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
       port::Thread::wakeup (this);
 #else
       // TODO
 #endif
     }
Friends And Related Function Documentation
void this_thread::exit (void * exit_ptr) friend
result_t this_thread::sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) friend
void this_thread::suspend (void) friend
result_t this_thread::timed_sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, systicks_t ticks, flags::mode_t mode) friend
result_t this_thread::try_sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) friend
Member Data Documentation
thread::func_t os::rtos::Thread::func_ protected
Definition at line 831 of file os.h.
Referenced by _invoke_with_exit(), and Thread().
thread::func_args_t os::rtos::Thread::func_args_ protected
Definition at line 832 of file os.h.
Referenced by _invoke_with_exit(), and Thread().
void* os::rtos::Thread::func_result_ protected
Definition at line 833 of file os.h.
Referenced by exit(), join(), and kill().
Thread* os::rtos::Thread::joiner_ protected
Definition at line 841 of file os.h.
Referenced by exit(), join(), kill(), and Thread().
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
thread::priority_t os::rtos::Thread::prio_ protected
Definition at line 845 of file os.h.
Referenced by sched_prio(), and Thread().
thread::state_t os::rtos::Thread::sched_state_ protected
Definition at line 844 of file os.h.
Referenced by _destroy(), exit(), join(), kill(), and Thread().
thread::sigset_t os::rtos::Thread::sig_mask_ protected
Definition at line 850 of file os.h.
Referenced by _try_wait(), sig_clear(), sig_get(), sig_raise(), and Thread().
void* os::rtos::Thread::stack_addr_ protected
Definition at line 830 of file os.h.
Referenced by Thread().
std::size_t os::rtos::Thread::stack_size_bytes_ protected
Definition at line 843 of file os.h.
Referenced by Thread().
os_thread_user_storage_t os::rtos::Thread::user_storage_ protected
Definition at line 852 of file os.h.
result_t os::rtos::Thread::wakeup_reason_ protected
Definition at line 847 of file os.h.
Referenced by wakeup().
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-thread.cpp