CMSIS++ Reference: os::rtos::Condition_variable Class Reference
os::rtos::Condition_variable Class Reference
#include <os.h>
Inherits os::rtos::Named_object.
Public Member Functions
Condition_variable ()
Create a condition variable.
Condition_variable (const condvar::Attributes &attr)
Condition_variable (const Condition_variable &)=delete
Condition_variable (Condition_variable &&)=delete
Condition_variable & operator= (const Condition_variable &)=delete
Condition_variable & operator= (Condition_variable &&)=delete
~Condition_variable ()
Delete a condition variable.
bool operator== (const Condition_variable &rhs) const
Compare condition variables.
result_t signal (void)
Signal a condition.
result_t broadcast (void)
Broadcast a condition.
result_t wait (Mutex &mutex)
Wait on a condition.
result_t timed_wait (Mutex &mutex, systicks_t ticks)
Timed wait on a condition.
const char * name (void) const
Protected Attributes
const char *const name_
Detailed Description
Definition at line 1453 of file os.h.
Constructor & Destructor Documentation
os::rtos::Condition_variable::Condition_variable ()
Create a condition variable.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 56 of file os-condvar.cpp.
References os::rtos::condvar::initializer.
                                             :
         Condition_variable
           { condvar::initializer }
     {
       ;
     }
os::rtos::Condition_variable::Condition_variable (const condvar::Attributes & attr)
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 68 of file os-condvar.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::Named_object::name(), os_assert_throw, and os::trace::printf().
                                                                          :
         Named_object
           { attr.name () }
     {
       os_assert_throw(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
     }
os::rtos::Condition_variable::Condition_variable (const Condition_variable &) delete
os::rtos::Condition_variable::Condition_variable (Condition_variable &&) delete
os::rtos::Condition_variable::~Condition_variable ()
Delete a condition variable.
It shall be safe to destroy an initialised condition variable upon which no threads are currently blocked. Attempting to destroy a condition variable upon which other threads are currently blocked results in undefined behaviour.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 86 of file os-condvar.cpp.
References os::trace::printf().
     {
       trace::printf ("%s() @%p \n", __func__, this);
       // TODO
     }
Member Function Documentation
result_t os::rtos::Condition_variable::broadcast (void)
Broadcast a condition.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Unblock all threads currently blocked on the specified condition variable.
If more than one thread is blocked on a condition variable, the scheduling policy shall determine the order in which threads are unblocked.
When each thread unblocked as a result of a Condition_variable::broadcast() returns from its call to Condition_variable::wait() or Condition_variable::timed_wait(), the thread shall own the mutex with which it called Condition_variable::wait() or Condition_variable::timed_wait(). The thread(s) that are unblocked shall contend for the mutex according to the scheduling policy (if applicable), and as if each had called Mutex::lock().
Condition_variable::broadcast() may be called by a thread whether or not it currently owns the mutex that threads calling Condition_variable::wait() or Condition_variable::timed_wait() have associated with the condition variable during their waits; however, if predictable scheduling behaviour is required, then that mutex shall be locked by the thread calling Condition_variable::broadcast().
The Condition_variable::broadcast() function shall have no effect if there are no threads currently blocked on this condition variable.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 165 of file os-condvar.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
       // TODO
       return result::ok;
     }
const char * os::rtos::Named_object::name (void) const inline inherited
Definition at line 2531 of file os.h.
Referenced by os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Thread::cancel(), Condition_variable(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), os::rtos::Memory_pool::free(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), and os::rtos::Semaphore::~Semaphore().
     {
       return name_;
     }
Condition_variable& os::rtos::Condition_variable::operator= (const Condition_variable &) delete
Condition_variable& os::rtos::Condition_variable::operator= (Condition_variable &&) delete
bool os::rtos::Condition_variable::operator== (const Condition_variable & rhs) const inline
Compare condition variables.
Return values
true The given condition variable is the same as this condition variable.
false The condition variables are different.
Identical condition variables should have the same memory address.
Definition at line 2805 of file os.h.
     {
       return this == &rhs;
     }
result_t os::rtos::Condition_variable::signal (void)
Signal a condition.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Unblock at least one of the threads that are blocked on the specified condition variable.
When each thread unblocked as a result of a Condition_variable::signal() returns from its call to Condition_variable::wait() or Condition_variable::timedwait(), the thread shall own the mutex with which it called Condition_variable::wait() or Condition_variable::timed_wait(). The thread(s) that are unblocked shall contend for the mutex according to the scheduling policy (if applicable), and as if each had called Mutex::lock().
Condition_variable::signal() may be called by a thread whether or not it currently owns the mutex that threads calling Condition_variable::wait() or Condition_variable::timed_wait() have associated with the condition variable during their waits; however, if predictable scheduling behavior is required, then that mutex shall be locked by the thread calling Condition_variable::broadcast().
The Condition_variable::signal() function shall have no effect if there are no threads currently blocked on this condition variable.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 122 of file os-condvar.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
       // TODO
       return result::ok;
     }
result_t os::rtos::Condition_variable::timed_wait (Mutex & mutex, systicks_t ticks)
Timed wait on a condition.
Parameters
[in] mutex Reference to the associated mutex.
[in] ticks Ticks to wait.
Return values
EPERM Cannot be invoked from an Interrupt Service Routine.
result::ok. Block on a condition variable. The application shall ensure that this function is called with mutex locked by the calling thread; otherwise, an error (for ERRORCHECK and robust mutexes) or undefined behaviour (for other mutexes) results.
TODO: add more.
The timeout shall expire after the number of time units (that is when the value of that clock equals or exceeds (now()+duration). The resolution of the timeout shall be the resolution of the clock on which it is based (the SysTick clock for CMSIS).
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 214 of file os-condvar.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s(%d_ticks) @%p \n", __func__, ticks, this);
       // TODO
       return result::ok;
     }
result_t os::rtos::Condition_variable::wait (Mutex & mutex)
Wait on a condition.
Parameters
[in] mutex Reference to the associated mutex.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Block on a condition variable. The application shall ensure that this function is called with mutex locked by the calling thread; otherwise, an error (for PTHREAD_MUTEX_ERRORCHECK and robust mutexes) or undefined behaviour (for other mutexes) results.
TODO: add more.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 187 of file os-condvar.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, os_assert_err, and os::trace::printf().
     {
       os_assert_err(!scheduler::in_handler_mode (), EPERM);
       trace::printf ("%s() @%p \n", __func__, this);
       // TODO
       return result::ok;
     }
Member Data Documentation
const char* const os::rtos::Named_object::name_ protected inherited
Definition at line 529 of file os.h.
The documentation for this class was generated from the following files:
include/cmsis-plus/rtos/os.h
src/cmsis-plus/rtos/os-condvar.cpp