CMSIS++ Reference: include/cmsis-plus/legacy/cmsis_os.h File Reference
cmsis_os.h File Reference
#include <cmsis-plus/rtos/os-c-decls.h>
#include <stdint.h>
#include <stddef.h>
Classes
struct os_thread_def
Thread Definition structure contains startup information of a thread.
struct os_timer_def
Timer Definition structure contains timer parameters.
struct os_mutex_def
Mutex Definition structure contains setup information for a mutex.
struct os_semaphore_def
Semaphore Definition structure contains setup information for a semaphore.
struct os_pool_def
Definition structure for memory block allocation.
struct os_messageQ_def
Definition structure for message queue.
struct os_mailQ_def
Definition structure for mail queue.
struct osEvent
Event structure contains detailed information about an event.
Macros
#define osCMSIS 0x00010002
API version (main [31:16] .sub [15:0])
#define osCMSIS_KERNEL 0x00010000
RTOS identification and version (main [31:16] .sub [15:0])
#define osKernelSystemId "CMSIS++ V1.00"
RTOS identification string.
#define osFeature_MainThread 0
main thread 1=main can be thread, 0=not available
#define osFeature_Pool 1
Memory Pools: 1=available, 0=not available.
#define osFeature_MailQ 1
Mail Queues: 1=available, 0=not available.
#define osFeature_MessageQ 1
Message Queues: 1=available, 0=not available.
#define osFeature_Signals 8
maximum number of Signal Flags available per thread
#define osFeature_Semaphore 30
maximum count for osSemaphoreCreate function
#define osFeature_Wait 1
osWait function: 1=available, 0=not available
#define osFeature_SysTick 1
osKernelSysTick functions: 1=available, 0=not available
#define osWaitForever 0xFFFFFFFF
Timeout value.
#define osKernelSysTickFrequency (1000)
The RTOS kernel system timer frequency.
#define osKernelSysTickMicroSec(microsec) (((uint64_t)microsec * (osKernelSysTickFrequency)) / 1000000)
Convert a microseconds value to ticks.
#define osThreadDef(name, priority, instances, stacksz)
Create a Thread Definition.
#define osThread(name) &os_thread_def_##name
Access a Thread definition.
#define osTimerDef(name, function)
Define timer.
#define osTimer(name) &os_timer_def_##name
Access the timer.
#define osMutexDef(name)
Define a Mutex.
#define osMutex(name) &os_mutex_def_##name
Access a mutex.
#define osSemaphoreDef(name)
Define a Semaphore object.
#define osSemaphore(name) &os_semaphore_def_##name
Access a Semaphore definition.
#define osPoolDef(name, items, type)
Define a Memory Pool.
#define osPool(name) &os_pool_def_##name
Access a Memory Pool definition.
#define osMessageQDef(name, items, type)
Create a Message Queue Definition.
#define osMessageQ(name) &os_messageQ_def_##name
Access a Message Queue.
#define osMailQDef(name, items, type)
Create a mail queue definition.
#define osMailQ(name) &os_mailQ_def_##name
Access a mail queue definition.
Typedefs
typedef void(* os_pthread) (void const *argument)
Entry point of a thread.
typedef void(* os_ptimer) (void const *argument)
Entry point of a timer call back function.
typedef os_thread_t osThread
typedef os_thread_attr_t osThreadAttr
typedef os_timer_t osTimer
typedef os_timer_attr_t osTimerAttr
typedef os_mutex_t osMutex
typedef os_mutex_attr_t osMutexAttr
typedef os_semaphore_t osSemaphore
typedef os_semaphore_attr_t osSemaphoreAttr
typedef os_mempool_t osPool
typedef os_mempool_attr_t osPoolAttr
typedef os_mqueue_t osMessageQ
typedef os_mqueue_attr_t osMessageQAttr
typedef os_mail_queue_t osMailQ
typedef osThread * osThreadId
Thread ID identifies the thread (pointer to a thread control block).
typedef osTimer * osTimerId
Timer ID identifies the timer (pointer to a timer control block).
typedef osMutex * osMutexId
Mutex ID identifies the mutex (pointer to a mutex control block).
typedef osSemaphore * osSemaphoreId
Semaphore ID identifies the semaphore (pointer to a semaphore control block).
typedef osPool * osPoolId
Pool ID identifies the memory pool (pointer to a memory pool control block).
typedef osMessageQ * osMessageQId
Message ID identifies the message queue (pointer to a message queue control block).
typedef osMailQ * osMailQId
Mail ID identifies the mail queue (pointer to a mail queue control block).
typedef struct os_thread_def osThreadDef_t
Thread Definition structure contains startup information of a thread.
typedef struct os_timer_def osTimerDef_t
Timer Definition structure contains timer parameters.
typedef struct os_mutex_def osMutexDef_t
Mutex Definition structure contains setup information for a mutex.
typedef struct os_semaphore_def osSemaphoreDef_t
Semaphore Definition structure contains setup information for a semaphore.
typedef struct os_pool_def osPoolDef_t
Definition structure for memory block allocation.
typedef struct os_messageQ_def osMessageQDef_t
Definition structure for message queue.
typedef struct os_mailQ_def osMailQDef_t
Definition structure for mail queue.
Enumerations
enum osPriority {
osPriorityIdle = os_priority_idle,
osPriorityLow = os_priority_low,
osPriorityBelowNormal = os_priority_below_normal,
osPriorityNormal = os_priority_normal,
osPriorityAboveNormal = os_priority_above_normal,
osPriorityHigh = os_priority_high,
osPriorityRealtime = os_priority_realtime,
osPriorityError = os_priority_error
}
enum osStatus {
osOK = 0,
osEventSignal = 0x08,
osEventMessage = 0x10,
osEventMail = 0x20,
osEventTimeout = 0x40,
osErrorParameter = 0x80,
osErrorResource = 0x81,
osErrorTimeoutResource = 0xC1,
osErrorISR = 0x82,
osErrorISRRecursive = 0x83,
osErrorPriority = 0x84,
osErrorNoMemory = 0x85,
osErrorValue = 0x86,
osErrorOS = 0xFF,
os_status_reserved = 0x7FFFFFFF
}
Status code values returned by CMSIS-RTOS functions.
enum os_timer_type {
osTimerOnce = os_timer_once,
osTimerPeriodic = os_timer_periodic
}
Timer type value for the timer definition.
Functions
osStatus osKernelInitialize (void)
Initialize the RTOS.
osStatus osKernelStart (void)
int32_t osKernelRunning (void)
Check if the RTOS scheduler is started.
uint32_t osKernelSysTick (void)
Get the system timer counter.
osThreadId osThreadCreate (const osThreadDef_t *thread_def, void *argument)
Create a thread.
osThreadId osThreadGetId (void)
Get the current thread.
osStatus osThreadTerminate (osThreadId thread_id)
Terminate a thread.
osStatus osThreadYield (void)
Yield control.
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
Change thread priority.
osPriority osThreadGetPriority (osThreadId thread_id)
Get thread priority.
osStatus osDelay (uint32_t millisec)
Time Delay.
osEvent osWait (uint32_t millisec)
Wait for Signal, Message, Mail, or Timeout.
osTimerId osTimerCreate (const osTimerDef_t *timer_def, os_timer_type type, void *argument)
Create a timer.
osStatus osTimerStart (osTimerId timer_id, uint32_t millisec)
Start the timer.
osStatus osTimerStop (osTimerId timer_id)
Stop the timer.
osStatus osTimerDelete (osTimerId timer_id)
Delete the timer.
int32_t osSignalSet (osThreadId thread_id, int32_t signals)
Set signal flags.
int32_t osSignalClear (osThreadId thread_id, int32_t signals)
Clear the specified Signal Flags of an active thread.
osEvent osSignalWait (int32_t signals, uint32_t millisec)
Wait for one or more Signal Flags to become signaled for the current RUNNING thread.
osMutexId osMutexCreate (const osMutexDef_t *mutex_def)
Create a mutex.
osStatus osMutexWait (osMutexId mutex_id, uint32_t millisec)
Wait for mutex.
osStatus osMutexRelease (osMutexId mutex_id)
Release the mutex.
osStatus osMutexDelete (osMutexId mutex_id)
Delete the mutex.
osSemaphoreId osSemaphoreCreate (const osSemaphoreDef_t *semaphore_def, int32_t count)
Create a semaphore.
int32_t osSemaphoreWait (osSemaphoreId semaphore_id, uint32_t millisec)
Wait until a Semaphore token becomes available.
osStatus osSemaphoreRelease (osSemaphoreId semaphore_id)
Release the semaphore.
osStatus osSemaphoreDelete (osSemaphoreId semaphore_id)
Delete the semaphore.
osPoolId osPoolCreate (const osPoolDef_t *pool_def)
Create a memory pool.
void * osPoolAlloc (osPoolId pool_id)
Allocate a memory block.
void * osPoolCAlloc (osPoolId pool_id)
Allocate and clear a memory block.
osStatus osPoolFree (osPoolId pool_id, void *block)
Free a memory block.
osMessageQId osMessageCreate (const osMessageQDef_t *queue_def, osThreadId thread_id)
Create a message queue.
osStatus osMessagePut (osMessageQId queue_id, uint32_t info, uint32_t millisec)
Put a message to a queue.
osEvent osMessageGet (osMessageQId queue_id, uint32_t millisec)
Get a message or Wait for a Message from a Queue.
osMailQId osMailCreate (const osMailQDef_t *queue_def, osThreadId thread_id)
Create a mail queue.
void * osMailAlloc (osMailQId queue_id, uint32_t millisec)
Allocate a memory block from a mail.
void * osMailCAlloc (osMailQId queue_id, uint32_t millisec)
Allocate and clear a memory block from a mail.
osStatus osMailPut (osMailQId queue_id, void *mail)
Put a mail to a queue.
osEvent osMailGet (osMailQId queue_id, uint32_t millisec)
Get a mail from a queue.
osStatus osMailFree (osMailQId queue_id, void *mail)
Free a memory block from a mail.
Macro Definition Documentation
#define osCMSIS 0x00010002
API version (main [31:16] .sub [15:0])
Note
MUST REMAIN UNCHANGED: osCMSIS identifies the CMSIS-RTOS API version.
Definition at line 98 of file cmsis_os.h.
#define osCMSIS_KERNEL 0x00010000
RTOS identification and version (main [31:16] .sub [15:0])
Note
CAN BE CHANGED: osCMSIS_KERNEL identifies the underlying RTOS kernel and version number.
Definition at line 101 of file cmsis_os.h.
#define osFeature_MailQ 1
Mail Queues: 1=available, 0=not available.
Definition at line 109 of file cmsis_os.h.
#define osFeature_MainThread 0
main thread 1=main can be thread, 0=not available
Note
MUST REMAIN UNCHANGED: osFeature_xxx shall be consistent in every CMSIS-RTOS.
Definition at line 107 of file cmsis_os.h.
#define osFeature_MessageQ 1
Message Queues: 1=available, 0=not available.
Definition at line 110 of file cmsis_os.h.
#define osFeature_Pool 1
Memory Pools: 1=available, 0=not available.
Definition at line 108 of file cmsis_os.h.
#define osFeature_Semaphore 30
maximum count for osSemaphoreCreate function
Definition at line 112 of file cmsis_os.h.
Referenced by osMutexDelete().
#define osFeature_Signals 8
maximum number of Signal Flags available per thread
Definition at line 111 of file cmsis_os.h.
#define osFeature_SysTick 1
osKernelSysTick functions: 1=available, 0=not available
Definition at line 114 of file cmsis_os.h.
#define osFeature_Wait 1
osWait function: 1=available, 0=not available
Definition at line 113 of file cmsis_os.h.
#define osKernelSystemId "CMSIS++ V1.00"
RTOS identification string.
Note
MUST REMAIN UNCHANGED: osKernelSystemId shall be consistent in every CMSIS-RTOS.
Definition at line 104 of file cmsis_os.h.
#define osKernelSysTickFrequency (1000)
The RTOS kernel system timer frequency.
Specifies the frequency of the Kernel SysTick timer in Hz. The value is typically use to scale a time value and is for example used in osKernelSysTickMicroSec.
Note
Reflects the system timer setting and is typically defined in a configuration file.
Definition at line 428 of file cmsis_os.h.
#define osKernelSysTickMicroSec (microsec) (((uint64_t)microsec * (osKernelSysTickFrequency)) / 1000000)
Convert a microseconds value to ticks.
Allows to scale a microsecond value to the frequency of the Kernel SysTick timer. This macro is typically used to check for short timeouts in polling loops.
Parameters
microsec time value in microseconds.
Returns
time value normalized to the osKernelSysTickFrequency.
Definition at line 441 of file cmsis_os.h.
#define osMailQ (name) &os_mailQ_def_##name
Access a mail queue definition.
Parameters
name name of the queue.
Note
CAN BE CHANGED: The parameter to osMailQ shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 1134 of file cmsis_os.h.
#define osMailQDef (name, items, type)
Value:
struct { \
    osMailQ data; \
    type pool[items]; \
    void* queue[items]; \
} os_mailQ_##name; \
const osMailQDef_t os_mailQ_def_##name = { \
    #name, \
    (items), \
    sizeof (type), \
    sizeof (void*), \
    os_mailQ_##name.pool, \
    sizeof(os_mailQ_##name.pool), \
    os_mailQ_##name.queue, \
    sizeof(os_mailQ_##name.queue), \
    &os_mailQ_##name.data \
}
Create a mail queue definition.
Parameters
name name of the queue.
queue_sz maximum number of messages in queue.
type data type of a single message element.
Note
CAN BE CHANGED: The parameter to osMailQDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 1108 of file cmsis_os.h.
#define osMessageQ (name) &os_messageQ_def_##name
Access a Message Queue.
Parameters
name name of the queue.
Access to the message queue definition for the function osMessageCreate.
Note
CAN BE CHANGED: The parameter to osMessageQ shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 1044 of file cmsis_os.h.
#define osMessageQDef (name, items, type)
Value:
struct { \
    osMessageQ data; \
    void* queue[items]; \
} os_messageQ_##name; \
const osMessageQDef_t os_messageQ_def_##name = { \
    #name, \
    (items), \
    sizeof (void*), \
    os_messageQ_##name.queue, \
    sizeof(os_messageQ_##name.queue), \
    &os_messageQ_##name.data \
}
Create a Message Queue Definition.
Parameters
name name of the queue.
queue_sz maximum number of messages in the queue.
type data type of a single message element (for debugger).
Note
CAN BE CHANGED: The parameter to osMessageQDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 1019 of file cmsis_os.h.
#define osMutex (name) &os_mutex_def_##name
Access a mutex.
Parameters
name name of the mutex object.
Provides osMutexCreate access to the mutex object definition.
Note
CAN BE CHANGED: The parameter to osMutex shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 766 of file cmsis_os.h.
#define osMutexDef (name)
Value:
osMutex os_mutex_data_##name; \
const osMutexDef_t os_mutex_def_##name = \
{ \
    #name, \
    &os_mutex_data_##name \
}
Define a Mutex.
Parameters
name name of the mutex object.
Define a mutex object that is referenced by osMutex.
Note
CAN BE CHANGED: The parameter to osMutexDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 747 of file cmsis_os.h.
#define osPool (name) &os_pool_def_##name
Access a Memory Pool definition.
Parameters
name name of the memory pool.
Note
CAN BE CHANGED: The parameter to osPool shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 952 of file cmsis_os.h.
#define osPoolDef (name, items, type)
Value:
struct { \
    osPool data; \
    type pool[items]; \
} os_pool_##name; \
const osPoolDef_t os_pool_def_##name = \
{ \
    #name, \
    (items), \
    sizeof(type), \
    os_pool_##name.pool, \
    sizeof(os_pool_##name.pool), \
    &os_pool_##name.data \
}
Define a Memory Pool.
Parameters
name name of the memory pool.
no maximum number of blocks (objects) in the memory pool.
type data type of a single block (object).
Note
CAN BE CHANGED: The parameter to osPoolDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 929 of file cmsis_os.h.
#define osSemaphore (name) &os_semaphore_def_##name
Access a Semaphore definition.
Parameters
name name of the semaphore object.
Note
CAN BE CHANGED: The parameter to osSemaphore shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 856 of file cmsis_os.h.
#define osSemaphoreDef (name)
Value:
osSemaphore os_semaphore_data_##name; \
const osSemaphoreDef_t os_semaphore_def_##name = \
{ \
    #name, \
    &os_semaphore_data_##name \
}
Define a Semaphore object.
Parameters
name name of the semaphore object.
Note
CAN BE CHANGED: The parameter to osSemaphoreDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 839 of file cmsis_os.h.
#define osThread (name) &os_thread_def_##name
Access a Thread definition.
Parameters
name name of the thread definition object.
Access to the thread definition for the function osThreadCreate.
Note
CAN BE CHANGED: The parameter to osThread shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 493 of file cmsis_os.h.
#define osThreadDef (name, priority, instances, stacksz)
Value:
struct { \
    uint64_t stack[(instances)*((stacksz+sizeof(uint64_t)-1)/sizeof(uint64_t))]; \
    osThread data[instances]; \
} os_thread_##name; \
const osThreadDef_t os_thread_def_##name = \
{ \
    #name, \
    (os_pthread)(name), \
    (priority), \
    (instances), \
    (stacksz), \
    &os_thread_##name.data[0], \
    &os_thread_##name.stack[0] \
}
Create a Thread Definition.
Parameters
name name of the thread function.
priority initial priority of the thread function.
instances number of possible thread instances.
stacksz stack size (in bytes) requirements for the thread function.
Define the attributes of a thread functions that can be created by the function osThreadCreate using osThread.
Note
CAN BE CHANGED: The parameters to osThreadDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 466 of file cmsis_os.h.
#define osTimer (name) &os_timer_def_##name
Access the timer.
Parameters
name name of the timer object.
Provide access to the timer definition for the function osTimerCreate.
Note
CAN BE CHANGED: The parameter to osTimer shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 638 of file cmsis_os.h.
#define osTimerDef (name, function)
Value:
struct { \
    osTimer data; \
} os_timer_##name; \
const osTimerDef_t os_timer_def_##name = \
{ \
    #name, \
    (os_ptimer)(function), \
    &os_timer_##name.data \
}
Define timer.
Parameters
name name of the timer object.
function name of the timer call back function.
Define the attributes of a timer object.
Note
CAN BE CHANGED: The parameter to osTimerDef shall be consistent but the macro body is implementation specific in every CMSIS-RTOS.
Definition at line 616 of file cmsis_os.h.
#define osWaitForever 0xFFFFFFFF
Timeout value.
Note
The names MUST REMAIN UNCHANGED: osWaitForever shall be consistent in every CMSIS-RTOS.wait forever timeout value
Definition at line 147 of file cmsis_os.h.
Referenced by osMutexDelete(), osMutexWait(), and osSignalWait().
Typedef Documentation
typedef void(* os_pthread) (void const *argument)
Entry point of a thread.
Note
MUST REMAIN UNCHANGED: os_pthread shall be consistent in every CMSIS-RTOS.
Definition at line 187 of file cmsis_os.h.
typedef void(* os_ptimer) (void const *argument)
Entry point of a timer call back function.
Note
MUST REMAIN UNCHANGED: os_ptimer shall be consistent in every CMSIS-RTOS.
Definition at line 194 of file cmsis_os.h.
typedef os_mail_queue_t osMailQ
Definition at line 215 of file cmsis_os.h.
typedef struct os_mailQ_def osMailQDef_t
Definition structure for mail queue.
Note
CAN BE CHANGED: os_mailQ_def is implementation specific in every CMSIS-RTOS.
typedef osMailQ* osMailQId
Mail ID identifies the mail queue (pointer to a mail queue control block).
Note
CAN BE CHANGED: os_mailQ_cb is implementation specific in every CMSIS-RTOS.
Definition at line 257 of file cmsis_os.h.
typedef os_mqueue_t osMessageQ
Definition at line 212 of file cmsis_os.h.
typedef os_mqueue_attr_t osMessageQAttr
Definition at line 213 of file cmsis_os.h.
typedef struct os_messageQ_def osMessageQDef_t
Definition structure for message queue.
Note
CAN BE CHANGED: os_messageQ_def is implementation specific in every CMSIS-RTOS.
typedef osMessageQ* osMessageQId
Message ID identifies the message queue (pointer to a message queue control block).
Note
CAN BE CHANGED: os_messageQ_cb is implementation specific in every CMSIS-RTOS.
Definition at line 251 of file cmsis_os.h.
typedef os_mutex_t osMutex
Definition at line 203 of file cmsis_os.h.
typedef os_mutex_attr_t osMutexAttr
Definition at line 204 of file cmsis_os.h.
typedef struct os_mutex_def osMutexDef_t
Mutex Definition structure contains setup information for a mutex.
Note
CAN BE CHANGED: os_mutex_def is implementation specific in every CMSIS-RTOS.
typedef osMutex* osMutexId
Mutex ID identifies the mutex (pointer to a mutex control block).
Note
CAN BE CHANGED: os_mutex_cb is implementation specific in every CMSIS-RTOS.
Definition at line 233 of file cmsis_os.h.
typedef os_mempool_t osPool
Definition at line 209 of file cmsis_os.h.
typedef os_mempool_attr_t osPoolAttr
Definition at line 210 of file cmsis_os.h.
typedef struct os_pool_def osPoolDef_t
Definition structure for memory block allocation.
Note
CAN BE CHANGED: os_pool_def is implementation specific in every CMSIS-RTOS.
typedef osPool* osPoolId
Pool ID identifies the memory pool (pointer to a memory pool control block).
Note
CAN BE CHANGED: os_pool_cb is implementation specific in every CMSIS-RTOS.
Definition at line 245 of file cmsis_os.h.
typedef os_semaphore_t osSemaphore
Definition at line 206 of file cmsis_os.h.
typedef os_semaphore_attr_t osSemaphoreAttr
Definition at line 207 of file cmsis_os.h.
typedef struct os_semaphore_def osSemaphoreDef_t
Semaphore Definition structure contains setup information for a semaphore.
Note
CAN BE CHANGED: os_semaphore_def is implementation specific in every CMSIS-RTOS.
typedef osSemaphore* osSemaphoreId
Semaphore ID identifies the semaphore (pointer to a semaphore control block).
Note
CAN BE CHANGED: os_semaphore_cb is implementation specific in every CMSIS-RTOS.
Definition at line 239 of file cmsis_os.h.
typedef os_thread_t osThread
Definition at line 197 of file cmsis_os.h.
typedef os_thread_attr_t osThreadAttr
Definition at line 198 of file cmsis_os.h.
typedef struct os_thread_def osThreadDef_t
Thread Definition structure contains startup information of a thread.
Note
CAN BE CHANGED: os_thread_def is implementation specific in every CMSIS-RTOS.
typedef osThread* osThreadId
Thread ID identifies the thread (pointer to a thread control block).
Note
CAN BE CHANGED: os_thread_cb is implementation specific in every CMSIS-RTOS.
Definition at line 221 of file cmsis_os.h.
typedef os_timer_t osTimer
Definition at line 200 of file cmsis_os.h.
typedef os_timer_attr_t osTimerAttr
Definition at line 201 of file cmsis_os.h.
typedef struct os_timer_def osTimerDef_t
Timer Definition structure contains timer parameters.
Note
CAN BE CHANGED: os_timer_def is implementation specific in every CMSIS-RTOS.
typedef osTimer* osTimerId
Timer ID identifies the timer (pointer to a timer control block).
Note
CAN BE CHANGED: os_timer_cb is implementation specific in every CMSIS-RTOS.
Definition at line 227 of file cmsis_os.h.
Enumeration Type Documentation
enum os_timer_type
Timer type value for the timer definition.
Note
The names MUST REMAIN UNCHANGED: os_timer_type shall be consistent in every CMSIS-RTOS.
Enumerator
osTimerOnce
one-shot timer
osTimerPeriodic
repeating timer
Definition at line 176 of file cmsis_os.h.
   {
     osTimerOnce = os_timer_once,
     osTimerPeriodic = os_timer_periodic
   } os_timer_type;
enum osPriority
Priority used for thread control.
Note
The names MUST REMAIN UNCHANGED: osPriority shall be consistent in every CMSIS-RTOS.
Enumerator
osPriorityIdle
priority: idle (lowest)
osPriorityLow
priority: low
osPriorityBelowNormal
priority: below normal
osPriorityNormal
priority: normal (default)
osPriorityAboveNormal
priority: above normal
osPriorityHigh
priority: high
osPriorityRealtime
priority: realtime (highest)
osPriorityError
system cannot determine priority or thread has illegal priority
Definition at line 131 of file cmsis_os.h.
   {
     osPriorityIdle = os_priority_idle,
     osPriorityLow = os_priority_low,
     osPriorityBelowNormal = os_priority_below_normal,
     osPriorityNormal = os_priority_normal,
     osPriorityAboveNormal = os_priority_above_normal,
     osPriorityHigh = os_priority_high,
     osPriorityRealtime = os_priority_realtime,
     osPriorityError = os_priority_error
   } osPriority;
enum osStatus
Status code values returned by CMSIS-RTOS functions.
Note
The names MUST REMAIN UNCHANGED: osStatus shall be consistent in every CMSIS-RTOS.
Enumerator
osOK
function completed; no error or event occurred.
osEventSignal
function completed; signal event occurred.
osEventMessage
function completed; message event occurred.
osEventMail
function completed; mail event occurred.
osEventTimeout
function completed; timeout occurred.
osErrorParameter
parameter error: a mandatory parameter was missing or specified an incorrect object.
osErrorResource
resource not available: a specified resource was not available.
osErrorTimeoutResource
resource not available within given time: a specified resource was not available within the timeout period.
osErrorISR
not allowed in ISR context: the function cannot be called from interrupt service routines.
osErrorISRRecursive
function called multiple times from ISR with same object.
osErrorPriority
system cannot determine priority or thread has illegal priority.
osErrorNoMemory
system is out of memory: it was impossible to allocate or reserve memory for the operation.
osErrorValue
value of a parameter is out of range.
osErrorOS
unspecified RTOS error: run-time error but no other error message fits.
os_status_reserved
prevent from enum down-size compiler optimization.
Definition at line 153 of file cmsis_os.h.
   {
     osOK = 0,
     osEventSignal = 0x08,
     osEventMessage = 0x10,
     osEventMail = 0x20,
     osEventTimeout = 0x40,
     osErrorParameter = 0x80,
     osErrorResource = 0x81,
     osErrorTimeoutResource = 0xC1,
     osErrorISR = 0x82,
     osErrorISRRecursive = 0x83,
     osErrorPriority = 0x84,
     osErrorNoMemory = 0x85,
     osErrorValue = 0x86,
     osErrorOS = 0xFF,
     os_status_reserved = 0x7FFFFFFF
   } osStatus;
Function Documentation
osStatus osDelay (uint32_t millisec)
Time Delay.
Parameters
[in] millisec time delay value.
Return values
osEventTimeout The time delay is executed.
osErrorISR osDelay() cannot be called from interrupt service routines.
Wait for a specified time period in millisec.
The millisec value specifies the number of timer ticks and is therefore an upper bound. The exact time delay depends on the actual time elapsed since the last timer tick.
For a value of 1, the system waits until the next timer tick occurs. That means that the actual time delay may be up to one timer tick less.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1094 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), osErrorISR, osErrorOS, osEventTimeout, osWait(), os::rtos::Systick_clock::sleep_for(), osEvent::status, os::rtos::Systick_clock::ticks_cast(), and os::rtos::Systick_clock::wait().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   result_t res = Systick_clock::sleep_for (
       Systick_clock::ticks_cast (millisec * 1000u));
   if (res == ETIMEDOUT)
     {
       return osEventTimeout;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osKernelInitialize (void)
Initialize the RTOS.
Return values
osOK The RTOS kernel was initialised.
osErrorISR The function cannot be invoked from Interrupt Service Routines.
Note
MUST REMAIN UNCHANGED: osKernelInitialize shall be consistent in every CMSIS-RTOS.
Initialise of the RTOS Kernel to allow peripheral setup and creation of other RTOS objects with the functions:
osThreadCreate : Create a thread function.
osTimerCreate : Define attributes of the timer callback function.
osMutexCreate : Define and initialise a mutex.
osSemaphoreCreate : Define and initialise a semaphore.
osPoolCreate : Define and initialise a fix-size memory pool.
osMessageCreate : Define and initialise a message queue.
osMailCreate : Define and initialise a mail queue with fix-size memory blocks.
The RTOS scheduler does not start thread switching until the function osKernelStart is called.
Note
In case that the RTOS Kernel starts thread execution with the function main the function osKernelInitialize stops thread switching. This allows you to setup the system to a defined state before thread switching is resumed with osKernelStart.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 780 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::scheduler::initialize(), osErrorISR, and osOK.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   scheduler::initialize ();
   return osOK;
 }
int32_t osKernelRunning (void)
Check if the RTOS scheduler is started.
Return values
0 The RTOS is not started.
1 The RTOS is started.
Identifies if the RTOS scheduler is started. For systems with the option to start the main function as a thread this allows you to identify that the RTOS scheduler is already running.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 816 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::now(), osKernelSysTick(), and os::rtos::scheduler::started().
 {
   return scheduler::started () ? 1 : 0;
 }
osStatus osKernelStart (void)
Start the RTOS scheduler.
Return values
osOK The RTOS scheduler has been successfully started.
osErrorISR The function cannot be invoked from Interrupt Service Routines.
Note
MUST REMAIN UNCHANGED: osKernelStart shall be consistent in every CMSIS-RTOS.
Start the RTOS Kernel and begin thread switching.
Note
When the CMSIS-RTOS starts thread execution with the function main this function resumes thread switching. The main thread will continue executing after osKernelStart.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 802 of file os-c-wrapper.cpp.
References os::rtos::scheduler::start().
 {
   return static_cast<osStatus> (scheduler::start ());
 }
uint32_t osKernelSysTick (void)
Get the system timer counter.
Returns
The RTOS kernel system timer as a 32-bits value.
Note
MUST REMAIN UNCHANGED: osKernelSysTick shall be consistent in every CMSIS-RTOS.
Referenced by osKernelRunning().
void* osMailAlloc (osMailQId queue_id, uint32_t millisec)
Allocate a memory block from a mail.
Parameters
[in] queue_id mail queue ID obtained with osMailCreate.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
pointer to memory block that can be filled with mail or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMailAlloc shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
void* osMailCAlloc (osMailQId queue_id, uint32_t millisec)
Allocate and clear a memory block from a mail.
Parameters
[in] queue_id mail queue ID obtained with osMailCreate.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
pointer to memory block that can be filled with mail or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMailCAlloc shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osMailQId osMailCreate (const osMailQDef_t * queue_def, osThreadId thread_id)
Create a mail queue.
Parameters
[in] queue_def reference to the mail queue definition obtain with osMailQ.
[in] thread_id thread ID (obtained by osThreadCreate or osThreadGetId) or NULL.
Returns
mail queue ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMailCreate shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osStatus osMailFree (osMailQId queue_id, void * mail)
Free a memory block from a mail.
Parameters
[in] queue_id mail queue ID obtained with osMailCreate.
[in] mail pointer to the memory block that was obtained with osMailGet.
Return values
osOK The mail block is released.
osErrorValue Mail block does not belong to the mail queue pool.
osErrorParameter The value to the parameter queue_id is incorrect.
Note
MUST REMAIN UNCHANGED: osMailFree shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osEvent osMailGet (osMailQId queue_id, uint32_t millisec)
Get a mail from a queue.
Parameters
[in] queue_id mail queue ID obtained with osMailCreate.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Return values
osOK No mail is available in the queue and no timeout was specified.
osEventTimeout No mail has arrived during the given timeout period.
osEventMail Mail received, value.p contains the pointer to mail content.
osErrorParameter A parameter is invalid or outside of a permitted range.
Note
MUST REMAIN UNCHANGED: osMailGet shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osStatus osMailPut (osMailQId queue_id, void * mail)
Put a mail to a queue.
Parameters
[in] queue_id mail queue ID obtained with osMailCreate.
[in] mail memory block previously allocated with osMailAlloc or osMailCAlloc.
Return values
osOK The message is put into the queue.
osErrorValue Mail was previously not allocated as memory slot.
osErrorParameter A parameter is invalid or outside of a permitted range.
Note
MUST REMAIN UNCHANGED: osMailPut shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osMessageQId osMessageCreate (const osMessageQDef_t * queue_def, osThreadId thread_id)
Create a message queue.
Parameters
[in] queue_def queue definition referenced with osMessageQ.
[in] thread_id thread ID (obtained by osThreadCreate or osThreadGetId) or NULL.
Returns
message queue ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMessageCreate shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osEvent osMessageGet (osMessageQId queue_id, uint32_t millisec)
Get a message or Wait for a Message from a Queue.
Parameters
[in] queue_id message queue ID obtained with osMessageCreate.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Return values
osOK No message is available in the queue and no timeout was specified.
osEventTimeout No message has arrived during the given timeout period.
osEventMessage Message received, value.p contains the pointer to message.
osErrorParameter A parameter is invalid or outside of a permitted range.
Note
MUST REMAIN UNCHANGED: osMessageGet shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osStatus osMessagePut (osMessageQId queue_id, uint32_t info, uint32_t millisec)
Put a message to a queue.
Parameters
[in] queue_id message queue ID obtained with osMessageCreate.
[in] info message information.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Return values
osOK The message is put into the queue.
osErrorResource no memory in the queue was available.
osErrorTimeoutResource no memory in the queue was available during the given time limit.
osErrorParameter a parameter is invalid or outside of a permitted range. status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMessagePut shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osMutexId osMutexCreate (const osMutexDef_t * mutex_def)
Create a mutex.
Parameters
[in] mutex_def mutex definition referenced with osMutex.
Returns
mutex ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMutexCreate shall be consistent in every CMSIS-RTOS.
Create and initialize a mutex object.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1443 of file os-c-wrapper.cpp.
References os_mutex_def::data, os::rtos::scheduler::in_handler_mode(), and os::rtos::mutex::recursive_initializer.
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   if (mutex_def == nullptr)
     {
       return nullptr;
     }
   return reinterpret_cast<osMutexId> (new ((void*) mutex_def->data) Mutex (
       mutex::recursive_initializer));
 }
osStatus osMutexDelete (osMutexId mutex_id)
Delete the mutex.
Parameters
[in] mutex_id mutex ID obtained by osMutexCreate.
Return values
osOK The mutex object has been deleted.
osErrorISR osMutexDelete cannot be called from interrupt service routines.
osErrorResource All tokens have already been released.
osErrorParameter The parameter mutex_id is incorrect.
Note
MUST REMAIN UNCHANGED: osMutexDelete shall be consistent in every CMSIS-RTOS.
Delete a mutex object. The function releases internal memory obtained for mutex handling. After this call the mutex_id is no longer valid and cannot be used. The mutex may be created again using the function osMutexCreate.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1586 of file os-c-wrapper.cpp.
References __attribute__(), attr, os::rtos::Memory_pool::block_size(), os::rtos::Memory_pool::capacity(), os_semaphore_def::data, os_pool_def::data, os_messageQ_def::data, os_mailQ_def::data, os::estd::free(), os::rtos::scheduler::in_handler_mode(), os_pool_def::item_sz, os_messageQ_def::item_sz, os_pool_def::items, os_messageQ_def::items, os_mailQ_def::items, os_semaphore_def::name, os_pool_def::name, os_messageQ_def::name, os_mailQ_def::name, os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osErrorTimeoutResource, osErrorValue, osEventMail, osEventMessage, osEventTimeout, osFeature_Semaphore, osMailAlloc(), osMailCAlloc(), osMailCreate(), osMailFree(), osMailGet(), osMailPut(), osMessageCreate(), osMessageGet(), osMessagePut(), osOK, osPoolAlloc(), osPoolCAlloc(), osPoolCreate(), osPoolFree(), osSemaphoreCreate(), osSemaphoreDelete(), osSemaphoreRelease(), osSemaphoreWait(), osWaitForever, osEvent::p, os_pool_def::pool, os_mailQ_def::pool, os_mail_queue_s::pool, os::rtos::Memory_pool::pool(), os_mailQ_def::pool_item_sz, os_messageQ_def::queue, os_mailQ_def::queue, os_mail_queue_s::queue, os_mailQ_def::queue_item_sz, os_messageQ_def::queue_sz, os_mailQ_def::queue_sz, os::trace::ret, osEvent::status, os::rtos::Systick_clock::ticks_cast(), value, and osEvent::value.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (mutex_id == nullptr)
     {
       return osErrorParameter;
     }
   (reinterpret_cast<Mutex&> (*mutex_id)).~Mutex ();
   return osOK;
 }
osStatus osMutexRelease (osMutexId mutex_id)
Release the mutex.
Parameters
[in] mutex_id mutex ID obtained by osMutexCreate.
Return values
osOK The mutex has been correctly released.
osErrorResource The mutex was not obtained before.
osErrorParameter The parameter mutex_id is incorrect.
osErrorISR osMutexRelease cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osMutexRelease shall be consistent in every CMSIS-RTOS.
Release a Mutex that was obtained with osMutexWait. Other threads that currently wait for the same mutex will be now put into the state READY.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1547 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osOK, and os::rtos::scheduler::unlock().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (mutex_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t res;
   res = (reinterpret_cast<Mutex&> (*mutex_id)).unlock ();
   if (res == result::ok)
     {
       return osOK;
     }
   else if (res == EPERM)
     {
       return osErrorResource;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osMutexWait (osMutexId mutex_id, uint32_t millisec)
Wait for mutex.
Parameters
[in] mutex_id mutex ID obtained by osMutexCreate.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Return values
osOK The mutex has been obtain.
osErrorTimeoutResource the mutex could not be obtained in the given time.
osErrorResource The mutex could not be obtained when no timeout was specified.
osErrorParameter The parameter mutex_id is incorrect.
osErrorISR osMutexWait cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osMutexWait shall be consistent in every CMSIS-RTOS.
Wait until a Mutex becomes available. If no other thread has obtained the Mutex, the function instantly returns and blocks the mutex object.
The argument millisec specifies how long the system waits for a mutex. While the system waits the thread that is calling this function is put into the state WAITING. The millisec timeout can have the following values:
when millisec is 0, the function returns instantly.
when millisec is set to osWaitForever the function will wait for an infinite time until the mutex becomes available.
all other values specify a time in millisecond for a timeout.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1478 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::scheduler::lock(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osErrorTimeoutResource, osOK, osWaitForever, os::trace::ret, and os::rtos::Systick_clock::ticks_cast().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (mutex_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t ret;
   if (millisec == osWaitForever)
     {
       ret = (reinterpret_cast<Mutex&> (*mutex_id)).lock ();
       // osErrorResource:
     }
   else if (millisec == 0)
     {
       ret = (reinterpret_cast<Mutex&> (*mutex_id)).try_lock ();
     }
   else
     {
       ret = (reinterpret_cast<Mutex&> (*mutex_id)).timed_lock (
           Systick_clock::ticks_cast (millisec * 1000u));
       // osErrorTimeoutResource:
     }
   if (ret == result::ok)
     {
       // osOK: the mutex has been obtained.
       return osOK;
     }
   else if (ret == EAGAIN)
     {
       // The mutex could not be obtained when no timeout was specified.
       // Only for try_lock().
       return osErrorResource;
     }
   else if (ret == ENOTRECOVERABLE)
     {
       // The mutex could not be obtained when no timeout was specified.
       // Only for lock().
       return osErrorResource;
     }
   else if (ret == ETIMEDOUT)
     {
       // The mutex could not be obtained in the given time.
       // Only for timed_lock().
       return osErrorTimeoutResource;
     }
   else
     {
       return osErrorOS;
     }
   return static_cast<osStatus> (ret);
 }
void* osPoolAlloc (osPoolId pool_id)
Allocate a memory block.
Parameters
[in] pool_id memory pool ID obtain referenced with osPoolCreate.
Returns
address of the allocated memory block or NULL in case of no memory available.
Note
MUST REMAIN UNCHANGED: osPoolAlloc shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
void* osPoolCAlloc (osPoolId pool_id)
Allocate and clear a memory block.
Parameters
[in] pool_id memory pool ID obtain referenced with osPoolCreate.
Returns
address of the allocated memory block or NULL in case of no memory available.
Note
MUST REMAIN UNCHANGED: osPoolCAlloc shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osPoolId osPoolCreate (const osPoolDef_t * pool_def)
Create a memory pool.
Parameters
[in] pool_def memory pool definition referenced with osPool.
Returns
memory pool ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osPoolCreate shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osStatus osPoolFree (osPoolId pool_id, void * block)
Free a memory block.
Parameters
[in] pool_id memory pool ID obtain referenced with osPoolCreate.
[in] block address of the allocated memory block that is returned to the memory pool.
Return values
osOK The memory block is released.
osErrorValue The block does not belong to the memory pool.
osErrorParameter A parameter is invalid or outside of a permitted range.
Note
MUST REMAIN UNCHANGED: osPoolFree shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osSemaphoreId osSemaphoreCreate (const osSemaphoreDef_t * semaphore_def, int32_t count)
Create a semaphore.
Parameters
[in] semaphore_def semaphore definition referenced with osSemaphore.
[in] count number of available resources.
Returns
semaphore ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osSemaphoreCreate shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osStatus osSemaphoreDelete (osSemaphoreId semaphore_id)
Delete the semaphore.
Parameters
[in] semaphore_id semaphore object referenced with osSemaphoreCreate.
Return values
osOK The semaphore object has been deleted.
osErrorISR osSemaphoreDelete cannot be called from interrupt service routines.
osErrorResource The semaphore object could not be deleted.
osErrorParameter The parameter semaphore_id is incorrect.
Note
MUST REMAIN UNCHANGED: osSemaphoreDelete shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
osStatus osSemaphoreRelease (osSemaphoreId semaphore_id)
Release the semaphore.
Parameters
[in] semaphore_id semaphore object referenced with osSemaphoreCreate.
Return values
osOK The semaphore has been released.
osErrorResource All tokens have already been released.
osErrorParameter The parameter semaphore_id is incorrect.
Note
MUST REMAIN UNCHANGED: osSemaphoreRelease shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
int32_t osSemaphoreWait (osSemaphoreId semaphore_id, uint32_t millisec)
Wait until a Semaphore token becomes available.
Parameters
[in] semaphore_id semaphore object referenced with osSemaphoreCreate.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Returns
number of available tokens, or -1 in case of incorrect parameters.
Note
MUST REMAIN UNCHANGED: osSemaphoreWait shall be consistent in every CMSIS-RTOS.
Referenced by osMutexDelete().
int32_t osSignalClear (osThreadId thread_id, int32_t signals)
Clear the specified Signal Flags of an active thread.
Parameters
[in] thread_id thread ID obtained by osThreadCreate or osThreadGetId.
[in] signals specifies the signal flags of the thread that shall be cleared.
Returns
previous signal flags of the specified thread or 0x80000000 in case of incorrect parameters or call from ISR.
Note
MUST REMAIN UNCHANGED: osSignalClear shall be consistent in every CMSIS-RTOS.
Clear the signal flags of an active thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1321 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode().
 {
   if (thread_id == nullptr)
     {
       return 0x80000000;
     }
   if (scheduler::in_handler_mode () || (signals == 0))
     {
       return 0x80000000;
     }
   thread::sigset_t sig;
   ((Thread*) (thread_id))->sig_clear (signals, &sig);
   return (int32_t) sig;
 }
int32_t osSignalSet (osThreadId thread_id, int32_t signals)
Set signal flags.
Parameters
[in] thread_id thread ID obtained by osThreadCreate or osThreadGetId.
[in] signals specifies the signal flags of the thread that should be set.
Returns
previous signal flags of the specified thread or 0x80000000 in case of incorrect parameters.
Note
MUST REMAIN UNCHANGED: osSignalSet shall be consistent in every CMSIS-RTOS.
Set the signal flags of an active thread.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 1297 of file os-c-wrapper.cpp.
 {
   if (thread_id == nullptr)
     {
       return 0x80000000;
     }
   if (signals == (int32_t) 0x80000000)
     {
       return 0x80000000;
     }
   thread::sigset_t osig;
   ((Thread*) (thread_id))->sig_raise ((thread::sigset_t) signals, &osig);
   return (int32_t) osig;
 }
osEvent osSignalWait (int32_t signals, uint32_t millisec)
Wait for one or more Signal Flags to become signaled for the current RUNNING thread.
Parameters
[in] signals wait until all specified signal flags set or 0 for any single signal flag.
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Return values
osOK No signal received when the timeout value millisec was 0.
osEventTimeout Signal not occurred within timeout.
osEventSignal Signal occurred, value.signals contains the signal flags; these signal flags are cleared.
osErrorValue The value signals is outside of the permitted range.
osErrorISR osSignalWait cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osSignalWait shall be consistent in every CMSIS-RTOS.
Suspend the execution of the current RUNNING thread until all specified signal flags with the parameter signals are set. When the parameter signals is 0 the current RUNNING thread is suspended until any signal is set. When these signal flags are already set, the function returns instantly. Otherwise the thread is put into the state WAITING. Signal flags that are reported as event are automatically cleared.
The argument millisec specifies how long the system waits for the specified signal flags. While the system waits the tread calling this function is put into the state WAITING. The timeout value can have the following values:
when millisec is 0, the function returns instantly.
when millisec is set to osWaitForever the function will wait an infinite time until a specified signal is set.
all other values specify a time in millisecond for a timeout.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1365 of file os-c-wrapper.cpp.
References os::rtos::flags::mode::all, os::rtos::flags::mode::clear, os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorValue, osEventSignal, osEventTimeout, osOK, osWaitForever, os::rtos::this_thread::sig_wait(), osEvent::signals, osEvent::status, os::rtos::Systick_clock::ticks_cast(), os::rtos::this_thread::timed_sig_wait(), os::rtos::this_thread::try_sig_wait(), and osEvent::value.
 {
   osEvent event;
   if (scheduler::in_handler_mode ())
     {
       event.status = osErrorISR;
       return event;
     }
   if (signals & 0x80000000)
     {
       event.status = osErrorValue;
       return event;
     }
   result_t res;
   if (millisec == osWaitForever)
     {
       res = this_thread::sig_wait ((thread::sigset_t) signals,
                                    (thread::sigset_t*) &event.value.signals,
                                    flags::mode::all || flags::mode::clear);
     }
   else if (millisec == 0)
     {
       res = this_thread::try_sig_wait ((thread::sigset_t) signals,
                                        (thread::sigset_t*) &event.value.signals,
                                        flags::mode::all || flags::mode::clear);
     }
   else
     {
       res = this_thread::timed_sig_wait (
           (thread::sigset_t) signals, (thread::sigset_t*) &event.value.signals,
           flags::mode::all || flags::mode::clear,
           Systick_clock::ticks_cast (millisec * 1000u));
     }
   if (res == result::ok)
     {
       event.status = osEventSignal;
     }
   else if (res == EAGAIN)
     {
       event.status = osOK; // Only for try_sig_wait().
     }
   else if (res == ETIMEDOUT)
     {
       event.status = osEventTimeout; // Only for timed_sig_wait().
     }
   else if (res == EPERM)
     {
       event.status = osErrorISR;
     }
   else if (res == EINVAL)
     {
       event.status = osErrorValue;
     }
   else
     {
       event.status = osErrorOS;
     }
   return event;
 }
osThreadId osThreadCreate (const osThreadDef_t * thread_def, void * args)
Create a thread.
Parameters
[in] thread_def thread definition referenced with osThread.
[in] argument pointer that is passed to the thread function as start argument.
Returns
thread ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osThreadCreate shall be consistent in every CMSIS-RTOS.
Find a free slot in the array of thread definitions and initialise the thread.
Start the thread function by adding it to the Active Threads list and set it to state READY. The thread function receives the argument pointer as function argument when the function is started. When the priority of the created thread function is higher than the current RUNNING thread, the created thread function starts instantly and becomes the new RUNNING thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 869 of file os-c-wrapper.cpp.
References args, attr, os_thread_def::data, os::trace::if(), os::rtos::scheduler::in_handler_mode(), os_thread_def::instances, os_thread_def::name, osPriorityError, os_thread_def::pthread, os::rtos::Thread::sched_state(), os_thread_def::stack, os_thread_def::stacksize, os::rtos::thread::Attributes::th_priority, os::rtos::thread::Attributes::th_stack_address, os::rtos::thread::Attributes::th_stack_size_bytes, and os_thread_def::tpriority.
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   if (thread_def == nullptr)
     {
       return nullptr;
     }
   thread::Attributes attr
     { thread_def->name };
   attr.th_priority = thread_def->tpriority;
   attr.th_stack_size_bytes = thread_def->stacksize;
   // Creating thread with invalid priority should fail (validator requirement).
   if (thread_def->tpriority >= osPriorityError)
     {
       return nullptr;
     }
   // Find a free slot in the tread definitions array.
   for (uint32_t i = 0; i < thread_def->instances; ++i)
     {
       Thread* th = (Thread*) &thread_def->data[i];
       if (th->sched_state () == thread::state::undefined
           || th->sched_state () == thread::state::terminated
           || th->sched_state () == thread::state::destroyed)
         {
           if (attr.th_stack_size_bytes > 0)
             {
               attr.th_stack_address = &thread_def->stack[(i)
                   * ((thread_def->stacksize + sizeof(uint64_t) - 1)
                       / sizeof(uint64_t))];
             }
           new (th) Thread (attr, (thread::func_t) thread_def->pthread, args);
           // No need to yield here, already done by constructor.
           return reinterpret_cast<osThreadId> (th);
         }
     }
   return nullptr;
 }
osThreadId osThreadGetId (void)
Get the current thread.
Returns
thread ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osThreadGetId shall be consistent in every CMSIS-RTOS.
Get the thread ID of the current running thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 922 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), and os::rtos::this_thread::thread().
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   return reinterpret_cast<osThreadId> (&this_thread::thread ());
 }
osPriority osThreadGetPriority (osThreadId thread_id)
Get thread priority.
Parameters
[in] thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Returns
The current priority value of the thread, or osPriorityError if error.
Note
MUST REMAIN UNCHANGED: osThreadGetPriority shall be consistent in every CMSIS-RTOS.
Get the priority of an active thread. In case of a failure the value osPriorityError is returned.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1059 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), and osPriorityError.
 {
   if (scheduler::in_handler_mode ())
     {
       return osPriorityError;
     }
   if (thread_id == nullptr)
     {
       return osPriorityError;
     }
   // Call C++ accessor.
   thread::priority_t prio =
       (reinterpret_cast<Thread&> (*thread_id)).sched_prio ();
   return static_cast<osPriority> (prio);
 }
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
Change thread priority.
Parameters
[in] thread_id thread ID obtained by osThreadCreate or osThreadGetId.
[in] priority new priority value for the thread function.
Return values
osOK The priority of the specified thread has been successfully changed.
osErrorParameter thread_id is incorrect.
osErrorValue incorrect priority value.
osErrorResource thread_id refers to a thread that is not an active thread.
osErrorISR osThreadSetPriority cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osThreadSetPriority shall be consistent in every CMSIS-RTOS.
Change the priority of a running thread. There is no need for an extra yield after it, if the priorities require, there is an implicit reschedule.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1006 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osErrorValue, osOK, and osPriorityError.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (thread_id == nullptr)
     {
       return osErrorParameter;
     }
   thread::state_t state =
       (reinterpret_cast<Thread&> (*thread_id)).sched_state ();
   if (state == thread::state::undefined || state >= thread::state::destroyed)
     {
       return osErrorResource;
     }
   if (priority < osPriorityIdle || priority >= osPriorityError)
     {
       return osErrorValue;
     }
   // Call C++ mutator.
   thread::priority_t prio = static_cast<thread::priority_t> (priority);
   result_t res = ((reinterpret_cast<Thread&> (*thread_id)).sched_prio (prio));
   // A mandatory yield is needed here, must be done
   // by the implementation.
   if (res == result::ok)
     {
       return osOK;
     }
   else if (res == EINVAL)
     {
       return osErrorValue;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osThreadTerminate (osThreadId thread_id)
Terminate a thread.
Parameters
[in] thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
osOK The specified thread has been successfully terminated.
osErrorParameter thread_id is incorrect.
osErrorResource thread_id refers to a thread that is not an active thread.
osErrorISR osThreadTerminate cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osThreadTerminate shall be consistent in every CMSIS-RTOS.
Remove the thread function from the active thread list. If the thread is currently RUNNING the execution will stop.
Note
In case that osThreadTerminate terminates the currently running task, the function never returns and other threads that are in the READY state are started.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 944 of file os-c-wrapper.cpp.
References os::rtos::this_thread::exit(), os::rtos::scheduler::in_handler_mode(), osErrorISR, osErrorParameter, osErrorResource, osOK, and os::rtos::this_thread::thread().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (thread_id == nullptr)
     {
       return osErrorParameter;
     }
   thread::state_t state =
       (reinterpret_cast<Thread&> (*thread_id)).sched_state ();
   if (state == thread::state::undefined)
     {
       return osErrorResource;
     }
   if ((reinterpret_cast<Thread*> (thread_id)) == &this_thread::thread ())
     {
       this_thread::exit ();
       /* NORETURN */
     }
   else
     {
       (reinterpret_cast<Thread&> (*thread_id)).kill ();
     }
   return osOK;
 }
osStatus osThreadYield (void)
Yield control.
Return values
osOK The function has been correctly executed.
osErrorISR The function cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osThreadYield shall be consistent in every CMSIS-RTOS.
Pass control to the next thread that is in state READY. If there is no other thread in the state READY, the current thread continues execution and no thread switching occurs.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 985 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), osErrorISR, osOK, and os::rtos::this_thread::yield().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   this_thread::yield ();
   return osOK;
 }
osTimerId osTimerCreate (const osTimerDef_t * timer_def, os_timer_type type, void * args)
Create a timer.
Parameters
[in] timer_def timer object referenced with osTimer.
[in] type osTimerOnce for one-shot or osTimerPeriodic for periodic behavior.
[in] argument argument to the timer call back function.
Returns
timer ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osTimerCreate shall be consistent in every CMSIS-RTOS.
Create a one-shot or periodic timer and associate it with a callback function argument. The timer is initially stopped and must be started with osTimerStart().
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1179 of file os-c-wrapper.cpp.
References attr, os_timer_def::data, os::rtos::scheduler::in_handler_mode(), os_timer_def::name, and os_timer_def::ptimer.
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   if (timer_def == nullptr)
     {
       return nullptr;
     }
   timer::Attributes attr
     { timer_def->name };
   attr.tm_type = (timer::type_t) type;
   return reinterpret_cast<osTimerId> (new ((void*) timer_def->data) Timer (
       attr, (timer::func_t) timer_def->ptimer, (timer::func_args_t) args));
 }
osStatus osTimerDelete (osTimerId timer_id)
Delete the timer.
Parameters
[in] timer_id timer ID obtained by osTimerCreate.
Return values
osOK The specified timer has been deleted.
osErrorISR osTimerDelete cannot be called from interrupt service routines.
osErrorParameter timer_id is incorrect.
Note
MUST REMAIN UNCHANGED: osTimerDelete shall be consistent in every CMSIS-RTOS.
Delete the timer object that was created by osTimerCreate.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1271 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), osErrorISR, osErrorParameter, and osOK.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (timer_id == nullptr)
     {
       return osErrorParameter;
     }
   (reinterpret_cast<Timer&> (*timer_id)).~Timer ();
   return osOK;
 }
osStatus osTimerStart (osTimerId timer_id, uint32_t millisec)
Start the timer.
Parameters
[in] timer_id timer ID obtained by osTimerCreate.
[in] millisec time delay value of the timer.
Return values
osOK The specified timer has been started or restarted.
osErrorISR osTimerStart cannot be called from interrupt service routines.
osErrorParameter timer_id is incorrect.
Note
MUST REMAIN UNCHANGED: osTimerStart shall be consistent in every CMSIS-RTOS.
Start or restart the timer.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1206 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osOK, os::rtos::scheduler::start(), and os::rtos::Systick_clock::ticks_cast().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (timer_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t res = (reinterpret_cast<Timer&> (*timer_id)).start (
       Systick_clock::ticks_cast (millisec * 1000u));
   if (res == result::ok)
     {
       return osOK;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osTimerStop (osTimerId timer_id)
Stop the timer.
Parameters
[in] timer_id timer ID obtained by osTimerCreate.
Return values
osOK the specified timer has been stopped.
osErrorISR osTimerStop cannot be called from interrupt service routines.
osErrorParameter timer_id is incorrect.
osErrorResource the timer is not started.
Note
MUST REMAIN UNCHANGED: osTimerStop shall be consistent in every CMSIS-RTOS.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1237 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, and osOK.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (timer_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t res = (reinterpret_cast<Timer&> (*timer_id)).stop ();
   if (res == result::ok)
     {
       return osOK;
     }
   else if (res == EAGAIN)
     {
       return osErrorResource;
     }
   else
     {
       return osErrorOS;
     }
 }
osEvent osWait (uint32_t millisec)
Wait for Signal, Message, Mail, or Timeout.
Parameters
[in] millisec CMSIS_RTOS_TimeOutValue or 0 in case of no time-out.
Return values
osEventSignal A signal event occurred and is returned.
osEventMessage A message event occurred and is returned.
osEventMail A mail event occurred and is returned.
osEventTimeout The time delay is executed.
osErrorISR osWait() cannot be called from interrupt service routines.
Note
MUST REMAIN UNCHANGED: osWait shall be consistent in every CMSIS-RTOS.
Referenced by osDelay().