CMSIS++ Reference: src/cmsis-plus/libcpp/cxx.cpp File Reference
cxx.cpp File Reference
#include <cstdlib>
#include <sys/types.h>
#include <cmsis-plus/diag/trace.h>
Namespaces
__gnu_cxx
Functions
void __gnu_cxx::__attribute__ ((noreturn)) __verbose_terminate_handler()
void __gnu_cxx::__verbose_terminate_handler ()
void __attribute__ ((noreturn)) __cxa_pure_virtual()
void __cxa_pure_virtual ()
Function Documentation
void __attribute__ ((noreturn))
Definition at line 24 of file abort.c.
References trace_printf(), and trace_puts().
Referenced by __attribute__().
 {
   trace_puts ("abort(), exiting...");
   _exit (1);
   /* NOTREACHED */
 }
void __cxa_pure_virtual ()
Definition at line 50 of file cxx.cpp.
References trace_puts().
Referenced by __gnu_cxx::__verbose_terminate_handler().
   {
     // Attempt to use a virtual function before object has been constructed
     trace_puts (__func__);
     abort ();
     /* NOTREACHED */
   }