CMSIS++ Reference: src/cmsis-plus/startup/exception-handlers.c File Reference
exception-handlers.c File Reference
#include <cmsis_device.h>
#include <cmsis-plus/arm/semihosting.h>
#include <cmsis-plus/diag/trace.h>
#include <cmsis-plus/cortexm/exception-handlers.h>
#include <string.h>
Functions
void __attribute__ ((noreturn, weak))
void __attribute__ ((section(".after_vectors"), weak))
Function Documentation
void __attribute__ ((noreturn, weak))
Definition at line 28 of file exception-handlers.c.
References Reset_Handler().
Referenced by __attribute__().
   {
     _start ();
   }
 #else
 // The Release version is optimised to a quick branch to _start.
 void __attribute__ ((section(".after_vectors"),naked))
 Reset_Handler (void)
 {
   asm volatile
   (
       " ldr     r0,=_start \n"
       " bx      r0"
       : /* Outputs */
       : /* Inputs */
       : /* Clobbers */
   );
 }
void __attribute__ ((section(".after_vectors"), weak))
Definition at line 65 of file exception-handlers.c.
References __attribute__(), AngelSWI, HardFault_Handler(), HardFault_Handler_C(), os::trace::if(), ExceptionStackFrame::lr, ExceptionStackFrame::pc, PendSV_Handler(), ExceptionStackFrame::psr, ExceptionStackFrame::r0, ExceptionStackFrame::r1, ExceptionStackFrame::r12, ExceptionStackFrame::r2, ExceptionStackFrame::r3, SEMIHOSTING_ReportException, SEMIHOSTING_SYS_CLOCK, SEMIHOSTING_SYS_CLOSE, SEMIHOSTING_SYS_ELAPSED, SEMIHOSTING_SYS_ERRNO, SEMIHOSTING_SYS_FLEN, SEMIHOSTING_SYS_GET_CMDLINE, SEMIHOSTING_SYS_HEAPINFO, SEMIHOSTING_SYS_ISERROR, SEMIHOSTING_SYS_ISTTY, SEMIHOSTING_SYS_OPEN, SEMIHOSTING_SYS_READ, SEMIHOSTING_SYS_READC, SEMIHOSTING_SYS_REMOVE, SEMIHOSTING_SYS_RENAME, SEMIHOSTING_SYS_SEEK, SEMIHOSTING_SYS_SYSTEM, SEMIHOSTING_SYS_TICKFREQ, SEMIHOSTING_SYS_TIME, SEMIHOSTING_SYS_TMPNAM, SEMIHOSTING_SYS_WRITE, SEMIHOSTING_SYS_WRITE0, SEMIHOSTING_SYS_WRITEC, SVC_Handler(), SysTick_Handler(), trace_printf(), and trace_write().
 {
 #if defined(DEBUG)
   __DEBUG_BKPT();
 #endif
   while (1)
     {
     }
 }