CMSIS++ Reference: src/cmsis-plus/startup/initialize-hardware.c File Reference
initialize-hardware.c File Reference
#include <cmsis_device.h>
Functions
void __initialize_hardware_early (void)
void __initialize_hardware (void)
void __attribute__ ((weak))
Variables
unsigned int __vectors_start
Function Documentation
void __attribute__ ((weak))
Definition at line 44 of file initialize-hardware.c.
References __initialize_hardware(), and __vectors_start.
 {
   // Call the CSMSIS system initialisation routine.
   SystemInit ();
 #if defined(__ARM_ARCH_7M__)
   // Set VTOR to the actual address, provided by the linker script.
   // Override the manual, possibly wrong, SystemInit() setting.
   SCB->VTOR = (uint32_t) (&__vectors_start);
 #endif
   // The current version of SystemInit() leaves the value of the clock
   // in a RAM variable (SystemCoreClock), which will be cleared shortly,
   // so it needs to be recomputed after the RAM initialisations
   // are completed.
 #if defined(OS_INCLUDE_STARTUP_INIT_FP) || (defined (__VFP_FP__) && !defined (__SOFTFP__))
   // Normally FP init is done by SystemInit(). In case this is not done
   // there, it is possible to force its inclusion by defining
   // OS_INCLUDE_STARTUP_INIT_FP.
   // Enable the Cortex-M4 FPU only when -mfloat-abi=hard.
   // Code taken from Section 7.1, Cortex-M4 TRM (DDI0439C)
   // Set bits 20-23 to enable CP10 and CP11 coprocessor
   SCB->CPACR |= (0xF << 20);
 #endif // (__VFP_FP__) && !(__SOFTFP__)
 #if defined(OS_DEBUG_SEMIHOSTING_FAULTS)
   SCB->SHCSR |= SCB_SHCSR_USGFAULTENA_Msk;
 #endif
 }
void __initialize_hardware (void)
Referenced by __attribute__().
void __initialize_hardware_early (void)
Referenced by __attribute__().
Variable Documentation
unsigned int __vectors_start
Referenced by __attribute__().