CMSIS++ Reference: __gnu_cxx Namespace Reference
__gnu_cxx Namespace Reference
Functions
void __attribute__ ((noreturn)) __verbose_terminate_handler()
void __verbose_terminate_handler ()
Function Documentation
void __gnu_cxx::__attribute__ ((noreturn))
Definition at line 24 of file abort.c.
Referenced by __verbose_terminate_handler().
 {
   trace_puts ("abort(), exiting...");
   _exit (1);
   /* NOTREACHED */
 }
void __gnu_cxx::__verbose_terminate_handler ()
Definition at line 34 of file cxx.cpp.
References __attribute__(), __cxa_pure_virtual(), and trace_puts().
   {
     trace_puts (__func__);
     abort ();
     /* NOTREACHED */
   }