CMSIS++ Reference: os::estd Namespace Reference
os::estd Namespace Reference
Namespaces
chrono
this_thread
Functions
void * malloc (std::size_t size) noexcept
void free (void *ptr) noexcept
void notify_all_at_thread_exit (condition_variable &cond, unique_lock< mutex > lk)
void __throw_system_error (int ev, const char *what_arg)
void __throw_cmsis_error (int ev, const char *what_arg)
Function Documentation
void os::estd::__throw_cmsis_error (int ev, const char * what_arg)
Definition at line 105 of file system-error.cpp.
References trace_printf().
     {
 #if defined(__EXCEPTIONS)
       throw std::system_error (
           std::error_code (ev, cmsis_error_category ()), what_arg);
 #else
       trace_printf ("system_error(%d, %s)\n", ev, what_arg);
       std::abort ();
 #endif
     }
void os::estd::__throw_system_error (int ev, const char * what_arg)
Definition at line 93 of file system-error.cpp.
References trace_printf().
     {
 #if defined(__EXCEPTIONS)
       throw std::system_error (
           std::error_code (ev, system_error_category ()), what_arg);
 #else
       trace_printf ("system_error(%d, %s)\n", ev, what_arg);
       std::abort ();
 #endif
     }
void os::estd::free (void * ptr) noexcept
The free() function deallocates the memory allocation pointed to by ptr. If ptr is a NULL pointer, no operation is performed. Currently it calls the C function.
Note
Synchronisation is provided by using a scheduler lock.
Definition at line 58 of file malloc.cpp.
References os::trace::printf().
Referenced by __attribute__(), os_mempool_free(), and osMutexDelete().
     {
       trace::printf ("%s(%d) %p %s\n", __func__, ptr);
         {
           // ----- Begin of critical section ----------------------------------
           scheduler::Critical_section cs;
           return ::free (ptr);
           // ----- End of critical section ------------------------------------
         }
     }
void * os::estd::malloc (std::size_t size) noexcept
The malloc() function allocates size bytes of memory and returns a pointer to the allocated memory. Currently it calls the C function.
Note
Synchronisation is provided by using a scheduler lock.
Definition at line 34 of file malloc.cpp.
References os::trace::printf().
Referenced by __attribute__().
     {
       void* p;
         {
           // ----- Begin of critical section ----------------------------------
           scheduler::Critical_section cs;
           p = ::malloc (size);
           // ----- End of critical section ------------------------------------
         }
       trace::printf ("%s(%d) %p\n", __func__, size, p);
       return p;
     }
void os::estd::notify_all_at_thread_exit (condition_variable & cond, unique_lock< mutex > lk)
Definition at line 73 of file condition-variable.cpp.
     {
       //__thread_local_data()->notify_all_at_thread_exit(&cond, lk.release());
       std::abort (); // Not implemented
     }