CMSIS++ Reference: os::rtos::scheduler Namespace Reference
os::rtos::scheduler Namespace Reference
Classes
class Critical_section
class Lock
Typedefs
using status_t = bool
Functions
result_t initialize (void)
Initialise the RTOS.
result_t start (void)
Start the RTOS scheduler.
bool started (void)
Check if the scheduler was started.
bool locked (void)
Check if the scheduler is locked.
status_t lock (void)
Lock the scheduler.
void unlock (status_t status)
Unlock the scheduler.
bool in_handler_mode (void)
Check if in handler mode.
Variables
status_t is_locked_ = false
bool is_started_ = false
Typedef Documentation
using os::rtos::scheduler::status_t = typedef bool
Definition at line 126 of file os.h.
Function Documentation
bool os::rtos::scheduler::in_handler_mode (void)
Check if in handler mode.
Return values
true Execution is in an exception handler context.
false Execution is in a thread context.
Note
Can be invoked from Interrupt Service Routines (obviously).
Definition at line 68 of file os-core.cpp.
Referenced by os::rtos::Memory_pool::alloc(), os::rtos::Condition_variable::broadcast(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Mutex::consistent(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), initialize(), os::rtos::Realtime_clock::initialize(), os::rtos::Thread::join(), os::rtos::Thread::kill(), lock(), os::rtos::Mutex::lock(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), osDelay(), osKernelInitialize(), osMutexCreate(), osMutexDelete(), osMutexRelease(), osMutexWait(), osSignalClear(), osSignalWait(), osThreadCreate(), osThreadGetId(), osThreadGetPriority(), osThreadSetPriority(), osThreadTerminate(), osThreadYield(), osTimerCreate(), osTimerDelete(), osTimerStart(), osTimerStop(), os::rtos::Mutex::prio_ceiling(), os::rtos::Message_queue::receive(), os::rtos::Semaphore::reset(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_wait(), os::rtos::Condition_variable::signal(), os::rtos::Systick_clock::sleep_for(), os::rtos::Realtime_clock::sleep_for(), start(), os::rtos::Timer::start(), os::rtos::Timer::stop(), os::rtos::this_thread::thread(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Mutex::timed_lock(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Condition_variable::timed_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Event_flags::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Mutex::try_lock(), os::rtos::Thread::try_sig_wait(), unlock(), os::rtos::Mutex::unlock(), os::rtos::Systick_clock::wait(), os::rtos::Condition_variable::wait(), os::rtos::Semaphore::wait(), os::rtos::Event_flags::wait(), and os::rtos::this_thread::yield().
       {
         return port::scheduler::in_handler_mode ();
       }
os::rtos::scheduler::initialize (void)
Initialise the RTOS.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Create all RTOS internal objects and be ready to run.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 54 of file os-core.cpp.
References in_handler_mode(), os::trace::initialize(), os_assert_err, and os::trace::printf().
Referenced by os::trace::__attribute__(), __attribute__(), initialize(), os_sched_initialize(), and osKernelInitialize().
       {
         os_assert_err(!scheduler::in_handler_mode (), EPERM);
         trace::printf ("%s() \n", __func__);
         return port::scheduler::initialize ();
       }
status_t os::rtos::scheduler::lock (void)
Lock the scheduler.
Returns
The previous status of the scheduler.
Lock the scheduler (prevent it for doing thread switches) and return the previous status, to be restored by unlock().
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 101 of file os-core.cpp.
References in_handler_mode(), is_locked_, and os_assert_throw.
Referenced by os::rtos::scheduler::Lock::lock(), os::rtos::Mutex::lock(), os_mutex_lock(), os_sched_lock(), osMutexWait(), and os::rtos::scheduler::Lock::try_lock().
       {
         os_assert_throw(!scheduler::in_handler_mode (), EPERM);
         port::scheduler::lock ();
         status_t tmp = is_locked_;
         is_locked_ = true;
         return tmp;
       }
bool os::rtos::scheduler::locked (void) inline
Check if the scheduler is locked.
Return values
true The scheduler is locked.
false The scheduler is running (not locked).
Check if the scheduler is locked on the current task or is switching tasks from the ready list.
Definition at line 2453 of file os.h.
References is_locked_.
Referenced by os_sched_is_locked().
       {
         return is_locked_;
       }
os::rtos::scheduler::start (void)
Start the RTOS scheduler.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
The scheduler cannot be stopped, will run forever, but thread switching can be locked/unlocked.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 81 of file os-core.cpp.
References in_handler_mode(), os_assert_err, and os::trace::printf().
Referenced by os_sched_start(), os_timer_start(), osKernelStart(), osTimerStart(), os::rtos::Timer::start(), os::rtos::Memory_pool::timed_alloc(), and os::rtos::Event_flags::timed_wait().
       {
         os_assert_err(!scheduler::in_handler_mode (), EPERM);
         trace::printf ("%s() \n", __func__);
         is_started_ = true;
         is_locked_ = false;
         return port::scheduler::start ();
       }
bool os::rtos::scheduler::started (void) inline
Check if the scheduler was started.
Return values
true The scheduler was started.
false The scheduler was not started.
Check if the scheduler was started, i.e. if scheduler::start() was called.
Definition at line 2442 of file os.h.
References is_started_.
Referenced by os_rtc_handler(), os_sched_is_started(), os_systick_handler(), osKernelRunning(), and os::rtos::this_thread::yield().
       {
         return is_started_;
       }
void os::rtos::scheduler::unlock (status_t status)
Unlock the scheduler.
Parameters
[in] status The new status of the scheduler.
Actually restore the scheduler status based on the given parameter, usually returned by a lock(). This allows for embedded critical sections to preserve the locked status until the outer one completes and invokes unlock().
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 123 of file os-core.cpp.
References in_handler_mode(), os_assert_throw, and os::rtos::this_thread::thread().
Referenced by os_mutex_unlock(), os_sched_unlock(), osMutexRelease(), os::rtos::scheduler::Lock::unlock(), os::rtos::Mutex::unlock(), and os::rtos::scheduler::Critical_section::~Critical_section().
       {
         os_assert_throw(!scheduler::in_handler_mode (), EPERM);
         port::scheduler::unlock (status);
         is_locked_ = status;
       }
Variable Documentation
status_t os::rtos::scheduler::is_locked_ = false
Definition at line 45 of file os-core.cpp.
Referenced by lock(), and locked().
status_t os::rtos::scheduler::is_started_ = false
Definition at line 44 of file os-core.cpp.
Referenced by started().