CMSIS++ Reference: os::trace Namespace Reference
os::trace Namespace Reference
Functions
void initialize (void)
Initialise the RTOS.
ssize_t write (const void *buf, std::size_t nbyte)
int printf (const char *format,...)
int vprintf (const char *format, std::va_list args)
int puts (const char *s)
int putchar (int c)
void dump_args (int argc, char *argv[])
void __attribute__ ((always_inline)) dbg_bkpt(void)
void __attribute__ ((weak)) write(const void *buf __attribute__((unused))
Write the given number of bytes to the trace output channel.
int va_start (args, format)
va_end (args)
if (ret > 0)
for (int i=0;i< argc;++i)
printf ("]);\n")
Variables
ssize_t std::size_t nbyte
int ret = vprintf (format, args)
int std::va_list args
void char * argv []
Function Documentation
void os::trace::__attribute__ ((weak)) const
Write the given number of bytes to the trace output channel.
Returns
The number of characters actually written, or -1 if error.
Definition at line 39 of file trace.cpp.
References __attribute__(), nbyte, and write().
     {
       ;
     }
void os::trace::__attribute__ ((always_inline)) inline
Definition at line 107 of file trace.h.
References __initialize_trace(), argc, args, argv, dump_args(), initialize(), nbyte, printf(), putchar(), puts(), trace_dump_args(), trace_printf(), trace_putchar(), trace_puts(), trace_vprintf(), trace_write(), vprintf(), and write().
Referenced by __attribute__(), __attribute__(), and if().
     {
       trace_dbg_bkpt ();
     }
void os::trace::dump_args (int argc, char * argv[])
Referenced by __attribute__(), if(), and trace_dump_args().
os::trace::for ()
Definition at line 124 of file trace.cpp.
References printf().
         {
           if (i != 0)
             {
               printf (", ");
             }
           printf ("\"%s\"", argv[i]);
         }
os::trace::if (ret , 0)
Definition at line 80 of file trace.cpp.
References __attribute__(), argc, argv, dump_args(), putchar(), puts(), ret, and write().
Referenced by __attribute__(), and osThreadCreate().
         {
           // Transfer the buffer to the device.
           ret = (int) write (buf, (size_t) ret);
         }
void os::trace::initialize (void)
Initialise the RTOS.
Return values
result::ok.
EPERM Cannot be invoked from an Interrupt Service Routine.
Create all RTOS internal objects and be ready to run.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 54 of file os-core.cpp.
References os::rtos::scheduler::in_handler_mode(), initialize(), os_assert_err, and printf().
Referenced by __attribute__(), __attribute__(), os::rtos::scheduler::initialize(), os_sched_initialize(), and osKernelInitialize().
       {
         os_assert_err(!scheduler::in_handler_mode (), EPERM);
         trace::printf ("%s() \n", __func__);
         return port::scheduler::initialize ();
       }
int os::trace::printf (const char * format, ...)
Referenced by __attribute__(), os::rtos::Thread::_destroy(), os::rtos::Thread::_invoke_with_exit(), os::rtos::Memory_pool::alloc(), os::rtos::Condition_variable::broadcast(), os::rtos::Thread::cancel(), os::rtos::Condition_variable::Condition_variable(), os::rtos::Mutex::consistent(), os::rtos::Thread::detach(), os::rtos::Event_flags::Event_flags(), os::rtos::Thread::exit(), for(), os::estd::free(), os::rtos::Memory_pool::free(), os::rtos::scheduler::initialize(), os::rtos::Thread::join(), os::rtos::Thread::kill(), os::rtos::Mutex::lock(), os::estd::malloc(), os::rtos::Memory_pool::Memory_pool(), os::rtos::Message_queue::Message_queue(), os::rtos::Mutex::Mutex(), os::rtos::Semaphore::post(), os::rtos::Mutex::prio_ceiling(), os::rtos::Message_queue::receive(), os::rtos::Memory_pool::reset(), os::rtos::Message_queue::reset(), os::rtos::Thread::sched_prio(), os::rtos::Semaphore::Semaphore(), os::rtos::Message_queue::send(), os::rtos::Thread::sig_clear(), os::rtos::Thread::sig_get(), os::rtos::Thread::sig_raise(), os::rtos::Thread::sig_wait(), os::rtos::Condition_variable::signal(), os::rtos::Systick_clock::sleep_for(), os::rtos::Realtime_clock::sleep_for(), os::rtos::scheduler::start(), os::rtos::Timer::start(), os::rtos::Timer::stop(), os::rtos::Thread::suspend(), os::rtos::Thread::Thread(), os::rtos::Memory_pool::timed_alloc(), os::rtos::Mutex::timed_lock(), os::rtos::Message_queue::timed_receive(), os::rtos::Message_queue::timed_send(), os::rtos::Thread::timed_sig_wait(), os::rtos::Condition_variable::timed_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Timer::Timer(), os::rtos::Memory_pool::try_alloc(), os::rtos::Mutex::try_lock(), os::rtos::Message_queue::try_receive(), os::rtos::Message_queue::try_send(), os::rtos::Thread::try_sig_wait(), os::rtos::Semaphore::try_wait(), os::rtos::Mutex::unlock(), os::rtos::Systick_clock::wait(), os::rtos::Condition_variable::wait(), os::rtos::Semaphore::wait(), os::rtos::Thread::wakeup(), os::rtos::Condition_variable::~Condition_variable(), os::rtos::Event_flags::~Event_flags(), os::rtos::Memory_pool::~Memory_pool(), os::rtos::Message_queue::~Message_queue(), os::rtos::Mutex::~Mutex(), os::rtos::Semaphore::~Semaphore(), and os::rtos::Timer::~Timer().
os::trace::printf ("])
int os::trace::putchar (int c)
Referenced by __attribute__(), if(), and trace_putchar().
int os::trace::puts (const char * s)
Referenced by __attribute__(), if(), and trace_puts().
os::trace::va_end (args)
Referenced by trace_printf().
int os::trace::va_start (args , format)
Referenced by trace_printf().
int os::trace::vprintf (const char * format, std::va_list args)
Referenced by __attribute__(), trace_printf(), and trace_vprintf().
ssize_t os::trace::write (const void * buf, std::size_t nbyte)
Referenced by __attribute__(), and if().
Variable Documentation
int std::va_list os::trace::args
Initial value:
{
      char buf[ (200) ]
Definition at line 71 of file trace.cpp.
Referenced by __attribute__(), and trace_printf().
void char* os::trace::argv[]
Initial value:
{
      printf ("main(argc=%d, argv=[", argc)
Definition at line 122 of file trace.cpp.
Referenced by __attribute__(), and if().
ssize_t std::size_t os::trace::nbyte
Initial value:
{
      return (ssize_t) nbyte
Definition at line 51 of file trace.cpp.
Referenced by __attribute__().
return os::trace::ret = vprintf (format, args)
Definition at line 63 of file trace.cpp.
Referenced by os::rtos::Event_flags::get(), if(), osMutexDelete(), osMutexWait(), os::rtos::Thread::sig_get(), and trace_printf().