CMSIS++ Reference: os::rtos::this_thread Namespace Reference
os::rtos::this_thread Namespace Reference
Functions
Thread & thread (void)
Get current thread.
void yield (void)
Yield CPU.
void suspend (void)
Suspend the current thread.
void exit (void *exit_ptr=nullptr)
Terminate the current thread.
bool is_timeout (void)
Check if wake-up due to timeout.
result_t sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
Wait for signal flags.
result_t try_sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode)
Try to wait for signal flags.
result_t timed_sig_wait (thread::sigset_t mask, thread::sigset_t *oflags, flags::mode_t mode, systicks_t ticks)
Timed wait for signal flags.
Function Documentation
void os::rtos::this_thread::exit (void * exit_ptr = nullptr) inline
Terminate the current thread.
Returns
-
Definition at line 2641 of file os.h.
References os::rtos::Thread::exit(), and thread().
Referenced by os::rtos::interrupts::Critical_section::exit(), os::rtos::thread::main_trampoline(), os_this_thread_exit(), and osThreadTerminate().
       {
         return this_thread::thread ().exit (exit_ptr);
       }
bool os::rtos::this_thread::is_timeout (void)
Check if wake-up due to timeout.
Return values
true The previous sleep returned after the entire duration.
false The previous sleep returned due to an event.
result_t os::rtos::this_thread::sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) inline
Wait for signal flags.
Parameters
[in] mask The expected flags (OR-ed bit-mask); may be zero.
[out] oflags Pointer where to store the current flags; may be nullptr.
[in] mode Mode bits to select if either all or any flags are expected, and if the flags should be cleared.
Return values
result::ok All expected flags are raised.
EPERM Cannot be invoked from an Interrupt Service Routine.
EINVAL The mask is outside of the permitted range.
EINTR The operation was interrupted.
ENOTRECOVERABLE Wait failed.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 2610 of file os.h.
References os::rtos::Thread::sig_wait(), and thread().
Referenced by os_this_thread_sig_wait(), and osSignalWait().
       {
         return this_thread::thread ().sig_wait (mask, oflags, mode);
       }
void os::rtos::this_thread::suspend (void) inline
Suspend the current thread.
Remove the current thread from the ready list and pass control to the next thread that is in READY state.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 2599 of file os.h.
References os::rtos::Thread::suspend(), and thread().
Referenced by os::rtos::Memory_pool::alloc(), os_this_thread_suspend(), and os::rtos::Event_flags::wait().
       {
         this_thread::thread ().suspend ();
       }
Thread & os::rtos::this_thread::thread (void)
Get current thread.
Returns
Reference to the current running thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 65 of file os-thread.cpp.
References os::rtos::scheduler::in_handler_mode(), and os_assert_throw.
Referenced by os::rtos::Memory_pool::alloc(), exit(), os_thread_create(), osThreadGetId(), osThreadTerminate(), sig_wait(), os::rtos::Systick_clock::sleep_for(), suspend(), os::rtos::Memory_pool::timed_alloc(), timed_sig_wait(), os::rtos::Semaphore::timed_wait(), os::rtos::Event_flags::timed_wait(), try_sig_wait(), os::rtos::scheduler::unlock(), os::rtos::Systick_clock::wait(), os::rtos::Semaphore::wait(), os::rtos::Event_flags::wait(), and yield().
       {
         os_assert_throw(!scheduler::in_handler_mode (), EPERM);
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
         return port::this_thread::thread ();
 #else
         // TODO
 #endif
       }
result_t os::rtos::this_thread::timed_sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode, systicks_t ticks) inline
Timed wait for signal flags.
Parameters
[in] mask The expected flags (OR-ed bit-mask); may be zero.
[out] oflags Pointer where to store the current flags; may be nullptr.
[in] mode Mode bits to select if either all or any flags are expected, and if the flags should be cleared.
ticks The number of ticks to wait.
Return values
result::ok All expected flags are raised.
EPERM Cannot be invoked from an Interrupt Service Routine.
ETIMEDOUT The expected condition did not occur during the entire timeout duration.
EINVAL The mask is outside of the permitted range.
EINTR The operation was interrupted.
ENOTRECOVERABLE Wait failed.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 2634 of file os.h.
References thread(), and os::rtos::Thread::timed_sig_wait().
Referenced by os_this_thread_timed_sig_wait(), and osSignalWait().
       {
         return this_thread::thread ().timed_sig_wait (mask, oflags, mode, ticks);
       }
result_t os::rtos::this_thread::try_sig_wait (thread::sigset_t mask, thread::sigset_t * oflags, flags::mode_t mode) inline
Try to wait for signal flags.
Parameters
[in] mask The expected flags (OR-ed bit-mask); may be zero.
[out] oflags Pointer where to store the current flags; may be nullptr.
[in] mode Mode bits to select if either all or any flags are expected, and if the flags should be cleared.
Return values
result::ok All expected flags are raised.
EINVAL The mask is outside of the permitted range.
EAGAIN The expected condition did not occur.
ENOTRECOVERABLE Wait failed.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 2622 of file os.h.
References thread(), and os::rtos::Thread::try_sig_wait().
Referenced by os_this_thread_try_sig_wait(), and osSignalWait().
       {
         return this_thread::thread ().try_sig_wait (mask, oflags, mode);
       }
void os::rtos::this_thread::yield (void)
Yield CPU.
Pass control to next thread that is in READY state.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 87 of file os-thread.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::thread::initializer, os_assert_throw, os::rtos::scheduler::started(), and thread().
Referenced by osThreadYield(), os::rtos::Thread::sched_prio(), os::rtos::Thread::Thread(), and os::rtos::Semaphore::wait().
       {
         os_assert_throw(!scheduler::in_handler_mode (), EPERM);
         if (!scheduler::started ())
           {
             return;
           }
 #if defined(OS_INCLUDE_PORT_RTOS_THREAD)
         return port::this_thread::yield ();
 #else
         // TODO
 #endif
       }