CMSIS++ Reference: src/cmsis-plus/rtos/os-clocks.cpp File Reference
os-clocks.cpp File Reference
#include <cmsis-plus/rtos/os.h>
#include <cmsis-plus/diag/trace.h>
#include <cmsis-plus/rtos/port/os-decls.h>
#include <cmsis-plus/rtos/port/os-inlines.h>
#include <cassert>
#include <cerrno>
#include <cstdlib>
Namespaces
os
os::rtos
Functions
void os_systick_handler (void)
void os_rtc_handler (void)
void __attribute__ ((weak)) os_impl_systick_handler(void)
Variables
static Systick_clock::rep os::rtos::__systick_now
static Realtime_clock::rep os::rtos::__rtc_now
Function Documentation
void __attribute__ ((weak))
Definition at line 82 of file os-clocks.cpp.
References os_impl_rtc_handler().
 {
   // TODO
 }
void os_rtc_handler (void)
Definition at line 70 of file os-clocks.cpp.
References os::rtos::__rtc_now, os_impl_rtc_handler(), and os::rtos::scheduler::started().
Referenced by os::rtos::evflags::Attributes::Attributes(), os_systick_clock_ticks_cast_long(), and os_systick_handler().
 {
   using namespace os::rtos;
   // Prevent scheduler actions before starting it.
   if (scheduler::started ())
     {
       os_impl_rtc_handler ();
     }
   ++__rtc_now;
 }
void os_systick_handler (void)
Definition at line 46 of file os-clocks.cpp.
References os::rtos::__systick_now, os::rtos::Systick_clock::frequency_hz, os_impl_systick_handler(), os_rtc_handler(), and os::rtos::scheduler::started().
Referenced by os::rtos::evflags::Attributes::Attributes(), and os_systick_clock_ticks_cast_long().
 {
   using namespace os::rtos;
   // Prevent scheduler actions before starting it.
   if (scheduler::started ())
     {
       os_impl_systick_handler ();
     }
   __systick_now++;
 #if !defined(OS_INCLUDE_REALTIME_CLOCK_DRIVER)
   static uint32_t ticks = Systick_clock::frequency_hz;
   if (--ticks == 0)
     {
       ticks = Systick_clock::frequency_hz;
       os_rtc_handler ();
     }
 #endif
 }