CMSIS++ Reference: include/cmsis-plus/rtos/os-c-api.h File Reference
os-c-api.h File Reference
#include <cmsis-plus/rtos/os-c-decls.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
Enumerations
enum { os_ok = 0 }
Functions
int os_main (int argc, char *argv[])
os_result_t os_sched_initialize (void)
os_result_t os_sched_start (void)
bool os_sched_is_started (void)
os_sched_status_t os_sched_lock (void)
void os_sched_unlock (os_sched_status_t status)
bool os_sched_is_locked (void)
os_irq_status_t os_irq_critical_enter (void)
void os_irq_critical_exit (os_irq_status_t status)
void os_this_thread_suspend (void)
void os_this_thread_exit (void *exit_ptr)
os_result_t os_this_thread_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t *oflags, os_flags_mode_t mode)
os_result_t os_this_thread_try_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t *oflags, os_flags_mode_t mode)
os_result_t os_this_thread_timed_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t *oflags, os_flags_mode_t mode, os_systicks_t ticks)
void os_thread_attr_init (os_thread_attr_t *attr, const char *name)
void os_thread_create (os_thread_t *thread, const os_thread_attr_t *attr, os_thread_func_t func, const os_thread_func_args_t args)
void os_thread_destroy (os_thread_t *thread)
os_result_t os_thread_join (os_thread_t *thread, void **exit_ptr)
os_thread_prio_t os_thread_get_prio (os_thread_t *thread)
os_result_t os_thread_set_prio (os_thread_t *thread, os_thread_prio_t prio)
void os_thread_wakeup (os_thread_t *thread)
os_thread_user_storage_t * os_thread_get_user_storage (os_thread_t *thread)
os_result_t os_thread_sig_raise (os_thread_t *thread, os_thread_sigset_t mask, os_thread_sigset_t *oflags)
os_result_t os_thread_sig_clear (os_thread_t *thread, os_thread_sigset_t mask, os_thread_sigset_t *oflags)
os_thread_sigset_t os_thread_sig_get (os_thread_t *thread, os_thread_sigset_t mask, os_flags_mode_t mode)
os_systick_clock_rep_t os_systick_clock_now (void)
os_systick_clock_rep_t os_systick_clock_now_details (os_systick_clock_current_t *details)
os_result_t os_systick_clock_sleep_for (os_systick_clock_sleep_rep_t ticks)
os_result_t os_systick_clock_wait (os_systick_clock_sleep_rep_t ticks)
os_systicks_t os_systick_clock_ticks_cast (uint32_t microsec)
os_systicks_t os_systick_clock_ticks_cast_long (uint64_t microsec)
os_realtime_clock_rep_t os_realtime_clock_now (void)
os_result_t os_realtime_clock_sleep_for (os_realtime_clock_sleep_rep_t secs)
void os_timer_attr_init (os_timer_attr_t *attr, const char *name)
void os_timer_create (os_timer_t *timer, const os_timer_attr_t *attr, os_timer_func_t func, os_timer_func_args_t args)
void os_timer_destroy (os_timer_t *timer)
os_result_t os_timer_start (os_timer_t *timer, os_systicks_t ticks)
os_result_t os_timer_stop (os_timer_t *timer)
void os_mutex_attr_init (os_mutex_attr_t *attr, const char *name)
void os_mutex_create (os_mutex_t *mutex, const os_mutex_attr_t *attr)
void os_mutex_destroy (os_mutex_t *mutex)
os_result_t os_mutex_lock (os_mutex_t *mutex)
os_result_t os_mutex_try_lock (os_mutex_t *mutex)
os_result_t os_mutex_timed_lock (os_mutex_t *mutex, os_systicks_t ticks)
os_result_t os_mutex_unlock (os_mutex_t *mutex)
os_thread_prio_t os_mutex_get_prio_ceiling (os_mutex_t *mutex)
os_result_t os_mutex_set_prio_ceiling (os_mutex_t *mutex, os_thread_prio_t prio_ceiling, os_thread_prio_t *old_prio_ceiling)
void os_condvar_attr_init (os_condvar_attr_t *attr, const char *name)
void os_condvar_create (os_condvar_t *condvar, os_condvar_attr_t *attr)
void os_condvar_destroy (os_condvar_t *condvar)
os_result_t os_condvar_signal (os_condvar_t *condvar)
os_result_t os_condvar_broadcast (os_condvar_t *condvar)
os_result_t os_condvar_wait (os_condvar_t *condvar, os_mutex_t *mutex)
os_result_t os_condvar_timed_wait (os_condvar_t *condvar, os_mutex_t *mutex, os_systicks_t ticks)
void os_semaphore_attr_init (os_semaphore_attr_t *attr, const char *name)
void os_semaphore_create (os_semaphore_t *semaphore, os_semaphore_attr_t *attr)
void os_semaphore_destroy (os_semaphore_t *semaphore)
os_result_t os_semaphore_post (os_semaphore_t *semaphore)
os_result_t os_semaphore_wait (os_semaphore_t *semaphore)
os_result_t os_semaphore_try_wait (os_semaphore_t *semaphore)
os_result_t os_semaphore_timed_wait (os_semaphore_t *semaphore, os_systicks_t ticks)
os_semaphore_count_t os_semaphore_get_value (os_semaphore_t *semaphore)
os_result_t os_semaphore_reset (os_semaphore_t *semaphore)
void os_mempool_attr_init (os_mempool_attr_t *attr, const char *name)
void os_mempool_create (os_mempool_t *mempool, os_mempool_attr_t *attr, os_mempool_size_t blocks, os_mempool_size_t block_size_bytes)
void os_mempool_destroy (os_mempool_t *mempool)
void * os_mempool_alloc (os_mempool_t *mempool)
void * os_mempool_try_alloc (os_mempool_t *mempool)
void * os_mempool_timed_alloc (os_mempool_t *mempool, os_systicks_t ticks)
os_result_t os_mempool_free (os_mempool_t *mempool, void *block)
size_t os_mempool_get_capacity (os_mempool_t *mempool)
size_t os_mempool_get_count (os_mempool_t *mempool)
size_t os_mempool_get_block_size (os_mempool_t *mempool)
bool os_mempool_is_empty (os_mempool_t *mempool)
bool os_mempool_is_full (os_mempool_t *mempool)
os_result_t os_mempool_reset (os_mempool_t *mempool)
void os_mqueue_attr_init (os_mqueue_attr_t *attr, const char *name)
void os_mqueue_create (os_mqueue_t *mqueue, os_mqueue_attr_t *attr, os_mqueue_size_t msgs, os_mqueue_size_t msg_size_bytes)
void os_mqueue_destroy (os_mqueue_t *mqueue)
os_result_t os_mqueue_send (os_mqueue_t *mqueue, const char *msg, size_t nbytes, os_mqueue_prio_t mprio)
os_result_t os_mqueue_try_send (os_mqueue_t *mqueue, const char *msg, size_t nbytes, os_mqueue_prio_t mprio)
os_result_t os_mqueue_timed_send (os_mqueue_t *mqueue, const char *msg, size_t nbytes, os_mqueue_prio_t mprio, os_systicks_t ticks)
os_result_t os_mqueue_receive (os_mqueue_t *mqueue, char *msg, size_t nbytes, os_mqueue_prio_t *mprio)
os_result_t os_mqueue_try_receive (os_mqueue_t *mqueue, char *msg, size_t nbytes, os_mqueue_prio_t *mprio)
os_result_t os_mqueue_timed_receive (os_mqueue_t *mqueue, char *msg, size_t nbytes, os_mqueue_prio_t *mprio, os_systicks_t ticks)
size_t os_mqueue_get_length (os_mqueue_t *mqueue)
size_t os_mqueue_get_capacity (os_mqueue_t *mqueue)
size_t os_mqueue_get_msg_size (os_mqueue_t *mqueue)
bool os_mqueue_is_empty (os_mqueue_t *mqueue)
bool os_mqueue_is_full (os_mqueue_t *mqueue)
os_result_t os_mqueue_reset (os_mqueue_t *mqueue)
void os_evflags_attr_init (os_evflags_attr_t *attr, const char *name)
void os_evflags_create (os_evflags_t *evflags, os_evflags_attr_t *attr)
void os_evflags_destroy (os_evflags_t *evflags)
os_result_t os_evflags_wait (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags, os_flags_mode_t mode)
os_result_t os_evflags_try_wait (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags, os_flags_mode_t mode)
os_result_t os_evflags_timed_wait (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags, os_flags_mode_t mode, os_systicks_t ticks)
os_result_t os_evflags_raise (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags)
os_result_t os_evflags_clear (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags)
os_flags_mask_t os_evflags_get (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mode_t mode)
bool os_evflags_get_waiting (os_evflags_t *evflags)
void os_systick_handler (void)
void os_rtc_handler (void)
Enumeration Type Documentation
anonymous enum
Enumerator
os_ok
function completed; no error or event occurred.
Definition at line 49 of file os-c-api.h.
   {
     os_ok = 0,
   };
Function Documentation
void os_condvar_attr_init (os_condvar_attr_t * attr, const char * name)
Definition at line 384 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) condvar::Attributes (name);
 }
os_result_t os_condvar_broadcast (os_condvar_t * condvar)
Definition at line 408 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).broadcast ();
 }
void os_condvar_create (os_condvar_t * condvar, os_condvar_attr_t * attr)
Definition at line 390 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (condvar) Condition_variable ((condvar::Attributes&) *attr);
 }
void os_condvar_destroy (os_condvar_t * condvar)
Definition at line 396 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Condition_variable&> (*condvar)).~Condition_variable ();
 }
os_result_t os_condvar_signal (os_condvar_t * condvar)
Definition at line 402 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).signal ();
 }
os_result_t os_condvar_timed_wait (os_condvar_t * condvar, os_mutex_t * mutex, os_systicks_t ticks)
Definition at line 421 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).timed_wait (
       (Mutex&) *mutex, ticks);
 }
os_result_t os_condvar_wait (os_condvar_t * condvar, os_mutex_t * mutex)
Definition at line 414 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).wait (
       (Mutex&) *mutex);
 }
void os_evflags_attr_init (os_evflags_attr_t * attr, const char * name)
Definition at line 676 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) evflags::Attributes (name);
 }
os_result_t os_evflags_clear (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags)
Definition at line 728 of file os-c-wrapper.cpp.
References os::rtos::flags::mode::clear.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).clear (
       mask, oflags);
 }
void os_evflags_create (os_evflags_t * evflags, os_evflags_attr_t * attr)
Definition at line 682 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (evflags) Event_flags ((evflags::Attributes&) *attr);
 }
void os_evflags_destroy (os_evflags_t * evflags)
Definition at line 688 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Event_flags&> (*evflags)).~Event_flags ();
 }
os_flags_mask_t os_evflags_get (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mode_t mode)
Definition at line 736 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_flags_mask_t) (reinterpret_cast<Event_flags&> (*evflags)).get (
       mask, mode);
 }
bool os_evflags_get_waiting (os_evflags_t * evflags)
Definition at line 744 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Event_flags&> (*evflags)).waiting ();
 }
os_result_t os_evflags_raise (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags)
Definition at line 720 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).raise (
       mask, oflags);
 }
os_result_t os_evflags_timed_wait (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags, os_flags_mode_t mode, os_systicks_t ticks)
Definition at line 711 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).timed_wait (
       mask, oflags, mode, ticks);
 }
os_result_t os_evflags_try_wait (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags, os_flags_mode_t mode)
Definition at line 703 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).try_wait (
       mask, oflags, mode);
 }
os_result_t os_evflags_wait (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags, os_flags_mode_t mode)
Definition at line 694 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).wait (mask,
                                                                          oflags,
                                                                          mode);
 }
os_irq_status_t os_irq_critical_enter (void)
Definition at line 125 of file os-c-wrapper.cpp.
References os::rtos::interrupts::Critical_section::enter().
 {
   return interrupts::Critical_section::enter();
 }
void os_irq_critical_exit (os_irq_status_t status)
Definition at line 131 of file os-c-wrapper.cpp.
References os::rtos::interrupts::Critical_section::exit().
 {
   interrupts::Critical_section::exit(status);
 }
int os_main (int argc, char * argv[])
void* os_mempool_alloc (os_mempool_t * mempool)
Definition at line 508 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).alloc ();
 }
void os_mempool_attr_init (os_mempool_attr_t * attr, const char * name)
Definition at line 488 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) mempool::Attributes (name);
 }
void os_mempool_create (os_mempool_t * mempool, os_mempool_attr_t * attr, os_mempool_size_t blocks, os_mempool_size_t block_size_bytes)
Definition at line 494 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (mempool) Memory_pool ((mempool::Attributes&) *attr, blocks,
                              block_size_bytes);
 }
void os_mempool_destroy (os_mempool_t * mempool)
Definition at line 502 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Memory_pool&> (*mempool)).~Memory_pool ();
 }
os_result_t os_mempool_free (os_mempool_t * mempool, void * block)
Definition at line 526 of file os-c-wrapper.cpp.
References os::estd::free().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Memory_pool&> (*mempool)).free (block);
 }
size_t os_mempool_get_block_size (os_mempool_t * mempool)
Definition at line 544 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).block_size ();
 }
size_t os_mempool_get_capacity (os_mempool_t * mempool)
Definition at line 532 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).capacity ();
 }
size_t os_mempool_get_count (os_mempool_t * mempool)
Definition at line 538 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).count ();
 }
bool os_mempool_is_empty (os_mempool_t * mempool)
Definition at line 550 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).empty ();
 }
bool os_mempool_is_full (os_mempool_t * mempool)
Definition at line 556 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).full ();
 }
os_result_t os_mempool_reset (os_mempool_t * mempool)
Definition at line 562 of file os-c-wrapper.cpp.
References os::driver::usb::device::reset.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Memory_pool&> (*mempool)).reset ();
 }
void* os_mempool_timed_alloc (os_mempool_t * mempool, os_systicks_t ticks)
Definition at line 520 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).timed_alloc (ticks);
 }
void* os_mempool_try_alloc (os_mempool_t * mempool)
Definition at line 514 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).try_alloc ();
 }
void os_mqueue_attr_init (os_mqueue_attr_t * attr, const char * name)
Definition at line 570 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) mqueue::Attributes (name);
 }
void os_mqueue_create (os_mqueue_t * mqueue, os_mqueue_attr_t * attr, os_mqueue_size_t msgs, os_mqueue_size_t msg_size_bytes)
Definition at line 576 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (mqueue) Message_queue ((mqueue::Attributes&) *attr, msgs,
                               msg_size_bytes);
 }
void os_mqueue_destroy (os_mqueue_t * mqueue)
Definition at line 584 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Message_queue&> (*mqueue)).~Message_queue ();
 }
size_t os_mqueue_get_capacity (os_mqueue_t * mqueue)
Definition at line 644 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).capacity ();
 }
size_t os_mqueue_get_length (os_mqueue_t * mqueue)
Definition at line 638 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).length ();
 }
size_t os_mqueue_get_msg_size (os_mqueue_t * mqueue)
Definition at line 650 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).msg_size ();
 }
bool os_mqueue_is_empty (os_mqueue_t * mqueue)
Definition at line 656 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).empty ();
 }
bool os_mqueue_is_full (os_mqueue_t * mqueue)
Definition at line 662 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).full ();
 }
os_result_t os_mqueue_receive (os_mqueue_t * mqueue, char * msg, size_t nbytes, os_mqueue_prio_t * mprio)
Definition at line 614 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).receive (
       msg, nbytes, mprio);
 }
os_result_t os_mqueue_reset (os_mqueue_t * mqueue)
Definition at line 668 of file os-c-wrapper.cpp.
References os::driver::usb::device::reset.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).reset ();
 }
os_result_t os_mqueue_send (os_mqueue_t * mqueue, const char * msg, size_t nbytes, os_mqueue_prio_t mprio)
Definition at line 590 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).send (
       msg, nbytes, mprio);
 }
os_result_t os_mqueue_timed_receive (os_mqueue_t * mqueue, char * msg, size_t nbytes, os_mqueue_prio_t * mprio, os_systicks_t ticks)
Definition at line 630 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).timed_receive (
       msg, nbytes, mprio, ticks);
 }
os_result_t os_mqueue_timed_send (os_mqueue_t * mqueue, const char * msg, size_t nbytes, os_mqueue_prio_t mprio, os_systicks_t ticks)
Definition at line 606 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).timed_send (
       msg, nbytes, mprio, ticks);
 }
os_result_t os_mqueue_try_receive (os_mqueue_t * mqueue, char * msg, size_t nbytes, os_mqueue_prio_t * mprio)
Definition at line 622 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).try_receive (
       msg, nbytes, mprio);
 }
os_result_t os_mqueue_try_send (os_mqueue_t * mqueue, const char * msg, size_t nbytes, os_mqueue_prio_t mprio)
Definition at line 598 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).try_send (
       msg, nbytes, mprio);
 }
void os_mutex_attr_init (os_mutex_attr_t * attr, const char * name)
Definition at line 326 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) mutex::Attributes (name);
 }
void os_mutex_create (os_mutex_t * mutex, const os_mutex_attr_t * attr)
Definition at line 332 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (mutex) Mutex ((mutex::Attributes&) *attr);
 }
void os_mutex_destroy (os_mutex_t * mutex)
Definition at line 338 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Mutex&> (*mutex)).~Mutex ();
 }
os_thread_prio_t os_mutex_get_prio_ceiling (os_mutex_t * mutex)
Definition at line 368 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_thread_prio_t) (reinterpret_cast<Mutex&> (*mutex)).prio_ceiling ();
 }
os_result_t os_mutex_lock (os_mutex_t * mutex)
Definition at line 344 of file os-c-wrapper.cpp.
References os::rtos::scheduler::lock().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).lock ();
 }
os_result_t os_mutex_set_prio_ceiling (os_mutex_t * mutex, os_thread_prio_t prio_ceiling, os_thread_prio_t * old_prio_ceiling)
Definition at line 374 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).prio_ceiling (
       prio_ceiling, old_prio_ceiling);
 }
os_result_t os_mutex_timed_lock (os_mutex_t * mutex, os_systicks_t ticks)
Definition at line 356 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).timed_lock (ticks);
 }
os_result_t os_mutex_try_lock (os_mutex_t * mutex)
Definition at line 350 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).try_lock ();
 }
os_result_t os_mutex_unlock (os_mutex_t * mutex)
Definition at line 362 of file os-c-wrapper.cpp.
References os::rtos::scheduler::unlock().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).unlock ();
 }
os_realtime_clock_rep_t os_realtime_clock_now (void)
Definition at line 278 of file os-c-wrapper.cpp.
References os::rtos::Realtime_clock::now().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_realtime_clock_rep_t) Realtime_clock::now ();
 }
os_result_t os_realtime_clock_sleep_for (os_realtime_clock_sleep_rep_t secs)
Definition at line 284 of file os-c-wrapper.cpp.
References os::rtos::Realtime_clock::sleep_for().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) Realtime_clock::sleep_for (secs);
 }
void os_rtc_handler (void)
Definition at line 70 of file os-clocks.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   using namespace os::rtos;
   // Prevent scheduler actions before starting it.
   if (scheduler::started ())
     {
       os_impl_rtc_handler ();
     }
   ++__rtc_now;
 }
os_result_t os_sched_initialize (void)
Definition at line 87 of file os-c-wrapper.cpp.
References os::rtos::scheduler::initialize().
 {
   return static_cast<os_result_t> (scheduler::initialize ());
 }
bool os_sched_is_locked (void)
Definition at line 117 of file os-c-wrapper.cpp.
References os::rtos::scheduler::locked().
 {
   return scheduler::locked ();
 }
bool os_sched_is_started (void)
Definition at line 99 of file os-c-wrapper.cpp.
References os::rtos::scheduler::started().
 {
   return scheduler::started ();
 }
os_sched_status_t os_sched_lock (void)
Definition at line 105 of file os-c-wrapper.cpp.
References os::rtos::scheduler::lock().
 {
   return scheduler::lock ();
 }
os_result_t os_sched_start (void)
Definition at line 93 of file os-c-wrapper.cpp.
References os::rtos::scheduler::start().
 {
   return static_cast<os_result_t> (scheduler::start ());
 }
void os_sched_unlock (os_sched_status_t status)
Definition at line 111 of file os-c-wrapper.cpp.
References os::rtos::scheduler::unlock().
 {
   scheduler::unlock (status);
 }
void os_semaphore_attr_init (os_semaphore_attr_t * attr, const char * name)
Definition at line 431 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) semaphore::Attributes (name);
 }
void os_semaphore_create (os_semaphore_t * semaphore, os_semaphore_attr_t * attr)
Definition at line 437 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (semaphore) Semaphore ((semaphore::Attributes&) *attr);
 }
void os_semaphore_destroy (os_semaphore_t * semaphore)
Definition at line 443 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Semaphore&> (*semaphore)).~Semaphore ();
 }
os_semaphore_count_t os_semaphore_get_value (os_semaphore_t * semaphore)
Definition at line 474 of file os-c-wrapper.cpp.
References value.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_semaphore_count_t) (reinterpret_cast<Semaphore&> (*semaphore)).value ();
 }
os_result_t os_semaphore_post (os_semaphore_t * semaphore)
Definition at line 449 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).post ();
 }
os_result_t os_semaphore_reset (os_semaphore_t * semaphore)
Definition at line 480 of file os-c-wrapper.cpp.
References os::driver::usb::device::reset.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).reset ();
 }
os_result_t os_semaphore_timed_wait (os_semaphore_t * semaphore, os_systicks_t ticks)
Definition at line 467 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).timed_wait (
       ticks);
 }
os_result_t os_semaphore_try_wait (os_semaphore_t * semaphore)
Definition at line 461 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).try_wait ();
 }
os_result_t os_semaphore_wait (os_semaphore_t * semaphore)
Definition at line 455 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).wait ();
 }
os_systick_clock_rep_t os_systick_clock_now (void)
Definition at line 251 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::now().
 {
   return (os_systick_clock_rep_t) Systick_clock::now ();
 }
os_systick_clock_rep_t os_systick_clock_now_details (os_systick_clock_current_t * details)
Definition at line 257 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::now().
 {
   return (os_systick_clock_rep_t) Systick_clock::now (
       (Systick_clock::current_t*) details);
 }
os_result_t os_systick_clock_sleep_for (os_systick_clock_sleep_rep_t ticks)
Definition at line 264 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::sleep_for().
 {
   return (os_result_t) Systick_clock::sleep_for (ticks);
 }
os_systicks_t os_systick_clock_ticks_cast (uint32_t microsec) inline
Definition at line 163 of file os-c-api.h.
References OS_INTEGER_SYSTICK_FREQUENCY_HZ.
   {
     // TODO: add some restrictions to match only numeric types
     return (os_systicks_t) ((((microsec)
         * ((uint32_t) OS_INTEGER_SYSTICK_FREQUENCY_HZ)) + (uint32_t) 999999ul)
         / (uint32_t) 1000000ul);
   }
os_systicks_t os_systick_clock_ticks_cast_long (uint64_t microsec) inline
Definition at line 172 of file os-c-api.h.
References args, attr, func, os_condvar_attr_init(), os_condvar_broadcast(), os_condvar_create(), os_condvar_destroy(), os_condvar_signal(), os_condvar_timed_wait(), os_condvar_wait(), os_evflags_attr_init(), os_evflags_clear(), os_evflags_create(), os_evflags_destroy(), os_evflags_get(), os_evflags_get_waiting(), os_evflags_raise(), os_evflags_timed_wait(), os_evflags_try_wait(), os_evflags_wait(), OS_INTEGER_SYSTICK_FREQUENCY_HZ, os_mempool_alloc(), os_mempool_attr_init(), os_mempool_create(), os_mempool_destroy(), os_mempool_free(), os_mempool_get_block_size(), os_mempool_get_capacity(), os_mempool_get_count(), os_mempool_is_empty(), os_mempool_is_full(), os_mempool_reset(), os_mempool_timed_alloc(), os_mempool_try_alloc(), os_mqueue_attr_init(), os_mqueue_create(), os_mqueue_destroy(), os_mqueue_get_capacity(), os_mqueue_get_length(), os_mqueue_get_msg_size(), os_mqueue_is_empty(), os_mqueue_is_full(), os_mqueue_receive(), os_mqueue_reset(), os_mqueue_send(), os_mqueue_timed_receive(), os_mqueue_timed_send(), os_mqueue_try_receive(), os_mqueue_try_send(), os_mutex_attr_init(), os_mutex_create(), os_mutex_destroy(), os_mutex_get_prio_ceiling(), os_mutex_lock(), os_mutex_set_prio_ceiling(), os_mutex_timed_lock(), os_mutex_try_lock(), os_mutex_unlock(), os_realtime_clock_now(), os_realtime_clock_sleep_for(), os_rtc_handler(), os_semaphore_attr_init(), os_semaphore_create(), os_semaphore_destroy(), os_semaphore_get_value(), os_semaphore_post(), os_semaphore_reset(), os_semaphore_timed_wait(), os_semaphore_try_wait(), os_semaphore_wait(), os_systick_handler(), os_timer_attr_init(), os_timer_create(), os_timer_destroy(), os_timer_start(), and os_timer_stop().
   {
     // TODO: add some restrictions to match only numeric types
     return (os_systicks_t) ((((microsec)
         * ((uint64_t) OS_INTEGER_SYSTICK_FREQUENCY_HZ)) + (uint64_t) 999999ul)
         / (uint64_t) 1000000ul);
   }
os_result_t os_systick_clock_wait (os_systick_clock_sleep_rep_t ticks)
Definition at line 270 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::wait().
 {
   return (os_result_t) Systick_clock::wait (ticks);
 }
void os_systick_handler (void)
Definition at line 46 of file os-clocks.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   using namespace os::rtos;
   // Prevent scheduler actions before starting it.
   if (scheduler::started ())
     {
       os_impl_systick_handler ();
     }
   __systick_now++;
 #if !defined(OS_INCLUDE_REALTIME_CLOCK_DRIVER)
   static uint32_t ticks = Systick_clock::frequency_hz;
   if (--ticks == 0)
     {
       ticks = Systick_clock::frequency_hz;
       os_rtc_handler ();
     }
 #endif
 }
void os_this_thread_exit (void * exit_ptr)
Definition at line 145 of file os-c-wrapper.cpp.
References os::rtos::this_thread::exit().
 {
   this_thread::exit (exit_ptr);
 }
os_result_t os_this_thread_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t * oflags, os_flags_mode_t mode)
Definition at line 151 of file os-c-wrapper.cpp.
References os::rtos::this_thread::sig_wait().
 {
   return (os_result_t) this_thread::sig_wait (mask, oflags, mode);
 }
void os_this_thread_suspend (void)
Definition at line 139 of file os-c-wrapper.cpp.
References os::rtos::this_thread::suspend().
 {
   return this_thread::suspend ();
 }
os_result_t os_this_thread_timed_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t * oflags, os_flags_mode_t mode, os_systicks_t ticks)
Definition at line 165 of file os-c-wrapper.cpp.
References os::rtos::this_thread::timed_sig_wait().
 {
   return (os_result_t) this_thread::timed_sig_wait (mask, oflags, mode, ticks);
 }
os_result_t os_this_thread_try_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t * oflags, os_flags_mode_t mode)
Definition at line 158 of file os-c-wrapper.cpp.
References os::rtos::this_thread::try_sig_wait().
 {
   return (os_result_t) this_thread::try_sig_wait (mask, oflags, mode);
 }
void os_thread_attr_init (os_thread_attr_t * attr, const char * name)
Definition at line 175 of file os-c-wrapper.cpp.
References attr.
 {
   new (attr) thread::Attributes (name);
 }
void os_thread_create (os_thread_t * thread, const os_thread_attr_t * attr, os_thread_func_t func, const os_thread_func_args_t args)
Definition at line 181 of file os-c-wrapper.cpp.
References args, attr, and os::rtos::this_thread::thread().
 {
   new (thread) Thread ((thread::Attributes&) *attr, (thread::func_t) func,
                        (thread::func_args_t) args);
 }
void os_thread_destroy (os_thread_t * thread)
Definition at line 189 of file os-c-wrapper.cpp.
 {
   (reinterpret_cast<Thread&> (*thread)).~Thread ();
 }
os_thread_prio_t os_thread_get_prio (os_thread_t * thread)
Definition at line 201 of file os-c-wrapper.cpp.
 {
   return (os_thread_prio_t) (reinterpret_cast<Thread&> (*thread)).sched_prio ();
 }
os_thread_user_storage_t* os_thread_get_user_storage (os_thread_t * thread)
Definition at line 219 of file os-c-wrapper.cpp.
 {
   return (reinterpret_cast<Thread&> (*thread)).user_storage ();
 }
os_result_t os_thread_join (os_thread_t * thread, void ** exit_ptr)
Definition at line 195 of file os-c-wrapper.cpp.
References join().
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).join (exit_ptr);
 }
os_result_t os_thread_set_prio (os_thread_t * thread, os_thread_prio_t prio)
Definition at line 207 of file os-c-wrapper.cpp.
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).sched_prio (prio);
 }
os_result_t os_thread_sig_clear (os_thread_t * thread, os_thread_sigset_t mask, os_thread_sigset_t * oflags)
Definition at line 233 of file os-c-wrapper.cpp.
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).sig_clear (mask,
                                                                         oflags);
 }
os_thread_sigset_t os_thread_sig_get (os_thread_t * thread, os_thread_sigset_t mask, os_flags_mode_t mode)
Definition at line 241 of file os-c-wrapper.cpp.
 {
   return (os_thread_sigset_t) (reinterpret_cast<Thread&> (*thread)).sig_get (
       mask, mode);
 }
os_result_t os_thread_sig_raise (os_thread_t * thread, os_thread_sigset_t mask, os_thread_sigset_t * oflags)
Definition at line 225 of file os-c-wrapper.cpp.
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).sig_raise (mask,
                                                                         oflags);
 }
void os_thread_wakeup (os_thread_t * thread)
Definition at line 213 of file os-c-wrapper.cpp.
 {
   return (reinterpret_cast<Thread&> (*thread)).wakeup ();
 }
void os_timer_attr_init (os_timer_attr_t * attr, const char * name)
Definition at line 292 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) timer::Attributes (name);
 }
void os_timer_create (os_timer_t * timer, const os_timer_attr_t * attr, os_timer_func_t func, os_timer_func_args_t args)
Definition at line 298 of file os-c-wrapper.cpp.
References args, and attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (timer) Timer ((timer::Attributes&) *attr, (timer::func_t) func,
                      (timer::func_args_t) args);
 }
void os_timer_destroy (os_timer_t * timer)
Definition at line 306 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Timer&> (*timer)).~Timer ();
 }
os_result_t os_timer_start (os_timer_t * timer, os_systicks_t ticks)
Definition at line 312 of file os-c-wrapper.cpp.
References os::rtos::scheduler::start().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Timer&> (*timer)).start (ticks);
 }
os_result_t os_timer_stop (os_timer_t * timer)
Definition at line 318 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Timer&> (*timer)).stop ();
 }