CMSIS++ Reference: src/cmsis-plus/rtos/os-c-wrapper.cpp File Reference
os-c-wrapper.cpp File Reference
#include <cmsis-plus/rtos/os.h>
#include <cmsis-plus/rtos/os-c-api.h>
#include <cmsis-plus/diag/trace.h>
#include <cassert>
#include <cerrno>
#include <cstring>
#include <new>
#include <cmsis-plus/legacy/cmsis_os.h>
Functions
os_result_t os_sched_initialize (void)
os_result_t os_sched_start (void)
bool os_sched_is_started (void)
os_sched_status_t os_sched_lock (void)
void os_sched_unlock (os_sched_status_t status)
bool os_sched_is_locked (void)
os_irq_status_t os_irq_critical_enter (void)
void os_irq_critical_exit (os_irq_status_t status)
void os_this_thread_suspend (void)
void os_this_thread_exit (void *exit_ptr)
os_result_t os_this_thread_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t *oflags, os_flags_mode_t mode)
os_result_t os_this_thread_try_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t *oflags, os_flags_mode_t mode)
os_result_t os_this_thread_timed_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t *oflags, os_flags_mode_t mode, os_systicks_t ticks)
void os_thread_attr_init (os_thread_attr_t *attr, const char *name)
void os_thread_create (os_thread_t *thread, const os_thread_attr_t *attr, os_thread_func_t func, const os_thread_func_args_t args)
void os_thread_destroy (os_thread_t *thread)
os_result_t os_thread_join (os_thread_t *thread, void **exit_ptr)
os_thread_prio_t os_thread_get_prio (os_thread_t *thread)
os_result_t os_thread_set_prio (os_thread_t *thread, os_thread_prio_t prio)
void os_thread_wakeup (os_thread_t *thread)
os_thread_user_storage_t * os_thread_get_user_storage (os_thread_t *thread)
os_result_t os_thread_sig_raise (os_thread_t *thread, os_thread_sigset_t mask, os_thread_sigset_t *oflags)
os_result_t os_thread_sig_clear (os_thread_t *thread, os_thread_sigset_t mask, os_thread_sigset_t *oflags)
os_thread_sigset_t os_thread_sig_get (os_thread_t *thread, os_thread_sigset_t mask, os_flags_mode_t mode)
os_systick_clock_rep_t os_systick_clock_now (void)
os_systick_clock_rep_t os_systick_clock_now_details (os_systick_clock_current_t *details)
os_result_t os_systick_clock_sleep_for (os_systick_clock_sleep_rep_t ticks)
os_result_t os_systick_clock_wait (os_systick_clock_sleep_rep_t ticks)
os_realtime_clock_rep_t os_realtime_clock_now (void)
os_result_t os_realtime_clock_sleep_for (os_realtime_clock_sleep_rep_t secs)
void os_timer_attr_init (os_timer_attr_t *attr, const char *name)
void os_timer_create (os_timer_t *timer, const os_timer_attr_t *attr, os_timer_func_t func, os_timer_func_args_t args)
void os_timer_destroy (os_timer_t *timer)
os_result_t os_timer_start (os_timer_t *timer, os_systicks_t ticks)
os_result_t os_timer_stop (os_timer_t *timer)
void os_mutex_attr_init (os_mutex_attr_t *attr, const char *name)
void os_mutex_create (os_mutex_t *mutex, const os_mutex_attr_t *attr)
void os_mutex_destroy (os_mutex_t *mutex)
os_result_t os_mutex_lock (os_mutex_t *mutex)
os_result_t os_mutex_try_lock (os_mutex_t *mutex)
os_result_t os_mutex_timed_lock (os_mutex_t *mutex, os_systicks_t ticks)
os_result_t os_mutex_unlock (os_mutex_t *mutex)
os_thread_prio_t os_mutex_get_prio_ceiling (os_mutex_t *mutex)
os_result_t os_mutex_set_prio_ceiling (os_mutex_t *mutex, os_thread_prio_t prio_ceiling, os_thread_prio_t *old_prio_ceiling)
void os_condvar_attr_init (os_condvar_attr_t *attr, const char *name)
void os_condvar_create (os_condvar_t *condvar, os_condvar_attr_t *attr)
void os_condvar_destroy (os_condvar_t *condvar)
os_result_t os_condvar_signal (os_condvar_t *condvar)
os_result_t os_condvar_broadcast (os_condvar_t *condvar)
os_result_t os_condvar_wait (os_condvar_t *condvar, os_mutex_t *mutex)
os_result_t os_condvar_timed_wait (os_condvar_t *condvar, os_mutex_t *mutex, os_systicks_t ticks)
void os_semaphore_attr_init (os_semaphore_attr_t *attr, const char *name)
void os_semaphore_create (os_semaphore_t *semaphore, os_semaphore_attr_t *attr)
void os_semaphore_destroy (os_semaphore_t *semaphore)
os_result_t os_semaphore_post (os_semaphore_t *semaphore)
os_result_t os_semaphore_wait (os_semaphore_t *semaphore)
os_result_t os_semaphore_try_wait (os_semaphore_t *semaphore)
os_result_t os_semaphore_timed_wait (os_semaphore_t *semaphore, os_systicks_t ticks)
os_semaphore_count_t os_semaphore_get_value (os_semaphore_t *semaphore)
os_result_t os_semaphore_reset (os_semaphore_t *semaphore)
void os_mempool_attr_init (os_mempool_attr_t *attr, const char *name)
void os_mempool_create (os_mempool_t *mempool, os_mempool_attr_t *attr, os_mempool_size_t blocks, os_mempool_size_t block_size_bytes)
void os_mempool_destroy (os_mempool_t *mempool)
void * os_mempool_alloc (os_mempool_t *mempool)
void * os_mempool_try_alloc (os_mempool_t *mempool)
void * os_mempool_timed_alloc (os_mempool_t *mempool, os_systicks_t ticks)
os_result_t os_mempool_free (os_mempool_t *mempool, void *block)
size_t os_mempool_get_capacity (os_mempool_t *mempool)
size_t os_mempool_get_count (os_mempool_t *mempool)
size_t os_mempool_get_block_size (os_mempool_t *mempool)
bool os_mempool_is_empty (os_mempool_t *mempool)
bool os_mempool_is_full (os_mempool_t *mempool)
os_result_t os_mempool_reset (os_mempool_t *mempool)
void os_mqueue_attr_init (os_mqueue_attr_t *attr, const char *name)
void os_mqueue_create (os_mqueue_t *mqueue, os_mqueue_attr_t *attr, os_mqueue_size_t msgs, os_mqueue_size_t msg_size_bytes)
void os_mqueue_destroy (os_mqueue_t *mqueue)
os_result_t os_mqueue_send (os_mqueue_t *mqueue, const char *msg, size_t nbytes, os_mqueue_prio_t mprio)
os_result_t os_mqueue_try_send (os_mqueue_t *mqueue, const char *msg, size_t nbytes, os_mqueue_prio_t mprio)
os_result_t os_mqueue_timed_send (os_mqueue_t *mqueue, const char *msg, size_t nbytes, os_mqueue_prio_t mprio, os_systicks_t ticks)
os_result_t os_mqueue_receive (os_mqueue_t *mqueue, char *msg, size_t nbytes, os_mqueue_prio_t *mprio)
os_result_t os_mqueue_try_receive (os_mqueue_t *mqueue, char *msg, size_t nbytes, os_mqueue_prio_t *mprio)
os_result_t os_mqueue_timed_receive (os_mqueue_t *mqueue, char *msg, size_t nbytes, os_mqueue_prio_t *mprio, os_systicks_t ticks)
size_t os_mqueue_get_length (os_mqueue_t *mqueue)
size_t os_mqueue_get_capacity (os_mqueue_t *mqueue)
size_t os_mqueue_get_msg_size (os_mqueue_t *mqueue)
bool os_mqueue_is_empty (os_mqueue_t *mqueue)
bool os_mqueue_is_full (os_mqueue_t *mqueue)
os_result_t os_mqueue_reset (os_mqueue_t *mqueue)
void os_evflags_attr_init (os_evflags_attr_t *attr, const char *name)
void os_evflags_create (os_evflags_t *evflags, os_evflags_attr_t *attr)
void os_evflags_destroy (os_evflags_t *evflags)
os_result_t os_evflags_wait (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags, os_flags_mode_t mode)
os_result_t os_evflags_try_wait (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags, os_flags_mode_t mode)
os_result_t os_evflags_timed_wait (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags, os_flags_mode_t mode, os_systicks_t ticks)
os_result_t os_evflags_raise (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags)
os_result_t os_evflags_clear (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mask_t *oflags)
os_flags_mask_t os_evflags_get (os_evflags_t *evflags, os_flags_mask_t mask, os_flags_mode_t mode)
bool os_evflags_get_waiting (os_evflags_t *evflags)
osStatus osKernelInitialize (void)
Initialize the RTOS.
osStatus osKernelStart (void)
int32_t osKernelRunning (void)
Check if the RTOS scheduler is started.
osThreadId osThreadCreate (const osThreadDef_t *thread_def, void *args)
Create a thread.
osThreadId osThreadGetId (void)
Get the current thread.
osStatus osThreadTerminate (osThreadId thread_id)
Terminate a thread.
osStatus osThreadYield (void)
Yield control.
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
Change thread priority.
osPriority osThreadGetPriority (osThreadId thread_id)
Get thread priority.
osStatus osDelay (uint32_t millisec)
Time Delay.
osTimerId osTimerCreate (const osTimerDef_t *timer_def, os_timer_type type, void *args)
Create a timer.
osStatus osTimerStart (osTimerId timer_id, uint32_t millisec)
Start the timer.
osStatus osTimerStop (osTimerId timer_id)
Stop the timer.
osStatus osTimerDelete (osTimerId timer_id)
Delete the timer.
int32_t osSignalSet (osThreadId thread_id, int32_t signals)
Set signal flags.
int32_t osSignalClear (osThreadId thread_id, int32_t signals)
Clear the specified Signal Flags of an active thread.
osEvent osSignalWait (int32_t signals, uint32_t millisec)
Wait for one or more Signal Flags to become signaled for the current RUNNING thread.
osMutexId osMutexCreate (const osMutexDef_t *mutex_def)
Create a mutex.
osStatus osMutexWait (osMutexId mutex_id, uint32_t millisec)
Wait for mutex.
osStatus osMutexRelease (osMutexId mutex_id)
Release the mutex.
osStatus osMutexDelete (osMutexId mutex_id)
Delete the mutex.
Function Documentation
void os_condvar_attr_init (os_condvar_attr_t * attr, const char * name)
Definition at line 384 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) condvar::Attributes (name);
 }
os_result_t os_condvar_broadcast (os_condvar_t * condvar)
Definition at line 408 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).broadcast ();
 }
void os_condvar_create (os_condvar_t * condvar, os_condvar_attr_t * attr)
Definition at line 390 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (condvar) Condition_variable ((condvar::Attributes&) *attr);
 }
void os_condvar_destroy (os_condvar_t * condvar)
Definition at line 396 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Condition_variable&> (*condvar)).~Condition_variable ();
 }
os_result_t os_condvar_signal (os_condvar_t * condvar)
Definition at line 402 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).signal ();
 }
os_result_t os_condvar_timed_wait (os_condvar_t * condvar, os_mutex_t * mutex, os_systicks_t ticks)
Definition at line 421 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).timed_wait (
       (Mutex&) *mutex, ticks);
 }
os_result_t os_condvar_wait (os_condvar_t * condvar, os_mutex_t * mutex)
Definition at line 414 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Condition_variable&> (*condvar)).wait (
       (Mutex&) *mutex);
 }
void os_evflags_attr_init (os_evflags_attr_t * attr, const char * name)
Definition at line 676 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) evflags::Attributes (name);
 }
os_result_t os_evflags_clear (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags)
Definition at line 728 of file os-c-wrapper.cpp.
References os::rtos::flags::mode::clear.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).clear (
       mask, oflags);
 }
void os_evflags_create (os_evflags_t * evflags, os_evflags_attr_t * attr)
Definition at line 682 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (evflags) Event_flags ((evflags::Attributes&) *attr);
 }
void os_evflags_destroy (os_evflags_t * evflags)
Definition at line 688 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Event_flags&> (*evflags)).~Event_flags ();
 }
os_flags_mask_t os_evflags_get (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mode_t mode)
Definition at line 736 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_flags_mask_t) (reinterpret_cast<Event_flags&> (*evflags)).get (
       mask, mode);
 }
bool os_evflags_get_waiting (os_evflags_t * evflags)
Definition at line 744 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Event_flags&> (*evflags)).waiting ();
 }
os_result_t os_evflags_raise (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags)
Definition at line 720 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).raise (
       mask, oflags);
 }
os_result_t os_evflags_timed_wait (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags, os_flags_mode_t mode, os_systicks_t ticks)
Definition at line 711 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).timed_wait (
       mask, oflags, mode, ticks);
 }
os_result_t os_evflags_try_wait (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags, os_flags_mode_t mode)
Definition at line 703 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).try_wait (
       mask, oflags, mode);
 }
os_result_t os_evflags_wait (os_evflags_t * evflags, os_flags_mask_t mask, os_flags_mask_t * oflags, os_flags_mode_t mode)
Definition at line 694 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Event_flags&> (*evflags)).wait (mask,
                                                                          oflags,
                                                                          mode);
 }
os_irq_status_t os_irq_critical_enter (void)
Definition at line 125 of file os-c-wrapper.cpp.
References os::rtos::interrupts::Critical_section::enter().
 {
   return interrupts::Critical_section::enter();
 }
void os_irq_critical_exit (os_irq_status_t status)
Definition at line 131 of file os-c-wrapper.cpp.
References os::rtos::interrupts::Critical_section::exit().
 {
   interrupts::Critical_section::exit(status);
 }
void* os_mempool_alloc (os_mempool_t * mempool)
Definition at line 508 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).alloc ();
 }
void os_mempool_attr_init (os_mempool_attr_t * attr, const char * name)
Definition at line 488 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) mempool::Attributes (name);
 }
void os_mempool_create (os_mempool_t * mempool, os_mempool_attr_t * attr, os_mempool_size_t blocks, os_mempool_size_t block_size_bytes)
Definition at line 494 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (mempool) Memory_pool ((mempool::Attributes&) *attr, blocks,
                              block_size_bytes);
 }
void os_mempool_destroy (os_mempool_t * mempool)
Definition at line 502 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Memory_pool&> (*mempool)).~Memory_pool ();
 }
os_result_t os_mempool_free (os_mempool_t * mempool, void * block)
Definition at line 526 of file os-c-wrapper.cpp.
References os::estd::free().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Memory_pool&> (*mempool)).free (block);
 }
size_t os_mempool_get_block_size (os_mempool_t * mempool)
Definition at line 544 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).block_size ();
 }
size_t os_mempool_get_capacity (os_mempool_t * mempool)
Definition at line 532 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).capacity ();
 }
size_t os_mempool_get_count (os_mempool_t * mempool)
Definition at line 538 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).count ();
 }
bool os_mempool_is_empty (os_mempool_t * mempool)
Definition at line 550 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).empty ();
 }
bool os_mempool_is_full (os_mempool_t * mempool)
Definition at line 556 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).full ();
 }
os_result_t os_mempool_reset (os_mempool_t * mempool)
Definition at line 562 of file os-c-wrapper.cpp.
References os::driver::usb::device::reset.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Memory_pool&> (*mempool)).reset ();
 }
void* os_mempool_timed_alloc (os_mempool_t * mempool, os_systicks_t ticks)
Definition at line 520 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).timed_alloc (ticks);
 }
void* os_mempool_try_alloc (os_mempool_t * mempool)
Definition at line 514 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Memory_pool&> (*mempool)).try_alloc ();
 }
void os_mqueue_attr_init (os_mqueue_attr_t * attr, const char * name)
Definition at line 570 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) mqueue::Attributes (name);
 }
void os_mqueue_create (os_mqueue_t * mqueue, os_mqueue_attr_t * attr, os_mqueue_size_t msgs, os_mqueue_size_t msg_size_bytes)
Definition at line 576 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (mqueue) Message_queue ((mqueue::Attributes&) *attr, msgs,
                               msg_size_bytes);
 }
void os_mqueue_destroy (os_mqueue_t * mqueue)
Definition at line 584 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Message_queue&> (*mqueue)).~Message_queue ();
 }
size_t os_mqueue_get_capacity (os_mqueue_t * mqueue)
Definition at line 644 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).capacity ();
 }
size_t os_mqueue_get_length (os_mqueue_t * mqueue)
Definition at line 638 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).length ();
 }
size_t os_mqueue_get_msg_size (os_mqueue_t * mqueue)
Definition at line 650 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).msg_size ();
 }
bool os_mqueue_is_empty (os_mqueue_t * mqueue)
Definition at line 656 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).empty ();
 }
bool os_mqueue_is_full (os_mqueue_t * mqueue)
Definition at line 662 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (reinterpret_cast<Message_queue&> (*mqueue)).full ();
 }
os_result_t os_mqueue_receive (os_mqueue_t * mqueue, char * msg, size_t nbytes, os_mqueue_prio_t * mprio)
Definition at line 614 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).receive (
       msg, nbytes, mprio);
 }
os_result_t os_mqueue_reset (os_mqueue_t * mqueue)
Definition at line 668 of file os-c-wrapper.cpp.
References os::driver::usb::device::reset.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).reset ();
 }
os_result_t os_mqueue_send (os_mqueue_t * mqueue, const char * msg, size_t nbytes, os_mqueue_prio_t mprio)
Definition at line 590 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).send (
       msg, nbytes, mprio);
 }
os_result_t os_mqueue_timed_receive (os_mqueue_t * mqueue, char * msg, size_t nbytes, os_mqueue_prio_t * mprio, os_systicks_t ticks)
Definition at line 630 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).timed_receive (
       msg, nbytes, mprio, ticks);
 }
os_result_t os_mqueue_timed_send (os_mqueue_t * mqueue, const char * msg, size_t nbytes, os_mqueue_prio_t mprio, os_systicks_t ticks)
Definition at line 606 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).timed_send (
       msg, nbytes, mprio, ticks);
 }
os_result_t os_mqueue_try_receive (os_mqueue_t * mqueue, char * msg, size_t nbytes, os_mqueue_prio_t * mprio)
Definition at line 622 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).try_receive (
       msg, nbytes, mprio);
 }
os_result_t os_mqueue_try_send (os_mqueue_t * mqueue, const char * msg, size_t nbytes, os_mqueue_prio_t mprio)
Definition at line 598 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Message_queue&> (*mqueue)).try_send (
       msg, nbytes, mprio);
 }
void os_mutex_attr_init (os_mutex_attr_t * attr, const char * name)
Definition at line 326 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) mutex::Attributes (name);
 }
void os_mutex_create (os_mutex_t * mutex, const os_mutex_attr_t * attr)
Definition at line 332 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (mutex) Mutex ((mutex::Attributes&) *attr);
 }
void os_mutex_destroy (os_mutex_t * mutex)
Definition at line 338 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Mutex&> (*mutex)).~Mutex ();
 }
os_thread_prio_t os_mutex_get_prio_ceiling (os_mutex_t * mutex)
Definition at line 368 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_thread_prio_t) (reinterpret_cast<Mutex&> (*mutex)).prio_ceiling ();
 }
os_result_t os_mutex_lock (os_mutex_t * mutex)
Definition at line 344 of file os-c-wrapper.cpp.
References os::rtos::scheduler::lock().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).lock ();
 }
os_result_t os_mutex_set_prio_ceiling (os_mutex_t * mutex, os_thread_prio_t prio_ceiling, os_thread_prio_t * old_prio_ceiling)
Definition at line 374 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).prio_ceiling (
       prio_ceiling, old_prio_ceiling);
 }
os_result_t os_mutex_timed_lock (os_mutex_t * mutex, os_systicks_t ticks)
Definition at line 356 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).timed_lock (ticks);
 }
os_result_t os_mutex_try_lock (os_mutex_t * mutex)
Definition at line 350 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).try_lock ();
 }
os_result_t os_mutex_unlock (os_mutex_t * mutex)
Definition at line 362 of file os-c-wrapper.cpp.
References os::rtos::scheduler::unlock().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Mutex&> (*mutex)).unlock ();
 }
os_realtime_clock_rep_t os_realtime_clock_now (void)
Definition at line 278 of file os-c-wrapper.cpp.
References os::rtos::Realtime_clock::now().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_realtime_clock_rep_t) Realtime_clock::now ();
 }
os_result_t os_realtime_clock_sleep_for (os_realtime_clock_sleep_rep_t secs)
Definition at line 284 of file os-c-wrapper.cpp.
References os::rtos::Realtime_clock::sleep_for().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) Realtime_clock::sleep_for (secs);
 }
os_result_t os_sched_initialize (void)
Definition at line 87 of file os-c-wrapper.cpp.
References os::rtos::scheduler::initialize().
 {
   return static_cast<os_result_t> (scheduler::initialize ());
 }
bool os_sched_is_locked (void)
Definition at line 117 of file os-c-wrapper.cpp.
References os::rtos::scheduler::locked().
 {
   return scheduler::locked ();
 }
bool os_sched_is_started (void)
Definition at line 99 of file os-c-wrapper.cpp.
References os::rtos::scheduler::started().
 {
   return scheduler::started ();
 }
os_sched_status_t os_sched_lock (void)
Definition at line 105 of file os-c-wrapper.cpp.
References os::rtos::scheduler::lock().
 {
   return scheduler::lock ();
 }
os_result_t os_sched_start (void)
Definition at line 93 of file os-c-wrapper.cpp.
References os::rtos::scheduler::start().
 {
   return static_cast<os_result_t> (scheduler::start ());
 }
void os_sched_unlock (os_sched_status_t status)
Definition at line 111 of file os-c-wrapper.cpp.
References os::rtos::scheduler::unlock().
 {
   scheduler::unlock (status);
 }
void os_semaphore_attr_init (os_semaphore_attr_t * attr, const char * name)
Definition at line 431 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) semaphore::Attributes (name);
 }
void os_semaphore_create (os_semaphore_t * semaphore, os_semaphore_attr_t * attr)
Definition at line 437 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (semaphore) Semaphore ((semaphore::Attributes&) *attr);
 }
void os_semaphore_destroy (os_semaphore_t * semaphore)
Definition at line 443 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Semaphore&> (*semaphore)).~Semaphore ();
 }
os_semaphore_count_t os_semaphore_get_value (os_semaphore_t * semaphore)
Definition at line 474 of file os-c-wrapper.cpp.
References value.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_semaphore_count_t) (reinterpret_cast<Semaphore&> (*semaphore)).value ();
 }
os_result_t os_semaphore_post (os_semaphore_t * semaphore)
Definition at line 449 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).post ();
 }
os_result_t os_semaphore_reset (os_semaphore_t * semaphore)
Definition at line 480 of file os-c-wrapper.cpp.
References os::driver::usb::device::reset.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).reset ();
 }
os_result_t os_semaphore_timed_wait (os_semaphore_t * semaphore, os_systicks_t ticks)
Definition at line 467 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).timed_wait (
       ticks);
 }
os_result_t os_semaphore_try_wait (os_semaphore_t * semaphore)
Definition at line 461 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).try_wait ();
 }
os_result_t os_semaphore_wait (os_semaphore_t * semaphore)
Definition at line 455 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Semaphore&> (*semaphore)).wait ();
 }
os_systick_clock_rep_t os_systick_clock_now (void)
Definition at line 251 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::now().
 {
   return (os_systick_clock_rep_t) Systick_clock::now ();
 }
os_systick_clock_rep_t os_systick_clock_now_details (os_systick_clock_current_t * details)
Definition at line 257 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::now().
 {
   return (os_systick_clock_rep_t) Systick_clock::now (
       (Systick_clock::current_t*) details);
 }
os_result_t os_systick_clock_sleep_for (os_systick_clock_sleep_rep_t ticks)
Definition at line 264 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::sleep_for().
 {
   return (os_result_t) Systick_clock::sleep_for (ticks);
 }
os_result_t os_systick_clock_wait (os_systick_clock_sleep_rep_t ticks)
Definition at line 270 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::wait().
 {
   return (os_result_t) Systick_clock::wait (ticks);
 }
void os_this_thread_exit (void * exit_ptr)
Definition at line 145 of file os-c-wrapper.cpp.
References os::rtos::this_thread::exit().
 {
   this_thread::exit (exit_ptr);
 }
os_result_t os_this_thread_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t * oflags, os_flags_mode_t mode)
Definition at line 151 of file os-c-wrapper.cpp.
References os::rtos::this_thread::sig_wait().
 {
   return (os_result_t) this_thread::sig_wait (mask, oflags, mode);
 }
void os_this_thread_suspend (void)
Definition at line 139 of file os-c-wrapper.cpp.
References os::rtos::this_thread::suspend().
 {
   return this_thread::suspend ();
 }
os_result_t os_this_thread_timed_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t * oflags, os_flags_mode_t mode, os_systicks_t ticks)
Definition at line 165 of file os-c-wrapper.cpp.
References os::rtos::this_thread::timed_sig_wait().
 {
   return (os_result_t) this_thread::timed_sig_wait (mask, oflags, mode, ticks);
 }
os_result_t os_this_thread_try_sig_wait (os_thread_sigset_t mask, os_thread_sigset_t * oflags, os_flags_mode_t mode)
Definition at line 158 of file os-c-wrapper.cpp.
References os::rtos::this_thread::try_sig_wait().
 {
   return (os_result_t) this_thread::try_sig_wait (mask, oflags, mode);
 }
void os_thread_attr_init (os_thread_attr_t * attr, const char * name)
Definition at line 175 of file os-c-wrapper.cpp.
References attr.
 {
   new (attr) thread::Attributes (name);
 }
void os_thread_create (os_thread_t * thread, const os_thread_attr_t * attr, os_thread_func_t func, const os_thread_func_args_t args)
Definition at line 181 of file os-c-wrapper.cpp.
References args, attr, and os::rtos::this_thread::thread().
 {
   new (thread) Thread ((thread::Attributes&) *attr, (thread::func_t) func,
                        (thread::func_args_t) args);
 }
void os_thread_destroy (os_thread_t * thread)
Definition at line 189 of file os-c-wrapper.cpp.
 {
   (reinterpret_cast<Thread&> (*thread)).~Thread ();
 }
os_thread_prio_t os_thread_get_prio (os_thread_t * thread)
Definition at line 201 of file os-c-wrapper.cpp.
 {
   return (os_thread_prio_t) (reinterpret_cast<Thread&> (*thread)).sched_prio ();
 }
os_thread_user_storage_t* os_thread_get_user_storage (os_thread_t * thread)
Definition at line 219 of file os-c-wrapper.cpp.
 {
   return (reinterpret_cast<Thread&> (*thread)).user_storage ();
 }
os_result_t os_thread_join (os_thread_t * thread, void ** exit_ptr)
Definition at line 195 of file os-c-wrapper.cpp.
References join().
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).join (exit_ptr);
 }
os_result_t os_thread_set_prio (os_thread_t * thread, os_thread_prio_t prio)
Definition at line 207 of file os-c-wrapper.cpp.
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).sched_prio (prio);
 }
os_result_t os_thread_sig_clear (os_thread_t * thread, os_thread_sigset_t mask, os_thread_sigset_t * oflags)
Definition at line 233 of file os-c-wrapper.cpp.
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).sig_clear (mask,
                                                                         oflags);
 }
os_thread_sigset_t os_thread_sig_get (os_thread_t * thread, os_thread_sigset_t mask, os_flags_mode_t mode)
Definition at line 241 of file os-c-wrapper.cpp.
 {
   return (os_thread_sigset_t) (reinterpret_cast<Thread&> (*thread)).sig_get (
       mask, mode);
 }
os_result_t os_thread_sig_raise (os_thread_t * thread, os_thread_sigset_t mask, os_thread_sigset_t * oflags)
Definition at line 225 of file os-c-wrapper.cpp.
 {
   return (os_result_t) (reinterpret_cast<Thread&> (*thread)).sig_raise (mask,
                                                                         oflags);
 }
void os_thread_wakeup (os_thread_t * thread)
Definition at line 213 of file os-c-wrapper.cpp.
 {
   return (reinterpret_cast<Thread&> (*thread)).wakeup ();
 }
void os_timer_attr_init (os_timer_attr_t * attr, const char * name)
Definition at line 292 of file os-c-wrapper.cpp.
References attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (attr) timer::Attributes (name);
 }
void os_timer_create (os_timer_t * timer, const os_timer_attr_t * attr, os_timer_func_t func, os_timer_func_args_t args)
Definition at line 298 of file os-c-wrapper.cpp.
References args, and attr.
Referenced by os_systick_clock_ticks_cast_long().
 {
   new (timer) Timer ((timer::Attributes&) *attr, (timer::func_t) func,
                      (timer::func_args_t) args);
 }
void os_timer_destroy (os_timer_t * timer)
Definition at line 306 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   (reinterpret_cast<Timer&> (*timer)).~Timer ();
 }
os_result_t os_timer_start (os_timer_t * timer, os_systicks_t ticks)
Definition at line 312 of file os-c-wrapper.cpp.
References os::rtos::scheduler::start().
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Timer&> (*timer)).start (ticks);
 }
os_result_t os_timer_stop (os_timer_t * timer)
Definition at line 318 of file os-c-wrapper.cpp.
Referenced by os_systick_clock_ticks_cast_long().
 {
   return (os_result_t) (reinterpret_cast<Timer&> (*timer)).stop ();
 }
osStatus osDelay (uint32_t millisec)
Time Delay.
Wait for a specified time period in millisec.
The millisec value specifies the number of timer ticks and is therefore an upper bound. The exact time delay depends on the actual time elapsed since the last timer tick.
For a value of 1, the system waits until the next timer tick occurs. That means that the actual time delay may be up to one timer tick less.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1094 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), osErrorISR, osErrorOS, osEventTimeout, osWait(), os::rtos::Systick_clock::sleep_for(), osEvent::status, os::rtos::Systick_clock::ticks_cast(), and os::rtos::Systick_clock::wait().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   result_t res = Systick_clock::sleep_for (
       Systick_clock::ticks_cast (millisec * 1000u));
   if (res == ETIMEDOUT)
     {
       return osEventTimeout;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osKernelInitialize (void)
Initialize the RTOS.
Initialise of the RTOS Kernel to allow peripheral setup and creation of other RTOS objects with the functions:
osThreadCreate : Create a thread function.
osTimerCreate : Define attributes of the timer callback function.
osMutexCreate : Define and initialise a mutex.
osSemaphoreCreate : Define and initialise a semaphore.
osPoolCreate : Define and initialise a fix-size memory pool.
osMessageCreate : Define and initialise a message queue.
osMailCreate : Define and initialise a mail queue with fix-size memory blocks.
The RTOS scheduler does not start thread switching until the function osKernelStart is called.
Note
In case that the RTOS Kernel starts thread execution with the function main the function osKernelInitialize stops thread switching. This allows you to setup the system to a defined state before thread switching is resumed with osKernelStart.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 780 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::scheduler::initialize(), osErrorISR, and osOK.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   scheduler::initialize ();
   return osOK;
 }
int32_t osKernelRunning (void)
Check if the RTOS scheduler is started.
Identifies if the RTOS scheduler is started. For systems with the option to start the main function as a thread this allows you to identify that the RTOS scheduler is already running.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 816 of file os-c-wrapper.cpp.
References os::rtos::Systick_clock::now(), osKernelSysTick(), and os::rtos::scheduler::started().
 {
   return scheduler::started () ? 1 : 0;
 }
osStatus osKernelStart (void)
Start the RTOS Kernel and begin thread switching.
Note
When the CMSIS-RTOS starts thread execution with the function main this function resumes thread switching. The main thread will continue executing after osKernelStart.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 802 of file os-c-wrapper.cpp.
References os::rtos::scheduler::start().
 {
   return static_cast<osStatus> (scheduler::start ());
 }
osMutexId osMutexCreate (const osMutexDef_t * mutex_def)
Create a mutex.
Create and initialize a mutex object.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1443 of file os-c-wrapper.cpp.
References os_mutex_def::data, os::rtos::scheduler::in_handler_mode(), and os::rtos::mutex::recursive_initializer.
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   if (mutex_def == nullptr)
     {
       return nullptr;
     }
   return reinterpret_cast<osMutexId> (new ((void*) mutex_def->data) Mutex (
       mutex::recursive_initializer));
 }
osStatus osMutexDelete (osMutexId mutex_id)
Delete the mutex.
Delete a mutex object. The function releases internal memory obtained for mutex handling. After this call the mutex_id is no longer valid and cannot be used. The mutex may be created again using the function osMutexCreate.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1586 of file os-c-wrapper.cpp.
References __attribute__(), attr, os::rtos::Memory_pool::block_size(), os::rtos::Memory_pool::capacity(), os_semaphore_def::data, os_pool_def::data, os_messageQ_def::data, os_mailQ_def::data, os::estd::free(), os::rtos::scheduler::in_handler_mode(), os_pool_def::item_sz, os_messageQ_def::item_sz, os_pool_def::items, os_messageQ_def::items, os_mailQ_def::items, os_semaphore_def::name, os_pool_def::name, os_messageQ_def::name, os_mailQ_def::name, os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osErrorTimeoutResource, osErrorValue, osEventMail, osEventMessage, osEventTimeout, osFeature_Semaphore, osMailAlloc(), osMailCAlloc(), osMailCreate(), osMailFree(), osMailGet(), osMailPut(), osMessageCreate(), osMessageGet(), osMessagePut(), osOK, osPoolAlloc(), osPoolCAlloc(), osPoolCreate(), osPoolFree(), osSemaphoreCreate(), osSemaphoreDelete(), osSemaphoreRelease(), osSemaphoreWait(), osWaitForever, osEvent::p, os_pool_def::pool, os_mailQ_def::pool, os_mail_queue_s::pool, os::rtos::Memory_pool::pool(), os_mailQ_def::pool_item_sz, os_messageQ_def::queue, os_mailQ_def::queue, os_mail_queue_s::queue, os_mailQ_def::queue_item_sz, os_messageQ_def::queue_sz, os_mailQ_def::queue_sz, os::trace::ret, osEvent::status, os::rtos::Systick_clock::ticks_cast(), value, and osEvent::value.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (mutex_id == nullptr)
     {
       return osErrorParameter;
     }
   (reinterpret_cast<Mutex&> (*mutex_id)).~Mutex ();
   return osOK;
 }
osStatus osMutexRelease (osMutexId mutex_id)
Release the mutex.
Release a Mutex that was obtained with osMutexWait. Other threads that currently wait for the same mutex will be now put into the state READY.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1547 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osOK, and os::rtos::scheduler::unlock().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (mutex_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t res;
   res = (reinterpret_cast<Mutex&> (*mutex_id)).unlock ();
   if (res == result::ok)
     {
       return osOK;
     }
   else if (res == EPERM)
     {
       return osErrorResource;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osMutexWait (osMutexId mutex_id, uint32_t millisec)
Wait for mutex.
Wait until a Mutex becomes available. If no other thread has obtained the Mutex, the function instantly returns and blocks the mutex object.
The argument millisec specifies how long the system waits for a mutex. While the system waits the thread that is calling this function is put into the state WAITING. The millisec timeout can have the following values:
when millisec is 0, the function returns instantly.
when millisec is set to osWaitForever the function will wait for an infinite time until the mutex becomes available.
all other values specify a time in millisecond for a timeout.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1478 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::scheduler::lock(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osErrorTimeoutResource, osOK, osWaitForever, os::trace::ret, and os::rtos::Systick_clock::ticks_cast().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (mutex_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t ret;
   if (millisec == osWaitForever)
     {
       ret = (reinterpret_cast<Mutex&> (*mutex_id)).lock ();
       // osErrorResource:
     }
   else if (millisec == 0)
     {
       ret = (reinterpret_cast<Mutex&> (*mutex_id)).try_lock ();
     }
   else
     {
       ret = (reinterpret_cast<Mutex&> (*mutex_id)).timed_lock (
           Systick_clock::ticks_cast (millisec * 1000u));
       // osErrorTimeoutResource:
     }
   if (ret == result::ok)
     {
       // osOK: the mutex has been obtained.
       return osOK;
     }
   else if (ret == EAGAIN)
     {
       // The mutex could not be obtained when no timeout was specified.
       // Only for try_lock().
       return osErrorResource;
     }
   else if (ret == ENOTRECOVERABLE)
     {
       // The mutex could not be obtained when no timeout was specified.
       // Only for lock().
       return osErrorResource;
     }
   else if (ret == ETIMEDOUT)
     {
       // The mutex could not be obtained in the given time.
       // Only for timed_lock().
       return osErrorTimeoutResource;
     }
   else
     {
       return osErrorOS;
     }
   return static_cast<osStatus> (ret);
 }
int32_t osSignalClear (osThreadId thread_id, int32_t signals)
Clear the specified Signal Flags of an active thread.
Clear the signal flags of an active thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1321 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode().
 {
   if (thread_id == nullptr)
     {
       return 0x80000000;
     }
   if (scheduler::in_handler_mode () || (signals == 0))
     {
       return 0x80000000;
     }
   thread::sigset_t sig;
   ((Thread*) (thread_id))->sig_clear (signals, &sig);
   return (int32_t) sig;
 }
int32_t osSignalSet (osThreadId thread_id, int32_t signals)
Set signal flags.
Set the signal flags of an active thread.
Note
Can be invoked from Interrupt Service Routines.
Definition at line 1297 of file os-c-wrapper.cpp.
 {
   if (thread_id == nullptr)
     {
       return 0x80000000;
     }
   if (signals == (int32_t) 0x80000000)
     {
       return 0x80000000;
     }
   thread::sigset_t osig;
   ((Thread*) (thread_id))->sig_raise ((thread::sigset_t) signals, &osig);
   return (int32_t) osig;
 }
osEvent osSignalWait (int32_t signals, uint32_t millisec)
Wait for one or more Signal Flags to become signaled for the current RUNNING thread.
Suspend the execution of the current RUNNING thread until all specified signal flags with the parameter signals are set. When the parameter signals is 0 the current RUNNING thread is suspended until any signal is set. When these signal flags are already set, the function returns instantly. Otherwise the thread is put into the state WAITING. Signal flags that are reported as event are automatically cleared.
The argument millisec specifies how long the system waits for the specified signal flags. While the system waits the tread calling this function is put into the state WAITING. The timeout value can have the following values:
when millisec is 0, the function returns instantly.
when millisec is set to osWaitForever the function will wait an infinite time until a specified signal is set.
all other values specify a time in millisecond for a timeout.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1365 of file os-c-wrapper.cpp.
References os::rtos::flags::mode::all, os::rtos::flags::mode::clear, os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorValue, osEventSignal, osEventTimeout, osOK, osWaitForever, os::rtos::this_thread::sig_wait(), osEvent::signals, osEvent::status, os::rtos::Systick_clock::ticks_cast(), os::rtos::this_thread::timed_sig_wait(), os::rtos::this_thread::try_sig_wait(), and osEvent::value.
 {
   osEvent event;
   if (scheduler::in_handler_mode ())
     {
       event.status = osErrorISR;
       return event;
     }
   if (signals & 0x80000000)
     {
       event.status = osErrorValue;
       return event;
     }
   result_t res;
   if (millisec == osWaitForever)
     {
       res = this_thread::sig_wait ((thread::sigset_t) signals,
                                    (thread::sigset_t*) &event.value.signals,
                                    flags::mode::all || flags::mode::clear);
     }
   else if (millisec == 0)
     {
       res = this_thread::try_sig_wait ((thread::sigset_t) signals,
                                        (thread::sigset_t*) &event.value.signals,
                                        flags::mode::all || flags::mode::clear);
     }
   else
     {
       res = this_thread::timed_sig_wait (
           (thread::sigset_t) signals, (thread::sigset_t*) &event.value.signals,
           flags::mode::all || flags::mode::clear,
           Systick_clock::ticks_cast (millisec * 1000u));
     }
   if (res == result::ok)
     {
       event.status = osEventSignal;
     }
   else if (res == EAGAIN)
     {
       event.status = osOK; // Only for try_sig_wait().
     }
   else if (res == ETIMEDOUT)
     {
       event.status = osEventTimeout; // Only for timed_sig_wait().
     }
   else if (res == EPERM)
     {
       event.status = osErrorISR;
     }
   else if (res == EINVAL)
     {
       event.status = osErrorValue;
     }
   else
     {
       event.status = osErrorOS;
     }
   return event;
 }
osThreadId osThreadCreate (const osThreadDef_t * thread_def, void * args)
Create a thread.
Find a free slot in the array of thread definitions and initialise the thread.
Start the thread function by adding it to the Active Threads list and set it to state READY. The thread function receives the argument pointer as function argument when the function is started. When the priority of the created thread function is higher than the current RUNNING thread, the created thread function starts instantly and becomes the new RUNNING thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 869 of file os-c-wrapper.cpp.
References args, attr, os_thread_def::data, os::trace::if(), os::rtos::scheduler::in_handler_mode(), os_thread_def::instances, os_thread_def::name, osPriorityError, os_thread_def::pthread, os::rtos::Thread::sched_state(), os_thread_def::stack, os_thread_def::stacksize, os::rtos::thread::Attributes::th_priority, os::rtos::thread::Attributes::th_stack_address, os::rtos::thread::Attributes::th_stack_size_bytes, and os_thread_def::tpriority.
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   if (thread_def == nullptr)
     {
       return nullptr;
     }
   thread::Attributes attr
     { thread_def->name };
   attr.th_priority = thread_def->tpriority;
   attr.th_stack_size_bytes = thread_def->stacksize;
   // Creating thread with invalid priority should fail (validator requirement).
   if (thread_def->tpriority >= osPriorityError)
     {
       return nullptr;
     }
   // Find a free slot in the tread definitions array.
   for (uint32_t i = 0; i < thread_def->instances; ++i)
     {
       Thread* th = (Thread*) &thread_def->data[i];
       if (th->sched_state () == thread::state::undefined
           || th->sched_state () == thread::state::terminated
           || th->sched_state () == thread::state::destroyed)
         {
           if (attr.th_stack_size_bytes > 0)
             {
               attr.th_stack_address = &thread_def->stack[(i)
                   * ((thread_def->stacksize + sizeof(uint64_t) - 1)
                       / sizeof(uint64_t))];
             }
           new (th) Thread (attr, (thread::func_t) thread_def->pthread, args);
           // No need to yield here, already done by constructor.
           return reinterpret_cast<osThreadId> (th);
         }
     }
   return nullptr;
 }
osThreadId osThreadGetId (void)
Get the current thread.
Get the thread ID of the current running thread.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 922 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), and os::rtos::this_thread::thread().
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   return reinterpret_cast<osThreadId> (&this_thread::thread ());
 }
osPriority osThreadGetPriority (osThreadId thread_id)
Get thread priority.
Get the priority of an active thread. In case of a failure the value osPriorityError is returned.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1059 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), and osPriorityError.
 {
   if (scheduler::in_handler_mode ())
     {
       return osPriorityError;
     }
   if (thread_id == nullptr)
     {
       return osPriorityError;
     }
   // Call C++ accessor.
   thread::priority_t prio =
       (reinterpret_cast<Thread&> (*thread_id)).sched_prio ();
   return static_cast<osPriority> (prio);
 }
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
Change thread priority.
Change the priority of a running thread. There is no need for an extra yield after it, if the priorities require, there is an implicit reschedule.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1006 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, osErrorValue, osOK, and osPriorityError.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (thread_id == nullptr)
     {
       return osErrorParameter;
     }
   thread::state_t state =
       (reinterpret_cast<Thread&> (*thread_id)).sched_state ();
   if (state == thread::state::undefined || state >= thread::state::destroyed)
     {
       return osErrorResource;
     }
   if (priority < osPriorityIdle || priority >= osPriorityError)
     {
       return osErrorValue;
     }
   // Call C++ mutator.
   thread::priority_t prio = static_cast<thread::priority_t> (priority);
   result_t res = ((reinterpret_cast<Thread&> (*thread_id)).sched_prio (prio));
   // A mandatory yield is needed here, must be done
   // by the implementation.
   if (res == result::ok)
     {
       return osOK;
     }
   else if (res == EINVAL)
     {
       return osErrorValue;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osThreadTerminate (osThreadId thread_id)
Terminate a thread.
Remove the thread function from the active thread list. If the thread is currently RUNNING the execution will stop.
Note
In case that osThreadTerminate terminates the currently running task, the function never returns and other threads that are in the READY state are started.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 944 of file os-c-wrapper.cpp.
References os::rtos::this_thread::exit(), os::rtos::scheduler::in_handler_mode(), osErrorISR, osErrorParameter, osErrorResource, osOK, and os::rtos::this_thread::thread().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (thread_id == nullptr)
     {
       return osErrorParameter;
     }
   thread::state_t state =
       (reinterpret_cast<Thread&> (*thread_id)).sched_state ();
   if (state == thread::state::undefined)
     {
       return osErrorResource;
     }
   if ((reinterpret_cast<Thread*> (thread_id)) == &this_thread::thread ())
     {
       this_thread::exit ();
       /* NORETURN */
     }
   else
     {
       (reinterpret_cast<Thread&> (*thread_id)).kill ();
     }
   return osOK;
 }
osStatus osThreadYield (void)
Yield control.
Pass control to the next thread that is in state READY. If there is no other thread in the state READY, the current thread continues execution and no thread switching occurs.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 985 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), osErrorISR, osOK, and os::rtos::this_thread::yield().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   this_thread::yield ();
   return osOK;
 }
osTimerId osTimerCreate (const osTimerDef_t * timer_def, os_timer_type type, void * args)
Create a timer.
Create a one-shot or periodic timer and associate it with a callback function argument. The timer is initially stopped and must be started with osTimerStart().
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1179 of file os-c-wrapper.cpp.
References attr, os_timer_def::data, os::rtos::scheduler::in_handler_mode(), os_timer_def::name, and os_timer_def::ptimer.
 {
   if (scheduler::in_handler_mode ())
     {
       return nullptr;
     }
   if (timer_def == nullptr)
     {
       return nullptr;
     }
   timer::Attributes attr
     { timer_def->name };
   attr.tm_type = (timer::type_t) type;
   return reinterpret_cast<osTimerId> (new ((void*) timer_def->data) Timer (
       attr, (timer::func_t) timer_def->ptimer, (timer::func_args_t) args));
 }
osStatus osTimerDelete (osTimerId timer_id)
Delete the timer.
Delete the timer object that was created by osTimerCreate.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1271 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), osErrorISR, osErrorParameter, and osOK.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (timer_id == nullptr)
     {
       return osErrorParameter;
     }
   (reinterpret_cast<Timer&> (*timer_id)).~Timer ();
   return osOK;
 }
osStatus osTimerStart (osTimerId timer_id, uint32_t millisec)
Start the timer.
Start or restart the timer.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1206 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osOK, os::rtos::scheduler::start(), and os::rtos::Systick_clock::ticks_cast().
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (timer_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t res = (reinterpret_cast<Timer&> (*timer_id)).start (
       Systick_clock::ticks_cast (millisec * 1000u));
   if (res == result::ok)
     {
       return osOK;
     }
   else
     {
       return osErrorOS;
     }
 }
osStatus osTimerStop (osTimerId timer_id)
Stop the timer.
Warning
Cannot be invoked from Interrupt Service Routines.
Definition at line 1237 of file os-c-wrapper.cpp.
References os::rtos::scheduler::in_handler_mode(), os::rtos::result::ok, osErrorISR, osErrorOS, osErrorParameter, osErrorResource, and osOK.
 {
   if (scheduler::in_handler_mode ())
     {
       return osErrorISR;
     }
   if (timer_id == nullptr)
     {
       return osErrorParameter;
     }
   result_t res = (reinterpret_cast<Timer&> (*timer_id)).stop ();
   if (res == result::ok)
     {
       return osOK;
     }
   else if (res == EAGAIN)
     {
       return osErrorResource;
     }
   else
     {
       return osErrorOS;
     }
 }