CMSIS++ Reference: src/cmsis-plus/startup/startup.c File Reference
startup.c File Reference
#include <cmsis-plus/diag/trace.h>
#include <stdint.h>
#include <sys/types.h>
Macros
#define OS_INCLUDE_STARTUP_GUARD_CHECKS (1)
Functions
void __initialize_args (int *, char ***)
int main (int argc, char *argv[])
void __attribute__ ((noreturn))
void __attribute__ ((always_inline))
void __attribute__ ((section(".after_vectors"), noreturn, weak))
void __attribute__ ((weak))
Variables
unsigned int _sidata
unsigned int _sdata
unsigned int _edata
unsigned int __bss_start__
unsigned int __bss_end__
void(* __preinit_array_start [])(void)
Macro Definition Documentation
#define OS_INCLUDE_STARTUP_GUARD_CHECKS (1)
Definition at line 51 of file startup.c.
Function Documentation
void __attribute__ ((noreturn))
Definition at line 94 of file startup.c.
References trace_puts().
Referenced by __attribute__(), and __gnu_cxx::__verbose_terminate_handler().
 {
   // Iterate and copy word by word.
   // It is assumed that the pointers are word aligned.
   unsigned int *p = region_begin;
   while (p < region_end)
     *p++ = *from++;
 }
void __attribute__ ((always_inline)) inline
Definition at line 136 of file startup.c.
References __attribute__(), and __preinit_array_start.
 {
   // Iterate and clear word by word.
   // It is assumed that the pointers are word aligned.
   unsigned int *p = region_begin;
   while (p < region_end)
     *p++ = 0;
 }
void __attribute__ ((section(".after_vectors"), noreturn, weak))
Definition at line 228 of file startup.c.
References __bss_end__, __bss_start__, __initialize_args(), __initialize_hardware(), __initialize_hardware_early(), __initialize_trace(), _edata, _sdata, _sidata, argc, argv, and main().
 {
   // Initialise hardware right after reset, to switch clock to higher
   // frequency and have the rest of the initialisations run faster.
   //
   // Mandatory on platforms like Kinetis, which start with the watch dog
   // enabled and require an early sequence to disable it.
   //
   // Also useful on platform with external RAM, that need to be
   // initialised before filling the BSS section.
   __initialize_hardware_early ();
   // Use Old Style DATA and BSS section initialisation,
   // that will manage a single BSS sections.
 #if defined(DEBUG) && (OS_INCLUDE_STARTUP_GUARD_CHECKS)
   __data_begin_guard = DATA_GUARD_BAD_VALUE;
   __data_end_guard = DATA_GUARD_BAD_VALUE;
 #endif
 #if !defined(OS_INCLUDE_STARTUP_INIT_MULTIPLE_RAM_SECTIONS)
   // Copy the DATA segment from Flash to RAM (inlined).
   __initialize_data (&_sidata, &_sdata, &_edata);
 #else
   // Copy the data sections from flash to SRAM.
   for (unsigned int* p = &__data_regions_array_start;
       p < &__data_regions_array_end;)
     {
       unsigned int* from = (unsigned int *) (*p++);
       unsigned int* region_begin = (unsigned int *) (*p++);
       unsigned int* region_end = (unsigned int *) (*p++);
       __initialize_data (from, region_begin, region_end);
     }
 #endif
 #if defined(DEBUG) && (OS_INCLUDE_STARTUP_GUARD_CHECKS)
   if ((__data_begin_guard != DATA_BEGIN_GUARD_VALUE)
       || (__data_end_guard != DATA_END_GUARD_VALUE))
     {
       for (;;)
         ;
     }
 #endif
 #if defined(DEBUG) && (OS_INCLUDE_STARTUP_GUARD_CHECKS)
   __bss_begin_guard = BSS_GUARD_BAD_VALUE;
   __bss_end_guard = BSS_GUARD_BAD_VALUE;
 #endif
 #if !defined(OS_INCLUDE_STARTUP_INIT_MULTIPLE_RAM_SECTIONS)
   // Zero fill the BSS section (inlined).
   __initialize_bss (&__bss_start__, &__bss_end__);
 #else
   // Zero fill all bss segments
   for (unsigned int *p = &__bss_regions_array_start;
       p < &__bss_regions_array_end;)
     {
       unsigned int* region_begin = (unsigned int*) (*p++);
       unsigned int* region_end = (unsigned int*) (*p++);
       __initialize_bss (region_begin, region_end);
     }
 #endif
 #if defined(DEBUG) && (OS_INCLUDE_STARTUP_GUARD_CHECKS)
   if ((__bss_begin_guard != 0) || (__bss_end_guard != 0))
     {
       for (;;)
         ;
     }
 #endif
   // Hook to continue the initialisations. Usually compute and store the
   // clock frequency in the global CMSIS variable, cleared above.
   __initialize_hardware ();
   // Initialise the trace output device. From this moment on,
   // trace_printf() calls are available (including in static constructors).
   __initialize_trace();
   // Get the argc/argv (useful in semihosting configurations).
   int argc;
   char** argv;
   __initialize_args (&argc, &argv);
   // Call the standard library initialisation (mandatory for C++ to
   // execute the constructors for the static objects).
   __run_init_array ();
   // Call the main entry point, and save the exit code.
   int code = main (argc, argv);
   // Run the C++ static destructors.
   __run_fini_array ();
   _exit (code);
   // Should never reach this, _exit() should have already
   // performed a reset.
   for (;;)
     ;
   /* NOTREACHED */
 }
void __attribute__ ((weak))
Definition at line 363 of file startup.c.
References argv.
 {
   // By the time we reach this, the data and bss should have been initialised.
   // The strings pointed to by the argv array shall be modifiable by the
   // program, and retain their last-stored values between program startup
   // and program termination. (static, no const)
   static char name[] = "";
   // The string pointed to by argv[0] represents the program name;
   // argv[0][0] shall be the null character if the program name is not
   // available from the host environment. argv[argc] shall be a null pointer.
   // (static, no const)
   static char* argv[2] =
     { name, NULL };
   *p_argc = 1;
   *p_argv = &argv[0];
 #if __STDC_HOSTED__ != 0
   // temporary here
   initialise_monitor_handles ();
 #endif
   return;
 }
void __initialize_args (int * , char ***)
Referenced by __attribute__().
int main (int argc, char * argv[])
Referenced by __attribute__(), and os::rtos::thread::main_trampoline().
Variable Documentation
unsigned int __bss_end__
Referenced by __attribute__().
unsigned int __bss_start__
Referenced by __attribute__().
void(* __preinit_array_start[])(void)
Referenced by __attribute__().
unsigned int _edata
Referenced by __attribute__().
unsigned int _sdata
Referenced by __attribute__().
unsigned int _sidata
Referenced by __attribute__().