CMSIS++ Reference: include/cmsis-plus/diag/trace.h File Reference
trace.h File Reference
#include <cstdint>
#include <cstddef>
#include <cstdarg>
#include <sys/types.h>
Namespaces
os
os::trace
Functions
void __attribute__ ((always_inline)) trace_dbg_bkpt(void)
void os::trace::initialize (void)
Initialise the RTOS.
ssize_t os::trace::write (const void *buf, std::size_t nbyte)
int os::trace::printf (const char *format,...)
int os::trace::vprintf (const char *format, std::va_list args)
int os::trace::puts (const char *s)
int os::trace::putchar (int c)
void os::trace::dump_args (int argc, char *argv[])
void os::trace::__attribute__ ((always_inline)) dbg_bkpt(void)
void __initialize_trace (void)
ssize_t trace_write (const void *buf, size_t nbyte)
int trace_printf (const char *format,...)
int trace_vprintf (const char *format, va_list args)
int trace_puts (const char *s)
int trace_putchar (int c)
void trace_dump_args (int argc, char *argv[])
Function Documentation
void __attribute__ ((always_inline)) inline
Definition at line 58 of file trace.h.
 {
   asm volatile ("bkpt 0");
 }
void __initialize_trace (void)
Called from startup.
Referenced by os::trace::__attribute__(), and __attribute__().
void trace_dump_args (int argc, char * argv[])
Definition at line 217 of file trace.cpp.
References os::trace::dump_args().
Referenced by os::trace::__attribute__().
 {
   trace::dump_args (argc, argv);
 }
int trace_printf (const char * format, ...)
Definition at line 187 of file trace.cpp.
References os::trace::args, os::trace::ret, os::trace::va_end(), os::trace::va_start(), and os::trace::vprintf().
Referenced by __attribute__(), os::trace::__attribute__(), os::estd::__throw_cmsis_error(), and os::estd::__throw_system_error().
 {
   std::va_list args;
   va_start(args, format);
   int ret = trace::vprintf (format, args);
   va_end(args);
   return ret;
 }
int trace_putchar (int c)
Definition at line 211 of file trace.cpp.
References os::trace::putchar().
Referenced by os::trace::__attribute__().
 {
   return trace::putchar (c);
 }
int trace_puts (const char * s)
Definition at line 205 of file trace.cpp.
References os::trace::puts().
Referenced by __attribute__(), os::trace::__attribute__(), __cxa_pure_virtual(), and __gnu_cxx::__verbose_terminate_handler().
 {
   return trace::puts (s);
 }
int trace_vprintf (const char * format, va_list args)
Definition at line 199 of file trace.cpp.
References os::trace::vprintf().
Referenced by os::trace::__attribute__().
 {
   return trace::vprintf (format, args);
 }
ssize_t trace_write (const void * buf, size_t nbyte)
Referenced by os::trace::__attribute__(), and __attribute__().