CMSIS++ Reference: src/cmsis-plus/diag/trace.cpp File Reference
trace.cpp File Reference
#include <cmsis-plus/diag/trace.h>
#include <cstdarg>
#include <cstdio>
#include <cstring>
Namespaces
os
os::trace
Macros
#define OS_INTEGER_TRACE_PRINTF_TMP_ARRAY_SIZE (200)
Functions
void os::trace::__attribute__ ((weak)) write(const void *buf __attribute__((unused))
Write the given number of bytes to the trace output channel.
int os::trace::va_start (args, format)
os::trace::va_end (args)
os::trace::if (ret > 0)
os::trace::for (int i=0;i< argc;++i)
os::trace::printf ("]);\n")
void __attribute__ ((weak)) __initialize_trace(void)
int trace_printf (const char *format,...)
int trace_vprintf (const char *format, va_list args)
int trace_puts (const char *s)
int trace_putchar (int c)
void trace_dump_args (int argc, char *argv[])
Variables
ssize_t std::size_t os::trace::nbyte
int os::trace::ret = vprintf (format, args)
int std::va_list os::trace::args
void char * os::trace::argv []
ssize_t std::size_t nbyte
Macro Definition Documentation
#define OS_INTEGER_TRACE_PRINTF_TMP_ARRAY_SIZE (200)
Definition at line 28 of file trace.cpp.
Function Documentation
void __attribute__ ((weak))
Definition at line 145 of file trace.cpp.
References os::trace::__attribute__(), os::trace::initialize(), and trace_write().
 {
   trace::initialize ();
 }
void trace_dump_args (int argc, char * argv[])
Definition at line 217 of file trace.cpp.
References os::trace::dump_args().
Referenced by os::trace::__attribute__().
 {
   trace::dump_args (argc, argv);
 }
int trace_printf (const char * format, ...)
Definition at line 187 of file trace.cpp.
References os::trace::args, os::trace::ret, os::trace::va_end(), os::trace::va_start(), and os::trace::vprintf().
Referenced by __attribute__(), os::trace::__attribute__(), os::estd::__throw_cmsis_error(), and os::estd::__throw_system_error().
 {
   std::va_list args;
   va_start(args, format);
   int ret = trace::vprintf (format, args);
   va_end(args);
   return ret;
 }
int trace_putchar (int c)
Definition at line 211 of file trace.cpp.
References os::trace::putchar().
Referenced by os::trace::__attribute__().
 {
   return trace::putchar (c);
 }
int trace_puts (const char * s)
Definition at line 205 of file trace.cpp.
References os::trace::puts().
Referenced by __attribute__(), os::trace::__attribute__(), __cxa_pure_virtual(), and __gnu_cxx::__verbose_terminate_handler().
 {
   return trace::puts (s);
 }
int trace_vprintf (const char * format, va_list args)
Definition at line 199 of file trace.cpp.
References os::trace::vprintf().
Referenced by os::trace::__attribute__().
 {
   return trace::vprintf (format, args);
 }
Variable Documentation
ssize_t std::size_t nbyte
Initial value:
{
  return trace::write (buf, nbyte)
Definition at line 153 of file trace.cpp.